# -*- coding: utf-8 -*-
"""
2026年 大学入学共通テスト 英語(リーディング) 解答・解説
コンテンツ定義（本文全文 + 設問別の正解/解説/本文該当箇所）
"""

# ============================================================
# 解答一覧 (大問, 問, 設問番号, 正解)  ※正解は表示用文字列
# ============================================================
ANSWER_KEY = [
    ("第1問", "問1", "1",  "③", 2),
    ("",      "問2", "2",  "①", 2),
    ("",      "問3", "3",  "②", 2),
    ("第2問", "問1", "4",  "①", 3),
    ("",      "問2", "5",  "③", 3),
    ("",      "問3", "6",  "④", 3),
    ("",      "問4", "7",  "②", 3),
    ("第3問", "問1", "8",  "②", 2),
    ("",      "問2", "9",  "②", 1),
    ("",      "",    "10", "③", 1),
    ("",      "",    "11", "⑤", 1),
    ("",      "",    "12", "①", 1),
    ("",      "問3", "13", "④", 3),
    ("第4問", "問1", "14", "③", 3),
    ("",      "問2", "15", "③", 3),
    ("",      "問3", "16", "①", 3),
    ("",      "問4", "17", "③", 3),
    ("第5問", "問1", "18", "③", 2),
    ("",      "問2", "19", "④", 3),
    ("",      "問3", "20", "⑤", 3),
    ("",      "問4", "21", "③", 3),
    ("",      "問5", "22", "③/⑤", 5),  # 22・23 順不同
    ("第6問", "問1", "24", "①/④", 4),  # 24・25 順不同
    ("",      "問2", "26", "③", 2),
    ("",      "",    "27", "④", 1),
    ("",      "",    "28", "①", 1),
    ("",      "",    "29", "⑤", 1),
    ("",      "問3", "30", "④", 3),
    ("",      "問4", "31", "②", 3),
    ("第7問", "問1", "32", "③", 3),
    ("",      "問2", "33", "①/④", 4),  # 33・34 順不同
    ("",      "問3", "35", "②", 3),
    ("",      "問4", "36", "①", 3),
    ("",      "問5", "37", "④", 3),
    ("第8問", "問1", "38", "④", 3),
    ("",      "問2", "39", "①", 3),
    ("",      "問3", "40", "③/⑤", 4),  # 40・41 順不同
    ("",      "",    "42", "①", 3),
    ("",      "問4", "43", "②", 3),
    ("",      "問5", "44", "③", 4),
]

# ============================================================
# 本編データ
#   各大問: num, points, theme, situation, passages[], questions[]
#   passage: {kind:'dialogue'|'box'|'plain', title, items}
#     dialogue item: (speaker, text)
#     box/plain item: paragraph text (str)
#   question: dict(label, qtext, choices[(mark,text)], answer, explain, evidence[(en,ja)])
# ============================================================

SECTIONS = []

# -------------------- 第1問 --------------------
SECTIONS.append(dict(
    num="第1問", points=6,
    theme="ダンス部の衣装をめぐるメッセージのやり取り（チャット読解）",
    situation="あなたは国際ダンス部に所属し、来月のダンスコンテストの衣装について部員（Pat・Jessie・Val）とメッセージを交換している。",
    passages=[dict(kind="dialogue", title="Text messages（メッセージのやり取り）", items=[
        ("You", "Hey, everyone. We still haven't decided what to wear on stage yet. Any ideas?"),
        ("Pat", "I think our costumes should match the music. It starts with Scottish bagpipes, so a traditional check pattern like the one in this photo could work. What about wearing shirts with a similar pattern?"),
        ("Jessie", "Good suggestion. Also, when the music changes in the middle to hip-hop, why not change our look, too? We could put on accessories like necklaces."),
        ("Pat", "Our dance has jumping and twisting, so necklaces might be dangerous. How about sunglasses instead?"),
        ("Val", "Mmm, sunglasses might make it hard to see. We might fall off the stage. But Jessie, I do like your idea of switching our look to the music. Right before the hip-hop part starts, we could take off the check shirts to show black tank tops inside. A dark color would match the sound of the bass guitar and drums."),
        ("You", "Nice ideas, everyone. Let's not forget to talk with our instructor before we make the final decision about what costumes to buy. She said she's available before rehearsal tomorrow."),
    ])],
    questions=[
        dict(label="問1（解答番号 1）",
             qtext="Which two people are worried about the safety of the dancers?（ダンサーの安全を心配しているのは誰と誰か）",
             choices=[("①","Jessie and Val"),("②","Pat and Jessie"),("③","Pat and Val"),("④","Val and the instructor")],
             answer="③",
             explain="「安全（safety）への心配」を述べているのは2人。Pat は「ネックレスは（跳んだりひねったりするダンスだから）危険かもしれない」と言い、Val は「サングラスは見えにくくなり、ステージから落ちるかもしれない」と言っている。どちらも“けがの危険”を指摘しているので、③ Pat and Val が正解。Jessie はアクセサリー着用を提案しただけで安全には触れていない。",
             evidence=[
                 ("Pat: Our dance has jumping and twisting, so necklaces might be dangerous.","跳躍やひねりがあるダンスなので、ネックレスは危険かもしれない。"),
                 ("Val: sunglasses might make it hard to see. We might fall off the stage.","サングラスは視界が悪くなるかもしれない。ステージから落ちるかもしれない。"),
             ]),
        dict(label="問2（解答番号 2）",
             qtext="According to Val's suggestion, how would the costumes look during the second half of the performance?（Val の提案によると、後半の衣装はどう見えるか）",
             choices=[("①","（黒いタンクトップのみ）"),("②","（チェック柄シャツを着たまま）"),("③","（チェックの上着を羽織る）"),("④","（タンクトップ＋サングラス）")],
             answer="①",
             explain="Val は「ヒップホップの部分が始まる直前にチェックのシャツを脱ぎ、中の黒いタンクトップを見せよう」と提案している。さらに Val 自身がサングラスは却下している。したがって後半（second half）の見た目は“チェックシャツなし・サングラスなしの黒いタンクトップ姿”＝①。②③はチェックシャツを着たまま、④はサングラスを掛けているので不適。",
             evidence=[
                 ("Val: Right before the hip-hop part starts, we could take off the check shirts to show black tank tops inside.","ヒップホップ部分が始まる直前に、チェックのシャツを脱いで中の黒いタンクトップを見せられる。"),
             ]),
        dict(label="問3（解答番号 3）",
             qtext="According to the text messages, which of the following will your team probably do first tomorrow?（明日まず最初に行うと考えられることは何か）",
             choices=[("①","Buy the dance clothes"),("②","Consult with the instructor"),("③","Decide on the program"),("④","Rehearse the dance routine")],
             answer="②",
             explain="最後の You の発言が決め手。「買う衣装を最終決定する前に、指導者（instructor）に相談するのを忘れないようにしよう。先生は明日のリハーサルの前なら空いている」とある。つまり“リハーサル前にまず指導者に相談する”ので②が正解。衣装購入（①）はその相談の後。",
             evidence=[
                 ("You: Let's not forget to talk with our instructor before we make the final decision about what costumes to buy. She said she's available before rehearsal tomorrow.","衣装購入を最終決定する前に指導者に相談しよう。先生は明日のリハーサルの前なら時間が取れると言っていた。"),
             ]),
    ],
))

# -------------------- 第2問 --------------------
SECTIONS.append(dict(
    num="第2問", points=12,
    theme="大学寮（campus accommodation）の満足度調査と入居者コメント",
    situation="あなたは英国の大学に入学予定で、大学の寮について考えている。大学公式サイトに掲載された入居者アンケート結果と、入居者のコメントを読む。",
    passages=[
        dict(kind="box", title="Posted by the University Administration（大学事務局による投稿・2026年1月5日）／ Campus Accommodation: Satisfaction Survey", items=[
            "Keeping students healthy and happy is our mission. We do a survey every two years to improve student services. Last year, 85% of residents responded. Although this response rate is not perfect, we believe it is sufficient for the results to be trusted.",
            "Of those who responded, a large majority (82%) said that they felt safe in campus accommodation. This was up five percentage points from the previous survey. A majority (73%) also said that meals were delicious. Unfortunately, only 45% of respondents said that the food was healthy. This was a drop of eight percentage points from the previous survey. We are introducing more salads, but popular dishes like fish and chips will remain.",
            "Most importantly, over 90% of respondents said that, in general, they were satisfied with their stay in campus accommodation.",
        ]),
        dict(kind="box", title="Naoki のコメント", items=[
            "Most Japanese students tend to choose a homestay, but not me. I thought it over and finally decided on campus accommodation. It was a good choice because I made lasting friends of my own age. Meals were the weakest point, but deliveries from local restaurants were an excellent alternative.",
        ]),
        dict(kind="box", title="Helga のコメント", items=[
            "I loved the food there. I could eat as much as I liked. The big concern was non-residents could freely come and go on weekends. Also, lively parties and loud voices might put your exam results in danger. One more thing, the chairs in the shared meeting places will hurt your back.",
        ]),
    ],
    questions=[
        dict(label="問1（解答番号 4）",
             qtext="Which option best describes the administration's opinion?（大学事務局の「意見」を最もよく表すのはどれか）※事実ではなく opinion を問う",
             choices=[("①","The findings are reliable because enough residents responded."),
                      ("②","The results of the survey are being reported in the year 2026."),
                      ("③","The students should make more effort to have a healthier lifestyle."),
                      ("④","The survey is conducted annually to improve student services.")],
             answer="①",
             explain="設問は opinion（意見・主観）を問うのがポイント。事務局は「回答率は完璧ではないが、結果を信頼するのに十分だと“私たちは考える（we believe）”」と述べている。これは主観的判断＝意見なので①が正解。②は時期を述べた事実、④は「毎年（annually）」が誤り（本文は every two years＝隔年）。③は本文に記述なし。",
             evidence=[
                 ("Although this response rate is not perfect, we believe it is sufficient for the results to be trusted.","回答率は完璧ではないが、結果を信頼するには十分だと私たちは考えている。"),
                 ("We do a survey every two years …","私たちは隔年で調査を行っている（→④の annually は誤り）。"),
             ]),
        dict(label="問2（解答番号 5）",
             qtext="Which is true according to the administration's report?（事務局の報告によると正しいものはどれか）",
             choices=[("①","Most respondents said food at campus accommodation was not tasty."),
                      ("②","Most respondents were dissatisfied with campus accommodation."),
                      ("③","The percentage of respondents saying the food was healthy decreased."),
                      ("④","The percentage of respondents who felt security was good decreased.")],
             answer="③",
             explain="「食事が健康的だと答えた人は45%のみで、前回調査から8ポイント低下した」とあるので③が正解。①は73%が「おいしい」と回答しているので誤り。②は90%超が「満足」なので誤り。④は安全だと感じた人は82%で前回より5ポイント“上昇”しているので誤り（decreased が逆）。",
             evidence=[
                 ("only 45% of respondents said that the food was healthy. This was a drop of eight percentage points from the previous survey.","食事が健康的だと答えたのは回答者の45%のみで、前回調査から8ポイントの低下だった。"),
                 ("(82%) said that they felt safe … This was up five percentage points","82%が安全だと感じたと回答し、前回より5ポイント上昇した（→④は逆）。"),
             ]),
        dict(label="問3（解答番号 6）",
             qtext="Which option best reflects Naoki's comment?（Naoki のコメントを最もよく反映するものはどれか）",
             choices=[("①","He believed most Japanese students avoid choosing a homestay."),
                      ("②","He disliked the option of using deliveries from local restaurants."),
                      ("③","He doubted the strength of the relationship with friends he had made."),
                      ("④","He was satisfied with his decision to stay in campus accommodation.")],
             answer="④",
             explain="Naoki は「よく考えて寮を選んだ。同年代の長く続く友人ができたので良い選択だった」と述べている。寮を選んだ自分の決断に満足しているので④が正解。①は「多くの日本人学生はホームステイを“選ぶ傾向がある”」と言っているので avoid（避ける）は逆。②は地元レストランの配達を「優れた代替手段」と評価しているので逆。③は「長く続く友人」と言っており友情を疑ってはいない。",
             evidence=[
                 ("It was a good choice because I made lasting friends of my own age.","同年代の長く続く友人ができたので、（寮にしたのは）良い選択だった。"),
                 ("Meals were the weakest point, but deliveries from local restaurants were an excellent alternative.","食事は最大の弱点だったが、地元レストランからの配達が優れた代替手段だった（→②は逆）。"),
             ]),
        dict(label="問4（解答番号 7）",
             qtext="Based on Helga's comment, what can be said about campus accommodation?（Helga のコメントから寮について言えることは何か）",
             choices=[("①","It provides comfortable common areas for residents."),
                      ("②","Noise there might interfere with your studies."),
                      ("③","Servings of food in the dining hall are too small."),
                      ("④","The security there is a strong point for residents.")],
             answer="②",
             explain="Helga は「にぎやかなパーティーや大きな声が試験の成績を危うくするかもしれない」と懸念している。つまり“騒音が勉強の妨げになりうる”＝②が正解。①は「共用スペースの椅子は腰を痛める」と言っており快適ではないので逆。③は「好きなだけ食べられた」と言っており量は十分なので逆。④は「週末に部外者が自由に出入りできる」ことを大きな懸念としており、防犯はむしろ弱点なので逆。",
             evidence=[
                 ("lively parties and loud voices might put your exam results in danger.","にぎやかなパーティーや大きな声が、試験の成績を危うくするかもしれない。"),
                 ("The big concern was non-residents could freely come and go on weekends.","大きな懸念は、週末に部外者が自由に出入りできることだった（→④の防犯が強みは誤り）。"),
             ]),
    ],
))

# -------------------- 第3問 --------------------
SECTIONS.append(dict(
    num="第3問", points=9,
    theme="物語文「The Bug Cup（虫のカップ）」— マインドフルネス講座での出来事",
    situation="英語の先生から、次の授業のために次の短い物語を読むよう言われた。",
    passages=[dict(kind="box", title="The Bug Cup", items=[
        "My high school classmate and I were sitting an hour with our legs crossed and our eyes closed, trying to feel our breath. I had signed up for this special workshop to learn how to control my thoughts and emotions. My father had recommended it to me. He said it might help me focus my mind, lower my stress, and hopefully improve my grades at school. My friend came along to see if it could help him, too.",
        "Sometime during the session I heard a faint buzzing sound, but little by little I could hear it more clearly. It was a small insect. It flew very close to my right ear and almost went in it! I wanted to hit it with my hand, but we weren't supposed to move. “What should I do now?” I thought.",
        "Just as I opened my eyes, the bug flew off toward the instructor. I saw her take a cup and a postcard from nearby. She stood up and trapped the bug in the cup against the wall. Sliding the card between the cup and the wall, she covered the open end of the cup. Then, she did something that really impressed me. She walked to the window, opened it, and let the insect fly out. The instructor softly closed the window and our eyes met. After the session, she came over to me and said, “The bug cup always works. Having a warm heart for all creatures in our life makes for a peaceful mind.”",
        "I don't know yet if the workshop has helped me concentrate better or if it will improve my grades. However, I did learn something important from that bug cup experience.",
    ])],
    questions=[
        dict(label="問1（解答番号 8）",
             qtext="The author joined the workshop because ___.（筆者が講座に参加したのは…だから）",
             choices=[("①","a classmate encouraged him to"),("②","a family member suggested it"),
                      ("③","his father signed him up"),("④","his friend got good grades")],
             answer="②",
             explain="「父がそれ（講座）を私に勧めてくれた」とある。父＝家族の一員（a family member）が提案したので②が正解。③は「父が申し込んだ」だが、本文では“I had signed up（私が申し込んだ）”とあり、申し込んだのは筆者自身なので誤り。①の classmate（友人）は一緒に来ただけ、④の内容は本文になし。",
             evidence=[
                 ("I had signed up for this special workshop … My father had recommended it to me.","私はこの特別講座に申し込んでいた…父がそれを私に勧めてくれた。"),
             ]),
        dict(label="問2（解答番号 9〜12）",
             qtext="Choose four out of the five options (①〜⑤) and put them in the order they appeared in the story.（物語に登場した順に4つ並べよ）  9 → 10 → 11 → 12",
             choices=[("①","The author learned a valuable lesson."),
                      ("②","The author was aware of an annoying noise."),
                      ("③","The insect flew away from the author."),
                      ("④","The instructor caught the bug in her hand."),
                      ("⑤","The instructor released the insect.")],
             answer="② → ③ → ⑤ → ①",
             explain="物語の時系列を追う。①まず筆者が“かすかな羽音（うるさい音）”に気づく＝②。②次に虫が指導者の方へ飛んでいった（＝筆者から離れて飛んだ）＝③。③指導者は虫をカップに閉じ込め、窓を開けて外へ逃がした＝⑤。④最後に筆者は大切な教訓を学んだ＝①。よって ②→③→⑤→① が正解。選ばない1つは④で、指導者は虫を“手で”ではなく“カップ（cup）”で捕らえたので④は本文と矛盾し除外する。",
             evidence=[
                 ("I heard a faint buzzing sound … It was a small insect.","かすかな羽音が聞こえた…小さな虫だった。（②）"),
                 ("the bug flew off toward the instructor.","虫は指導者の方へ飛んでいった。（③＝筆者から離れた）"),
                 ("She … trapped the bug in the cup … let the insect fly out.","彼女は虫をカップに閉じ込め…外へ逃がした。（⑤・カップであって手ではない→④は誤り）"),
                 ("I did learn something important from that bug cup experience.","あの“虫のカップ”の経験から大切なことを学んだ。（①）"),
             ]),
        dict(label="問3（解答番号 13）",
             qtext="From the instructor, the author most likely understood the importance of being ___ to all living things.（指導者から、すべての生き物に対して…であることの大切さを理解したと考えられる）",
             choices=[("①","attractive"),("②","cruel"),("③","strict"),("④","tender")],
             answer="④",
             explain="指導者は「人生のすべての生き物に温かい心を持つことが、穏やかな心につながる」と語り、実際に虫を殺さず逃がした。すべての生き物に“優しく（tender）”あることの大切さ＝④が正解。②cruel（残酷）、③strict（厳格）は逆、①attractive（魅力的）は無関係。",
             evidence=[
                 ("Having a warm heart for all creatures in our life makes for a peaceful mind.","人生のすべての生き物に温かい心を持つことが、穏やかな心をつくる。"),
                 ("She … opened it, and let the insect fly out.","彼女は窓を開けて虫を外へ逃がした。（優しさを行動で示した）"),
             ]),
    ],
))

# -------------------- 第4問 --------------------
SECTIONS.append(dict(
    num="第4問", points=12,
    theme="英語部の校内ニュースレター原稿（Eco Week 特集）と顧問のコメント（推敲問題）",
    situation="英語部で、学校の Eco Week（廃棄物管理がテーマ）を宣伝するオンライン・ニュースレターを書いている。下は最新の原稿で、右側に部顧問のコメント（1）〜（4）が付いている。",
    passages=[
        dict(kind="box", title="English Club Times（2026年1月）／ Join Eco Week Activities", items=[
            "The waste produced around the world is a continuing challenge. We must think of better methods to reduce and manage waste, and we can start at school. To raise awareness of waste management, we want to inform you about three activities for Eco Week 2026.",
            "One activity is (1)a poster contest. During Eco Week, we will vote to decide on the top three posters based on the message and design. They will be posted on the school website after Eco Week so that students can keep in mind the importance of waste management.",
            "(2)〔Another activity is a garbage collecting race which students from other schools can also join. Here's what to do. First, make a team of three. <A> Then, on the morning of the race, meet at the local seashore, and receive tools and bags. <B> Listen to the organizer explain the aim and rules of the race. <C> Join the closing ceremony to see if your team has won. <D> The winning team will be featured on the local city website.〕 Through this activity, we will enjoy working together to create a clean environment.",
            "The third activity is an eco-friendly fashion show. Students will make original items using clothing from their closet. (3)Making our own clothes is enjoyable. The most creative entries will be chosen and the winning ones will be exhibited in our hall.",
            "Through these Eco Week 2026 activities, we will be able to (4)acquire recycling skills for waste management. This school campaign will include a poster contest, a garbage collecting race, and an eco-friendly fashion show. We can make a difference to improve our environment. Let's think globally and act locally!",
        ]),
        dict(kind="box", title="Comments（顧問のコメント）", items=[
            "(1) What is the purpose of making the posters? Explain it.",
            "(2) Readers want to know how the winners will be decided. Add it.",
            "(3) This sentence doesn't seem to fit well here. Rewrite it.",
            "(4) This part does not summarize your main argument. Rewrite it.",
            "Overall comments: Your draft introduces eco activities well. I hope many students join them!",
        ]),
    ],
    questions=[
        dict(label="問1（解答番号 14）",
             qtext="Based on Comment (1), choose the best phrase to add after the underlined part.（コメント(1)に基づき、下線部 a poster contest の後に加える最適な語句を選べ）",
             choices=[("①","to advertise a new school website"),
                      ("②","to discover the best artists in the school"),
                      ("③","to promote eco-friendly actions among students"),
                      ("④","to recruit more English Club members")],
             answer="③",
             explain="コメント(1)は「ポスターを作る“目的”は何か。説明せよ」と求めている。ニュースレター全体のテーマは廃棄物管理（waste management）の意識向上であり、ポスターはその意識を高めるためのもの。よって「生徒の間で環境に優しい行動を促すため」＝③が目的として最適。①④はテーマ（環境）と無関係、②は“最も上手な芸術家を見つける”でコンテストの本来の目的とずれる。",
             evidence=[
                 ("To raise awareness of waste management, we want to inform you about three activities …","廃棄物管理への意識を高めるために、3つの活動を紹介したい。（ポスターも意識向上＝環境行動の促進が目的）"),
             ]),
        dict(label="問2（解答番号 15）",
             qtext="Based on Comment (2), choose the best place to add the sentence: “Pick up more garbage than other teams in an hour.”（コメント(2)に基づき、この文を入れる最適な場所 <A>〜<D> を選べ）",
             choices=[("①","<A>"),("②","<B>"),("③","<C>"),("④","<D>")],
             answer="③",
             explain="コメント(2)は「読者は“どうやって勝者が決まるか”を知りたい。それを加えよ」と求めている。挿入文「1時間で他のチームより多くのゴミを拾う」は“勝敗の決め方（競技内容）”を示す。手順は『道具と袋を受け取る→<B>→主催者がルールを説明する→<C>→勝ったか確認する閉会式に参加』なので、ルール説明の直後で、勝敗確認（閉会式）の前にあたる <C>＝③が最適。ここでレースの中身（勝ち方）を述べてから結果を見に行く流れになる。",
             evidence=[
                 ("Listen to the organizer explain the aim and rules of the race. <C> Join the closing ceremony to see if your team has won.","主催者がレースの目的とルールを説明するのを聞く。<C> 自分のチームが勝ったか確認する閉会式に参加する。（ルール説明の後＝<C>に“勝ち方”を入れる）"),
             ]),
        dict(label="問3（解答番号 16）",
             qtext="Based on Comment (3), choose the best sentence to replace the underlined sentence.（コメント(3)に基づき、下線部の文を置き換える最適な文を選べ）",
             choices=[("①","This activity will help students to appreciate various ways of reusing old clothes."),
                      ("②","This activity will influence more students to ask the fashion industry to lower prices for old clothes."),
                      ("③","This activity will lead to the growth of the market for fast fashion over the one for used clothes."),
                      ("④","This activity will provide students with opportunities for improving their business skills to sell used clothes.")],
             answer="①",
             explain="下線部「自分の服を作るのは楽しい」は、廃棄物管理というテーマに合わない（コメント(3)＝“ここにうまく合わない。書き直せ”）。ファッションショーは“クローゼットにある服（古着）を使って”作るので、テーマに合うのは「古着を再利用するさまざまな方法を理解する助けになる」＝①。③は fast fashion（使い捨て型）の市場拡大でテーマに逆行、②④は値下げ要求・販売の商売スキルでテーマからずれる。",
             evidence=[
                 ("Students will make original items using clothing from their closet.","生徒はクローゼットにある服を使ってオリジナルの作品を作る。（＝古着の再利用→①が文脈に合う）"),
             ]),
        dict(label="問4（解答番号 17）",
             qtext="Based on Comment (4), choose the best phrase to replace the underlined part.（コメント(4)に基づき、下線部 acquire recycling skills for を置き換える最適な語句を選べ）",
             choices=[("①","become creative artists who focus on"),
                      ("②","cooperate with other high schools on"),
                      ("③","get ourselves more involved in"),
                      ("④","learn how to collect more garbage for")],
             answer="③",
             explain="下線部を含む文は結論部で「これらの活動を通じて、私たちは廃棄物管理を〔　〕できるようになる」。コメント(4)は“ここは主張の要約になっていない。書き直せ”。原稿の主張は冒頭の「廃棄物を減らし管理する、よりよい方法を考えるべき」＝廃棄物管理に積極的に関わること。よって「（廃棄物管理に）もっと自分たちが関わる」＝③が要約として最適。④の“ゴミ集め”はレース1つに限られ全体（3活動）の要約にならず、①②はテーマ外。",
             evidence=[
                 ("We must think of better methods to reduce and manage waste, and we can start at school.","廃棄物を減らし管理するよりよい方法を考えねばならない。学校から始められる。（＝主張：廃棄物管理に関わる→③）"),
             ]),
    ],
))

# -------------------- 第5問 --------------------
SECTIONS.append(dict(
    num="第5問", points=16,
    theme="図書館の絵本フェア案内（リーフレット）＋推薦フォーム（絵本4冊）＋図書館からのメール",
    situation="英国に留学中。町の図書館で見つけたリーフレットを読み、推薦フォームを提出したところ、図書館からメールが届いた。推薦したのは下の絵本4冊。",
    passages=[
        dict(kind="box", title="Readburgh Library ─ Book Recommendations & Volunteers Wanted（リーフレット）", items=[
            "Our library will hold a book fair from 1 to 8 February 2026, to introduce picture books from various countries to Readburgh children. The fair will exhibit books all week in the entrance hall. We are also planning to have ‘Story Time’ reading sessions in The Children's Centre in the library on the final day.",
            "To help improve our selection of books, we are calling for picture book recommendations for preschool children. Additionally, the library is recruiting volunteers to read stories to children during the reading sessions. If you volunteer, you will receive a book coupon.",
            "Please note:  ・Books in the original language or translations are welcome.  ・No book should cost more than £20.  ・The submission period is from 15 December 2025 to 19 January 2026.",
            "Nominate your book(s) and/or register as a volunteer via the online form.  For questions, contact: internationalbookfair@***.lib.uk",
        ]),
        dict(kind="box", title="Library Book Fair Online Form（あなたが提出した推薦フォーム）", items=[
            "Will you be a ‘Story Time’ reader?  → No（「いいえ」を選択）",
            "① Green Demon Blue Demon／Written by Shinichiro Ishida／Year 1990／Price £16／Pictures by Author — This book contains short stories about demons and various animals they encounter. Most stories are heart-warming, but some are not. My favourite is ‘Breakfast Battle.’ Two demons fight over what to feed their pet dog for breakfast. Illustrations are another attractive feature, making it suitable for children between three and five years old.",
            "② Paint! Paint! Paint!／Written by Kaori Ando／Year 2022／Price £8／Pictures by Author — This is a popular picture book for parents to read to their children before they enter primary school. The main character wants to paint the whole world. She paints ceilings in orange, kitchens in purple, and streets and buildings in green. By chance, her cat steps in some paint and leaves paw prints wherever it goes. The world looks more colourful after reading the story.",
            "③ Panda Adventures／Written by Maruo Maru／Year 2021／Price £10／Pictures by Kanako Maru — In this story, a young male panda escapes from a zoo. He meets a schoolboy and they visit places in town together. However, the poor panda is caught and taken back to the zoo. The boy's final words to the panda had me in tears. The story is long, so it is suitable for kids aged over ten.",
            "④ The Cloud Prince／Written by Kamiko Narita／Year 1981／Price £19／Pictures by Author — A boy who lives on a thunder cloud plays tricks on children. The tricks include snow in summer and a rainstorm in the park when they are playing. The children are afraid of him at first, but he rescues an injured goat and they all become friends. This book is read to preschool children all over the world.",
        ]),
        dict(kind="box", title="図書館からのメール（2026年1月17日・件名: Book Recommendations）", items=[
            "Hello, Thank you for your recommendations. In fact, we found that the titles have been translated into multiple languages, which will make the fair truly international. Although one of your entries did not fit the target age range, your other titles are gratefully accepted (refer to the attachment). If you have an additional book recommendation, please email it to us.",
            "As we are still short of volunteers for the last day, would you kindly reconsider? — Thanks again, Library Staff（添付: List of accepted books）",
        ]),
    ],
    questions=[
        dict(label="問1（解答番号 18）",
             qtext="What is the main purpose of the library book fair?（図書館の絵本フェアの主な目的は何か）",
             choices=[("①","To display picture books by Readburgh authors"),
                      ("②","To encourage international students to use the library"),
                      ("③","To familiarise children with stories from around the world"),
                      ("④","To promote foreign book collections in preschools")],
             answer="③",
             explain="リーフレット冒頭に「さまざまな国の絵本を Readburgh の子どもたちに“紹介する”ためにフェアを開く」とある。世界各地の物語に子どもを親しませることが目的＝③。①は“Readburgh の作家による本”が誤り（さまざまな国の本）、②は対象が国際学生ではなく子ども、④は preschools での蔵書宣伝という記述はない。",
             evidence=[
                 ("to introduce picture books from various countries to Readburgh children","さまざまな国の絵本を Readburgh の子どもたちに紹介するため。"),
             ]),
        dict(label="問2（解答番号 19）",
             qtext="Which is true about the library event?（図書館のイベントについて正しいものはどれか）",
             choices=[("①","Books will be on show in the children's area."),
                      ("②","Reading sessions will be held daily."),
                      ("③","The book fair will run for one month."),
                      ("④","Volunteers will be given a thank-you gift.")],
             answer="④",
             explain="「ボランティアをすれば本のクーポン（book coupon）がもらえる」とあり、これがお礼の品＝④が正解。①は本は“玄関ホール（entrance hall）”で展示（子ども用エリアではない）。②朗読会は“最終日”のみ（毎日ではない）。③フェアは2月1〜8日＝1週間で、1か月ではない。",
             evidence=[
                 ("If you volunteer, you will receive a book coupon.","ボランティアをすれば、本のクーポンがもらえる。（＝お礼の品）"),
                 ("from 1 to 8 February 2026 … exhibit books all week in the entrance hall … reading sessions … on the final day","2月1〜8日／玄関ホールで1週間展示／朗読会は最終日（→①②③はいずれも誤り）。"),
             ]),
        dict(label="問3（解答番号 20）",
             qtext="Which combination best describes the four books you recommended?（推薦した4冊を最もよく表す組合せはどれか）  A: All include drawings by the writers. ／ B: All meet the budget criterion. ／ C: All have happy endings. ／ D: All mention animals.",
             choices=[("①","A and B"),("②","A and C"),("③","A and D"),("④","B and C"),("⑤","B and D"),("⑥","C and D")],
             answer="⑤",
             explain="B と D が正しいので⑤。B（予算条件＝£20以下）：4冊は£16・£8・£10・£19ですべて£20以下→○。D（すべて動物が登場）：①悪魔とペットの犬、②ねこ、③パンダ、④負傷したヤギ→すべて動物が登場→○。A（挿絵は作者本人）：③Panda Adventures は Pictures by Kanako Maru で作者（Maruo Maru）と別人なので“すべて”ではない→×。C（すべてハッピーエンド）：③はパンダが動物園に連れ戻され「最後の言葉に涙した」＝悲しい結末なので“すべて”ではない→×。",
             evidence=[
                 ("No book should cost more than £20. … £16 / £8 / £10 / £19","本は£20を超えないこと。4冊は£16・£8・£10・£19＝全て条件内（B○）。"),
                 ("③ Pictures by Kanako Maru（作者は Maruo Maru）","③の挿絵は作者と別人→A×。"),
                 ("③ the poor panda is caught and taken back to the zoo. The boy's final words … had me in tears.","③はパンダが連れ戻され、涙する結末→C×。一方①犬・②ねこ・③パンダ・④ヤギで全冊に動物→D○。"),
             ]),
        dict(label="問4（解答番号 21）",
             qtext="Which of your book recommendations will not be included in the fair?（推薦した本のうち、フェアに含まれないのはどれか）",
             choices=[("①","Green Demon Blue Demon"),("②","Paint! Paint! Paint!"),
                      ("③","Panda Adventures"),("④","The Cloud Prince")],
             answer="③",
             explain="メールに「あなたの応募のうち1冊は“対象年齢（target age range）”に合わなかった」とある。フェアの対象は preschool children（未就学児）。各本の対象年齢は ①3〜5歳、②小学校入学前、④未就学児で適合するが、③Panda Adventures は“10歳以上向け（kids aged over ten）”で未就学児に合わない。よって除外＝③。",
             evidence=[
                 ("recommendations for preschool children","対象は未就学児向けの絵本。"),
                 ("③ The story is long, so it is suitable for kids aged over ten.","③は長く、10歳以上向け（→対象年齢に合わず除外）。"),
                 ("Although one of your entries did not fit the target age range …","あなたの応募の1冊は対象年齢に合わなかった。"),
             ]),
        dict(label="問5（解答番号 22・23）※順不同",
             qtext="In the email, what are the two things that the library would like you to do?（メールで図書館があなたにしてほしい2つのことは何か）",
             choices=[("①","Ask your friends to volunteer"),("②","Buy a new picture book"),
                      ("③","Participate in ‘Story Time’"),("④","Resubmit your online form"),
                      ("⑤","Suggest another book title"),("⑥","Translate one of the books")],
             answer="③ と ⑤",
             explain="メールの依頼は2つ。(a)「追加の推薦本があればメールしてください」→ 別の本を提案する＝⑤。(b)「最終日のボランティアがまだ不足している。再考してもらえませんか」→ あなたはフォームで朗読ボランティア（‘Story Time’ reader）を“No”にしていたので、その再考を促している＝③ Participate in ‘Story Time’。よって③と⑤。④（再提出）や⑥（翻訳）は依頼されていない。",
             evidence=[
                 ("If you have an additional book recommendation, please email it to us.","追加の推薦本があればメールしてください。（→⑤）"),
                 ("As we are still short of volunteers for the last day, would you kindly reconsider?","最終日のボランティアがまだ不足しています。再考いただけませんか。（フォームで No にした朗読ボランティアの再考→③）"),
             ]),
    ],
))

# -------------------- 第6問 --------------------
SECTIONS.append(dict(
    num="第6問", points=12,
    theme="物語文「The Onigiri Shop（おにぎり屋）」と Story Outline（あらすじ整理）",
    situation="英語の授業で、発表のために次の物語のあらすじ（アウトライン）を作るよう先生に言われた。物語は◆◆の区切りで「現在（大人のミツキ）」と「回想（中学生時代）」が切り替わる。",
    passages=[dict(kind="box", title="The Onigiri Shop", items=[
        "〔現在〕Mitsuki walked to the park near her office and sat on the bench. She was feeling nervous about her presentation in the afternoon. She quickly unwrapped her onigiri, or rice ball, and bit into the salmon filling. She was immediately taken back to a comforting time in her life so many years ago.",
        "〔回想〕An old man sold traditional onigiri in a small, one-window shop in an old shopping arcade. Mitsuki, a junior high school kendo club member, often bought onigiri on her way home after practice. This shop was popular because it sold the best homemade tuna-filled onigiri in town. Mitsuki always bought one. The old man never said much and neither did Mitsuki.",
        "One day, Mitsuki noticed an old black-and-white photo of a young man in kendo gear on the wall of the shop. She thought the old man might be a kendo fan. She wanted to talk to him about kendo but could not work up the courage to do so.",
        "On a Friday afternoon, after a long practice, she had to carry home not only her kendo shinai, or bamboo sword, but also the rest of the equipment needed for the tournament the next day. She was starving, so she went to buy her regular onigiri. When she got home, she realized that she did not have her shinai. “Oh no! Where did I leave it? At the onigiri shop?” In a panic, Mitsuki ran out of her house and retraced her steps back to the onigiri shop. It was closed! She banged on the window shutter. “Excuse me, could you please open up?”",
        "The old man opened the side door of the shop. He held out her shinai. “I found it outside the shop,” he said. “Thank you so much. I need it for the tournament tomorrow,” Mitsuki said. The old man murmured under his breath, “Never lose sight of yours. I never lost sight of mine.” He shut the door before Mitsuki could utter another word.",
        "The next morning, Mitsuki stopped by the onigiri shop. “I'll need to keep up my energy today,” she thought. She bought her regular onigiri and said, “Thank you for keeping my shinai yesterday.” The old man just nodded.",
        "At the tournament, Mitsuki ate during her mid-morning break. She opened the bag, and to her surprise, she discovered two onigiri inside. One was her regular tuna-filled onigiri and the other was salmon-filled. She eagerly ate both. Later in the afternoon, she won her match. Although her team did not win, it was the best she had ever done.",
        "Mitsuki rushed toward home. She wanted to tell the onigiri man about her performance at the tournament. The shop window was shuttered. She banged on it. “Hello, hello? Is anyone there?” A young man looked out of the side door. “Can I help you?” he asked. This man looked vaguely familiar. Then Mitsuki asked, “Where is the onigiri man?” The young man said, “Oh, my father didn't feel well this afternoon and is in the hospital, just for a few days.” Feeling sad, Mitsuki walked slowly home.",
        "Mitsuki sat in the kitchen and thought about the old man. Then it hit her. “He's the man in the photo! That's why the young man looked familiar!” Mitsuki began writing a note.",
        "〔メモ〕Thank you for the bonus onigiri. It helped me win my match! I know you love kendo. I'll get your winning onigiri before my next tournament with my teammates. We'll smash the tournament, so please get well soon! — Mitsuki",
        "“Could you please give this to your father?” she asked the young man the next day.",
        "〔回想おわり〕Mitsuki continued practicing kendo throughout junior high school and kept buying her favorite tuna onigiri after practice. On tournament days, the old man gave her a salmon one as well. And as always, the old man just nodded. “Good luck,” he murmured.",
        "〔現在〕Salmon onigiri always gave Mitsuki renewed energy. She walked back to her office with a spring in her step, ready to smash her presentation.",
    ]),
    dict(kind="box", title="Story Outline（解答する枠組み）", items=[
        "Setting and characters — Mitsuki: ・was active in her junior high school kendo club ・bought onigiri on her way home from school ・was curious, but shy about talking to the old man",
        "Old man: ・owned an onigiri shop in a shopping arcade ・〔解答番号24〕 ・〔解答番号25〕",
        "Important incidents（重要な出来事・上から順に）: 〔26〕→〔27〕→〔28〕→〔29〕",
        "What does the story tell us?（この物語が伝えること）: ・The old man〔30〕. ・Mitsuki's〔31〕.",
    ])],
    questions=[
        dict(label="問1（解答番号 24・25）※順不同",
             qtext="Choose the best options for 24 and 25.（「老人」を説明するものを2つ選べ）",
             choices=[("①","appeared unfriendly and sometimes seemed rude"),
                      ("②","gifted two tuna-filled onigiri to Mitsuki on tournament day"),
                      ("③","kept the shop open although he had few customers"),
                      ("④","practiced kendo when he was in his youth"),
                      ("⑤","ran his business with his son in a disorganized way")],
             answer="① と ④",
             explain="①「無愛想に見え、時にぶっきらぼうに見えた」：老人は『never said much（多くを語らない）』、ミツキが話し終える前に戸を閉めるなど、そっけない印象＝○。④「若い頃に剣道をしていた」：店の壁に『剣道着姿の若い男のモノクロ写真』があり、後に『写真の人物＝老人だ』と判明する＝○。②は“ツナを2個”が誤り（実際はツナ＋サーモンの2個で、サーモンがおまけ）。③は店は“人気店（best onigiri in town）”で客が少ないわけではない。⑤は息子と乱雑に経営した事実はない（息子は父の入院時に登場するのみ）。",
             evidence=[
                 ("The old man never said much … He shut the door before Mitsuki could utter another word.","老人は多くを語らず…ミツキが言い終える前に戸を閉めた。（①）"),
                 ("an old black-and-white photo of a young man in kendo gear … “He's the man in the photo!”","剣道着姿の若い男の古いモノクロ写真…「写真の人だ！」（④＝若い頃に剣道）"),
                 ("She discovered two onigiri … One was … tuna-filled … the other was salmon-filled.","2個のおにぎり…1つはツナ、もう1つはサーモン（→②“ツナ2個”は誤り）。"),
             ]),
        dict(label="問2（解答番号 26〜29）",
             qtext="Choose four out of the five options and put them in the order they happened in Mitsuki's life.（ミツキの人生で起きた順に4つ並べよ）  26→27→28→29",
             choices=[("①","Mitsuki did well at her match on the tournament day."),
                      ("②","Mitsuki wrote a message to the son of the old man."),
                      ("③","The old man found Mitsuki's shinai left outside his shop."),
                      ("④","The old man secretly gave Mitsuki an extra onigiri."),
                      ("⑤","The salmon-filled onigiri reminded Mitsuki of her youth.")],
             answer="③ → ④ → ① → ⑤",
             explain="設問は『ミツキの人生で起きた順』。物語は“現在（大人）→回想（中学時代）→現在”という入れ子構造で、選択肢には現在の場面も含まれる点に注意。③老人が店の外で竹刀（shinai）を見つけて返す（中学時代）→④翌日の大会で、袋の中におまけのサーモンおにぎりがこっそり入っていた→①その日の試合で自己最高の出来で勝った→⑤（大人になった現在）サーモンのおにぎりが若い頃の温かい記憶を呼び起こした。⑤は物語の冒頭・結末を結ぶ“現在”の出来事で、人生の時系列では一番あとにあたるため最後の枠（29）に入る。よって③→④→①→⑤。選ばない1つは②（老人の息子へメモを書いた）で、これは中学時代の補足的な出来事として除外する。〔ここは現在の場面を時系列の最後に置けるかが問われた難問〕",
             evidence=[
                 ("He held out her shinai. “I found it outside the shop,”","彼は竹刀を差し出した。「店の外で見つけた」（③）"),
                 ("she discovered two onigiri inside … the other was salmon-filled.","袋の中に2個のおにぎり…もう1つはサーモン（④おまけ）"),
                 ("Later in the afternoon, she won her match … the best she had ever done.","午後に試合に勝った…自己最高の出来だった（①）"),
                 ("〔冒頭・現在〕she bit into the salmon filling. She was immediately taken back to a comforting time in her life so many years ago.","サーモンの具にかじりつくと、すぐに何年も前の心温まる時へと引き戻された（⑤＝大人になった現在。人生の時系列では最後）"),
             ]),
        dict(label="問3（解答番号 30）",
             qtext="Choose the best option for 30: “The old man ___.”（老人について この物語が伝えること）",
             choices=[("①","began a weekly routine of making onigiri for the team"),
                      ("②","built a friendship with Mitsuki by exchanging notes"),
                      ("③","chatted with Mitsuki whenever she visited his shop"),
                      ("④","showed kindness with not words but with his actions")],
             answer="④",
             explain="老人はほとんど言葉を発しないが、竹刀を見つけて返し、こっそりサーモンのおにぎりを足し、「がんばれ」とつぶやくなど、行動で優しさを示した。よって「言葉ではなく行動で優しさを示した」＝④。①週課やチーム分は本文になし、②メモは一方通行で“やり取り”ではない、③は『never said much』に反する。",
             evidence=[
                 ("The old man never said much … the old man gave her a salmon one as well … “Good luck,” he murmured.","老人はほとんど語らず…サーモンも添えてくれた…「がんばれ」とつぶやいた。（言葉少なに行動で示す＝④）"),
             ]),
        dict(label="問4（解答番号 31）",
             qtext="Choose the best option for 31: “Mitsuki's ___.”（ミツキについて この物語が伝えること）",
             choices=[("①","kendo career ended because of the advice of the old man"),
                      ("②","memories about onigiri influenced her later in life"),
                      ("③","performance at the kendo tournament led to a team victory"),
                      ("④","presentation went well because she ate a tuna-filled onigiri")],
             answer="②",
             explain="冒頭と結末で、大人になったミツキはサーモンのおにぎりを食べて中学時代の温かい記憶によみがえり、“新たな活力”を得て発表に臨む。つまり「おにぎりにまつわる記憶が後の人生に影響した」＝②。①助言で剣道をやめた事実はない（中学を通じて続けた）。③『her team did not win』なのでチーム優勝は誤り。④大人が食べたのはサーモンのおにぎりであり“ツナ”ではない。",
             evidence=[
                 ("Salmon onigiri always gave Mitsuki renewed energy. She walked back to her office … ready to smash her presentation.","サーモンのおにぎりはいつもミツキに新たな活力を与えた。彼女は…発表に臨む準備が整い、オフィスへ戻った。（②）"),
                 ("Although her team did not win, it was the best she had ever done.","チームは勝てなかったが、自己最高の出来だった（→③は誤り）。"),
             ]),
    ],
))

# -------------------- 第7問 --------------------
SECTIONS.append(dict(
    num="第7問", points=16,
    theme="論説文「Mind-Wandering（心のさまよい）」＋発表スライド＋話し合い",
    situation="理科の授業の発表を、次の論説文を使って準備した。発表はスライドの空所〔32〕〜〔36〕と、最後の話し合い〔37〕を完成させる形。",
    passages=[dict(kind="box", title="Mind-Wandering: Lost in Thought", items=[
        "Rodin's sculpture The Thinker represents a man absorbed in thought. People may wonder if he is thinking about life's deep questions. Likewise, teachers may wonder what students sitting at their desks are thinking about—are they focusing on their schoolwork, or are they just daydreaming?",
        "It is natural for the mind to switch between periods of focus and periods of rest. Even when we are supposed to be concentrating, we may not be paying attention to the task at hand. Scientists have found that we engage in daydreaming, also known as “mind-wandering,” approximately 50% of the time we are awake. While our minds are wandering, we are not thinking about anything special but our brains naturally come up with ideas, images, and emotions. In short, mind-wandering is a shift away from thoughts on the current task to other unrelated thoughts.",
        "Our understanding about mind-wandering has grown over time. Past studies argued that mind-wandering was not merely a waste of time but actually quite harmful. Mind-wandering was found to negatively influence our mood, leading to work-related mistakes, traffic accidents, and even mental conditions such as depression. New research, however, shows that mind-wandering also has positive effects which can enrich our lives in various ways.",
        "One such effect is that mind-wandering helps us generate creative ideas. In fact, some of our best ideas become apparent when our minds are wandering. To access these ideas, however, our brains sometimes require a period of time, just like eggs need time to hatch. This is called the “incubation period.” This interval away from the problem is critical because during that time our brains are unconsciously sorting through pieces of information and associating them with the problem. This enables us to come up with a fresh solution, which appears when we least expect it, for example, when we are on a walk or taking a shower.",
        "What is really going on in the brain when the mind wanders? Previously, the brain was thought to be in a passive state at this time. However, through neuroimaging research conducted in 2001 in the US, more than a dozen regions of the brain were found to be active during mind-wandering. These regions, as a whole, were named the Default Mode Network (DMN). Moreover, according to a study conducted in 2022 by researchers based in Norway and the Netherlands, the DMN was more active when participants were performing a low-effort task compared to a high-effort task.",
        "How can we make use of new discoveries in brain science …? Here are four tips to help expand your mind. First, make time for simple activities such as doing the dishes or taking a warm bath. When involved with these undemanding tasks, our mind is free to wander around. Next, we can just go outside. For example, when we are in a forest, we are able to relax in nature and our mind can more easily spread out in all directions. Another suggestion is to get enough quality sleep each night. This will not only improve our mood, but enable the brain to be more receptive to new ideas. Finally, when we wake up in the morning, we should try to notice any thoughts that occur before we get out of bed. In this half-sleep state, our mind tends to wander and our ideas can flow more freely.",
        "We will not always be able to control all of our thoughts. However, if we are aware of when and how mind-wandering happens, we may be able to take advantage of its seemingly random nature.",
    ]),
    dict(kind="box", title="話し合いの4人のコメント（問5用）", items=[
        "Ami: I'm a book lover. I'll read anything to expand my mind. I often stay up late to finish another chapter. I drink a lot of green tea to help me stay awake.",
        "Barry: I like to keep active and do some sort of exercise. I usually go cycling along the riverbank before school. I also like hiking around the countryside on holidays.",
        "Chihiro: I'm extremely focused on my schoolwork during the week. So busy! On the weekends I need a break, so I visit my local hot springs to forget about everything.",
        "Dean: I want to be a cooking influencer. I post new recipes to my account almost daily. I check my phone to respond to my followers right after waking up in the morning.",
    ])],
    questions=[
        dict(label="問1（解答番号 32）",
             qtext="スライド2「The Occurrence of Mind-Wandering: It happens ___.」に入る最適な選択肢を選べ。",
             choices=[("①","in about half of the time we are daydreaming"),
                      ("②","in the nightmares we experience during sleep"),
                      ("③","when our focus is away from the ongoing activity"),
                      ("④","while we are concentrating on the present task")],
             answer="③",
             explain="本文は mind-wandering を「今取り組んでいる課題から、無関係な別の考えへと“注意がそれること”」と定義する。よって「進行中の活動から注意がそれているとき」＝③。①は本文の『起きている時間の約50%、白昼夢に耽る』を“白昼夢の半分”と取り違えた誤り。②睡眠中の悪夢ではない。④集中している“まさにその時”は逆。",
             evidence=[
                 ("mind-wandering is a shift away from thoughts on the current task to other unrelated thoughts.","mind-wandering とは、現在の課題に関する思考から、無関係な別の思考へと移ることである。（③）"),
             ]),
        dict(label="問2（解答番号 33・34）※順不同",
             qtext="スライド3「Possible Effects of Mind-Wandering: It ___. ／ It ___.」に入る2つを選べ。",
             choices=[("①","affects our mental health"),("②","decreases errors at work"),
                      ("③","enhances our memory"),("④","gives us novel ideas"),
                      ("⑤","improves our driving skill")],
             answer="① と ④",
             explain="本文は mind-wandering の“負の効果”と“正の効果”の両方を述べる。負：気分に悪影響を与え、仕事のミス・交通事故・うつ等の精神状態につながる→「心の健康に影響する」＝①。正：創造的なアイデアを生む助けになる→「斬新なアイデアを与える」＝④。②“仕事のミスを減らす”は逆（ミスを招く）、⑤“運転技能を高める”も逆（交通事故）、③記憶増強は本文に効果として明示なし。",
             evidence=[
                 ("…leading to work-related mistakes, traffic accidents, and even mental conditions such as depression.","仕事のミス・交通事故・うつなどの精神状態につながる。（①心の健康への影響）"),
                 ("mind-wandering helps us generate creative ideas.","mind-wandering は創造的なアイデアを生む助けになる。（④斬新なアイデア）"),
             ]),
        dict(label="問3（解答番号 35）",
             qtext="スライド4「What Happens During the Incubation Period?」に入る最適な選択肢を選べ。",
             choices=[("①","Complicated problems enter our consciousness."),
                      ("②","Our brains organize information in new ways."),
                      ("③","Our moods are altered from negative to positive."),
                      ("④","The mind moves from an active to a passive state.")],
             answer="②",
             explain="「孵化期間（incubation period）」について本文は『その間、脳は無意識のうちに情報の断片を整理し、それらを問題と結びつけている。これが新しい解決策を生む』と説明する。つまり“脳が情報を新しい形で整理する”＝②。①は問題が意識に入る、ではなく“問題から離れる”ので逆、③気分の話ではない、④脳は受動的でなく活動している（DMN）ので逆。",
             evidence=[
                 ("during that time our brains are unconsciously sorting through pieces of information and associating them with the problem.","その間、脳は無意識に情報の断片を整理し、問題と結びつけている。（②）"),
             ]),
        dict(label="問4（解答番号 36）",
             qtext="スライド5「A Finding From Neuroimaging Research」に入る最適な選択肢を選べ。",
             choices=[("①","The brain has multiple areas working while the mind is wandering."),
                      ("②","The brain's DMN is only activated when we perform high-effort tasks."),
                      ("③","The entire brain is inactive when we are working on low-effort tasks."),
                      ("④","The state of the brain remains passive during mind-wandering.")],
             answer="①",
             explain="2001年米国の神経画像研究で「mind-wandering 中に脳の十数か所の領域が活動していることが分かり、それらをまとめて DMN と名づけた」。つまり“心がさまよう間、脳の複数の領域が働いている”＝①。②DMN は“低負荷”課題でより活発（high-effort のみは誤り）、④脳は受動的でなく活動している（previously は passive と思われていたが新研究で否定）、③も誤り。",
             evidence=[
                 ("more than a dozen regions of the brain were found to be active during mind-wandering. These regions … were named the Default Mode Network (DMN).","mind-wandering 中に脳の十数以上の領域が活動していると分かり、それらは DMN と名づけられた。（①複数領域が活動）"),
             ]),
        dict(label="問5（解答番号 37）",
             qtext="話し合いで、本文の4つのコツに照らして mind-wandering の恩恵を最も得やすい2人を選べ。",
             choices=[("①","Ami and Barry"),("②","Ami and Chihiro"),("③","Ami and Dean"),
                      ("④","Barry and Chihiro"),("⑤","Barry and Dean"),("⑥","Chihiro and Dean")],
             answer="④",
             explain="本文の4つのコツは【①皿洗いや入浴など単純な作業の時間を作る／②外（自然）に出る／③毎晩しっかり睡眠をとる／④起床時、起き上がる前に浮かぶ考えに気づく】。Barry は『登校前にサイクリング、休日に田舎をハイキング』＝自然の中に出る（コツ②）に合致。Chihiro は『週末は温泉に行ってすべてを忘れる』＝温かい入浴のような単純で心が解放される時間（コツ①）に合致。よって④ Barry and Chihiro。Ami は夜更かし＋緑茶で起き続け（睡眠のコツ③に反する・読書は集中的）、Dean は起床直後にスマホで返信（起床時に考えに気づくコツ④に反する）ため不適。",
             evidence=[
                 ("make time for simple activities such as … taking a warm bath … we can just go outside … in a forest … get enough quality sleep … notice any thoughts … before we get out of bed.","入浴など単純な作業／外（森など自然）に出る／十分な睡眠／起床前に浮かぶ考えに気づく（＝4つのコツ）。"),
                 ("Barry: cycling along the riverbank … hiking around the countryside","Barry：川辺でサイクリング、田舎をハイキング（自然＝コツ②）。"),
                 ("Chihiro: I visit my local hot springs to forget about everything.","Chihiro：温泉に行ってすべてを忘れる（入浴・単純で解放的＝コツ①）。"),
             ]),
    ],
))

# -------------------- 第8問 --------------------
SECTIONS.append(dict(
    num="第8問", points=17,
    theme="スポーツとテクノロジー — 5人の意見＋資料A・B（小論文の準備）",
    situation="「スポーツとテクノロジー」についての小論文を、手順に沿って準備する。[Step1] 5人の意見を読む → [Step2] 立場を決める → [Step3] 資料A・Bを使ってアウトラインを作る。",
    passages=[
        dict(kind="box", title="[Step 1] 5人の意見", items=[
            "Akane (social worker): There is a strong relationship between the number of Olympic medals a country has and its wealth. If the cost of doing a sport is high, then only those with money can participate in it. Sports should be for all of us, as it benefits our physical and mental health. I am concerned that the continuing development of high-tech, expensive equipment may discourage ordinary people from taking up certain sports.",
            "Fiona (physical trainer): “Performance” should be seen as the sum of the athlete's own abilities plus the equipment available to them. All athletes want to use equipment that will maximize their performance. I understand this, but I can also think of some problematic cases. Suppose that two teams with the same ability are in a rowing race. The team with a newer boat model completes the race a fraction of a second faster. This might not be considered fair.",
            "Jack (journalist): Technology makes sports more thrilling for fans. We are fascinated by new achievements, so sports receive a high level of attention when records are broken. Sports fans, say of the Olympics, want to see their favorite skiers and skaters race faster. Our world is rapidly changing, and society expects to see those changes in sports as well. If records are never broken, then sports become dull for fans.",
            "Michael (retired swimmer): From elementary school, I practiced swimming seven days a week all year round. Swimming did not require expensive equipment and I used our community pool, which cost little. Through intense training over a period of years, I was able to win my state championship. To me, the spirit of sport is putting in the work to maximize your physical ability. New equipment giving advantages to one athlete over a harder-working one is an injustice.",
            "Tamara (tennis coach): I am old enough to remember the transition from wooden tennis rackets to so-called “oversized” graphite ones. Players now hit the ball harder; the new rackets also enable us to control the ball better. Is this a problem? No one complains about the new rackets anymore. Sports equipment is continually changing. Innovation in sports technology has improved the quality of games.",
        ]),
        dict(kind="box", title="[Step 3] アウトライン「Technology in Sports」と 資料A・B", items=[
            "Introduction: There are some issues with sports technology, but because of its current and potential contributions, we should accept it.",
            "Body — REASON 1: [the common idea in Step 2] ／ REASON 2:〔解答番号43〕[based on Source A] ／ REASON 3: Advanced technology in sports equipment can contribute to injury prevention. [based on support from Source B:〔解答番号44〕]",
            "Conclusion: Upon considering the aspects above, advancements in sports technology should be accepted.",
            "Source A: Sports technology makes sports better for everyone. On the other hand, it is sometimes argued that technology can threaten the integrity or value of a sport. This threat comes when new technology enables athletes to do their sport too easily or is only accessible to certain athletes, giving them an advantage. Wise regulation can ensure that this does not happen. For example, in 2016, a new running shoe was developed that improved runners' times by up to 4%. People in the running world became concerned that it could damage the sport's integrity. In 2020, World Athletics set concrete specifications for running shoes and regulations on their materials. It also created a rule that any shoe used in a race had to be available on the market for at least four months beforehand. As a result of these measures, no running shoe could be constructed in a way that made running too easy and every runner could benefit from new technology.",
            "Source B: A sporting company released a new type of running shoe that uses advanced technology. They conducted surveys on three groups of runners each consisting of 100 people: recreational runners, student-athletes, and professional athletes. The graph shows the number of people who responded positively to some of the shoe features.",
            "【資料Bのグラフ（肯定的に回答した人数／各群100人）】 shoe comfort（履き心地）: recreational 72 / student-athletes 74 / professional 82 ／ design of the shoes（デザイン）: recreational 42 / student-athletes 57 / professional 55 ／ reduced burden on legs（脚の負担軽減）: recreational 51 / student-athletes 57 / professional 69",
        ]),
    ],
    questions=[
        dict(label="問1（解答番号 38）",
             qtext="Which of the following best summarizes Akane's opinion?（Akane の意見を最もよく要約するものはどれか）",
             choices=[("①","Athletic ability cannot be developed using advanced technology."),
                      ("②","Olympic games will be less exciting with the latest equipment."),
                      ("③","Technology can benefit the physical health of elite athletes."),
                      ("④","The cost of sports might be a barrier for people's participation.")],
             answer="④",
             explain="Akane は「高価なハイテク用具の発展が、普通の人々を一部のスポーツから遠ざけるのではと懸念」「費用が高ければ、お金のある人しか参加できない」と述べる。つまり“費用が参加の障壁になりうる”＝④。①能力の話、②五輪が退屈になるはむしろ Jack と逆方向、③恩恵は“エリート選手”ではなく“すべての人”の健康。",
             evidence=[
                 ("If the cost of doing a sport is high, then only those with money can participate in it.","スポーツにかかる費用が高ければ、お金のある人しか参加できない。（④費用が障壁）"),
                 ("expensive equipment may discourage ordinary people from taking up certain sports.","高価な用具が普通の人々を一部のスポーツから遠ざけるかもしれない。"),
             ]),
        dict(label="問2（解答番号 39）",
             qtext="Both Fiona and Michael mention that ___.（Fiona と Michael がともに述べているのは…）",
             choices=[("①","advanced technology can give unfair advantages to some athletes"),
                      ("②","equipment should be considered a part of an athlete's performance"),
                      ("③","the spirit of sport is based on hard work and physical ability"),
                      ("④","water sports should require training without technology")],
             answer="①",
             explain="Fiona は「同実力の2チームでも、新しいボートのチームがわずかに速く、これは公平でないかもしれない」、Michael は「努力した選手より用具で有利になるのは不公正（injustice）」と述べる。両者の共通点は“先進的な用具・技術が一部の選手に不公平な優位を与えうる”＝①。②は Fiona のみ、③は Michael のみ、④は本文になし。",
             evidence=[
                 ("Fiona: The team with a newer boat model completes the race a fraction of a second faster. This might not be considered fair.","新しいボートのチームがわずかに速い。これは公平でないかもしれない。"),
                 ("Michael: New equipment giving advantages to one athlete over a harder-working one is an injustice.","努力した選手より、新しい用具で有利になるのは不公正だ。（①不公平な優位）"),
             ]),
        dict(label="問3（解答番号 40・41 ※順不同／42）",
             qtext="POSITION:「スポーツ用具の技術の進歩を受け入れるべきだ」。この立場を最も支持する2人〔40・41〕と、その2人に共通する考え〔42〕を選べ。",
             choices=[("【40・41】①","Akane"),("②","Fiona"),("③","Jack"),("④","Michael"),("⑤","Tamara"),
                      ("【42】①","advancements in technology promote the evolution of sports"),
                      ("②","athletes play a role in the enhancement of sports equipment"),
                      ("③","technology contributes to the breaking of sporting records"),
                      ("④","technology helps improve the experience of playing sports")],
             answer="40・41 = ③ Jack と ⑤ Tamara ／ 42 = ①",
             explain="「技術の進歩を受け入れるべき」という立場を支持するのは、Jack（技術はスポーツをより面白くし、記録更新で注目が集まる。社会は変化を期待する）と Tamara（用具は絶えず変化し、技術革新が試合の質を高めた）＝③・⑤。Akane・Fiona・Michael はいずれも懸念・反対寄りで不適。共通の考え〔42〕は、両者とも“スポーツが技術とともに変化・発展していく”ことを述べている＝① advancements in technology promote the evolution of sports。③は記録更新（Jack のみ）、④は“プレーする体験”（Tamara 寄りで Jack は観戦者の話）で共通項にならない。",
             evidence=[
                 ("Jack: Our world is rapidly changing, and society expects to see those changes in sports as well.","世界は急速に変化し、社会はスポーツにもその変化を期待する。（進歩＝発展）"),
                 ("Tamara: Sports equipment is continually changing. Innovation in sports technology has improved the quality of games.","スポーツ用具は絶えず変化している。技術革新が試合の質を高めた。（①スポーツの発展を促す）"),
             ]),
        dict(label="問4（解答番号 43）",
             qtext="Based on Source A, which is the most appropriate for REASON 2 in the essay outline?（資料Aに基づき、REASON 2 に最適なものを選べ）",
             choices=[("①","New technology will make a sport more accessible and thus motivate more people to start it."),
                      ("②","New technology with regulation improves the sporting experience while maintaining a sport's value."),
                      ("③","The introduction of new technology can enhance the integrity of a sport by making it easier."),
                      ("④","The regulation of new technology may lower the integrity of a sport by discouraging innovation.")],
             answer="②",
             explain="資料Aの要点は「技術はスポーツを良くするが、競技の価値（integrity）を脅かす恐れもある。しかし“賢明な規制（wise regulation）”でそれを防げる」。実例として、2016年の新シューズ騒動→2020年に World Athletics が規格・規制を設け、結果的に“誰もが技術の恩恵を受けられた”。よって REASON 2 は「規制を伴う新技術が、スポーツの価値を保ちながら体験を向上させる」＝②。③は『easier（簡単に）』が資料Aで否定された“脅威”そのもの、④は規制を否定的に描き逆、①は accessibility（Akane 的論点）で資料Aの主旨と異なる。",
             evidence=[
                 ("Wise regulation can ensure that this does not happen. … As a result … every runner could benefit from new technology.","賢明な規制でそれ（脅威）を防げる。…結果として、すべてのランナーが新技術の恩恵を受けられた。（②規制＋価値維持）"),
             ]),
        dict(label="問5（解答番号 44）",
             qtext="Based on Source B, which best supports REASON 3 (injury prevention)?（資料Bに基づき、REASON 3「けが防止」を最もよく支持するものを選べ）",
             choices=[("①","Advanced technology in shoes may encourage more students to run regularly. … student-athletes rated the running shoes higher than the other groups in two of three features."),
                      ("②","In addition to preventing injury, the running shoes are pleasant to wear. … more than three quarters of the respondents in each group felt the shoes were comfortable."),
                      ("③","More than half of the runners in each group felt the burden on their legs was reduced. This implies that people may maintain better physical condition thanks to the technology."),
                      ("④","The effectiveness of the new shoe was most evident for recreational runners with more than half feeling less burden on their legs. …")],
             answer="③",
             explain="REASON 3 は「先進技術はけが防止に寄与する」。これに直結するのはグラフの“reduced burden on legs（脚の負担軽減）”で、各群の数値は recreational 51・student-athletes 57・professional 69 で、いずれも50（半数）超。よって「各群で半数以上が脚の負担が軽くなったと感じた→技術のおかげで体の状態を保てる」＝③が、データと整合しけが防止を支持する。①は“走る学生を増やす”でけが防止と無関係、②は『各群で4分の3超が快適』だが履き心地は72・74・82で recreational(72)・student(74) は75%未満＝事実誤り、④は『recreational で最も顕著』だが脚負担軽減は recreational(51) が最小で誤り。",
             evidence=[
                 ("reduced burden on legs: recreational 51 / student-athletes 57 / professional 69","脚の負担軽減：51／57／69（各群とも半数超）→③の『各群で半数以上』が成立。"),
                 ("shoe comfort: recreational 72 / student-athletes 74 / professional 82","履き心地：72／74／82（recreational・student は75%未満）→②『各群で3/4超』は誤り。"),
             ]),
    ],
))
