# -*- coding: utf-8 -*-
"""英検準1級 単語テスト（4択・全10回×20語=200語）の単一ソース。

1エントリ = (word, pos, gloss, (distractor1, distractor2, distractor3),
             usage_en, usage_ja, note)
  word      : 見出し語（英語）。熟語・句動詞も同じ枠に入れる
  pos       : 動 / 名 / 形 / 副 / 熟
  gloss     : 正解の語義（日本語）
  distractors: 誤答の語義3つ。★「その語の別の正しい語義」を絶対に入れない（2正解になる）
  usage_en / usage_ja : 解答編に載せる用例（コロケーション）
  note      : 派生語・混同注意・反意語などの一言メモ

各回16語（単語）＋4語（熟語・句動詞）。正解位置は build 時に word の md5 順で
0〜3へ均等配分するので、ここでは正解を先頭に書いてよい（順序に意味は無い）。
第1〜2回のコア語は scripts/eiken_junichi/data/part1_vocab.json（3段検証済み）と共有。
"""

TESTS = [
    # ============================== 第1回 ==============================
    {"no": 1, "title": "動詞・名詞の中核", "items": [
        ("alleviate", "動", "〜を和らげる、軽減する",
         ("〜を長引かせる", "〜を挑発する", "〜を強める"),
         "alleviate poverty", "貧困を軽減する", "名 alleviation／≒ ease, relieve, mitigate"),
        ("deteriorate", "動", "悪化する、劣化する",
         ("回復する", "加速する", "分散する"),
         "His health deteriorated.", "彼の健康が悪化した", "自動詞。名 deterioration"),
        ("mitigate", "動", "〜を緩和する、軽減する",
         ("〜を誇張する", "〜を延期する", "〜を模倣する"),
         "mitigate the damage", "被害を緩和する", "mitigating circumstances＝情状酌量すべき事情"),
        ("advocate", "動", "〜を主張する、擁護する",
         ("〜をためらう", "〜を撤回する", "〜を軽視する"),
         "advocate reform", "改革を主張する", "名詞では「支持者・提唱者」"),
        ("undermine", "動", "〜を徐々に損なう、弱体化させる",
         ("〜を強固にする", "〜を掘り起こす", "〜を見落とす"),
         "undermine trust", "信頼を損なう", "mine＝掘る。下から掘り崩すイメージ"),
        ("comply", "動", "（規則などに）従う、順守する",
         ("（サービスに）苦情を言う", "補償する", "完了する"),
         "comply with the rules", "規則に従う", "comply with が定型。名 compliance"),
        ("exacerbate", "動", "〜を悪化させる、深刻化させる",
         ("〜を正当化する", "〜を免除する", "〜を発掘する"),
         "exacerbate tensions", "緊張を悪化させる", "≒ aggravate ⇔ alleviate"),
        ("deter", "動", "〜を思いとどまらせる、抑止する",
         ("〜を決定する", "〜をそそのかす", "〜を先延ばしにする"),
         "deter crime", "犯罪を抑止する", "deter A from -ing（Aに〜するのを思いとどまらせる）"),
        ("allocate", "動", "〜を割り当てる、配分する",
         ("〜を没収する", "〜を隠す", "〜を複製する"),
         "allocate funds", "資金を配分する", "allocate A to B。名 allocation"),
        ("scrutiny", "名", "精査、綿密な調査",
         ("気まぐれ", "概略", "中傷"),
         "under close scrutiny", "厳しい精査を受けて", "動 scrutinize"),
        ("discrepancy", "名", "食い違い、不一致",
         ("完全な一致", "遅延", "偏見"),
         "a discrepancy between the two reports", "2つの報告書の食い違い", "≒ inconsistency"),
        ("incentive", "名", "動機づけ、誘因、報奨",
         ("障害", "罰則", "偶然の一致"),
         "an incentive to study harder", "もっと勉強しようという動機づけ", "incentive to do の形で使う"),
        ("backlash", "名", "（激しい）反発、反感",
         ("（大事件の）前触れ", "政治的な妥協", "全面的な賛同"),
         "a public backlash", "世論の激しい反発", "backlash against 〜への反発"),
        ("prerequisite", "名", "前提条件、必須要件",
         ("副産物", "例外規定", "見積もり"),
         "a prerequisite for success", "成功の前提条件", "pre-（前）+ requisite（必要な）"),
        ("plight", "名", "苦境、窮状",
         ("名声", "特権", "節目"),
         "the plight of refugees", "難民の窮状", "悪い状況にのみ使う"),
        ("surge", "名", "急増、急激な高まり",
         ("停滞", "余剰", "深刻な不足"),
         "a surge in demand", "需要の急増", "動詞で「急激に増える」"),
        ("iron out", "熟", "（意見の相違・問題を）解決する、片づける",
         ("（収まった話を）蒸し返す", "〜を黙って見過ごす", "〜を印刷して配る"),
         "iron out the differences", "意見の相違を解消する", "アイロンでしわを伸ばすイメージ"),
        ("weed out", "熟", "〜をふるい落とす、取り除く",
         ("〜を新たに採用する", "〜を植え付ける", "〜を数え上げる"),
         "weed out weak candidates", "不適格な候補者をふるい落とす", "weed＝雑草を抜く"),
        ("rule out", "熟", "（可能性を）除外する、排除する",
         ("（新しい手順を）方針として定める", "〜に判定を下す", "〜を支配する"),
         "rule out the possibility", "その可能性を排除する", "⇔ rule in（候補に残す）"),
        ("come down with", "熟", "（病気に）かかる",
         ("〜を持って降りてくる", "（けんかのあと）仲直りする", "〜に潔く降参する"),
         "come down with the flu", "インフルエンザにかかる", "比較的軽い病気に使う"),
    ]},
    # ============================== 第2回 ==============================
    {"no": 2, "title": "形容詞・副詞の中核", "items": [
        ("plausible", "形", "もっともらしい、ありそうな",
         ("賞賛に値する", "疑いようのない", "実行可能な"),
         "a plausible explanation", "もっともらしい説明", "⇔ implausible。「本当らしいが確証はない」含み"),
        ("meticulous", "形", "細心の、極めて綿密な",
         ("大ざっぱな", "疑い深い", "気軽な"),
         "meticulous attention to detail", "細部への細心の注意", "≒ scrupulous, thorough"),
        ("susceptible", "形", "（病気などに）かかりやすい、影響を受けやすい",
         ("（証拠が薄く）疑わしい", "持続可能な", "抜け目のない"),
         "susceptible to infection", "感染しやすい", "susceptible to が定型"),
        ("inevitable", "形", "避けられない、必然の",
         ("予測できない", "取るに足りない", "評価できない"),
         "an inevitable consequence", "必然の結果", "副 inevitably"),
        ("lucrative", "形", "もうかる、利益の大きい",
         ("幸運な", "ぜいたくな", "なめらかな"),
         "a lucrative business", "もうかる商売", "≒ profitable"),
        ("prevalent", "形", "広く行き渡った、はやっている",
         ("ごくまれな", "一時的な", "予防のための"),
         "a prevalent belief", "広く浸透している考え", "名 prevalence"),
        ("redundant", "形", "余分な、（人員が）余剰の",
         ("不可欠な", "潤沢な", "際立った"),
         "be made redundant", "（英）人員整理で解雇される", "IT では「冗長な＝予備の」"),
        ("tentative", "形", "暫定的な、仮の",
         ("決定的な", "強制的な", "長期的な"),
         "a tentative agreement", "暫定的な合意", "≒ provisional"),
        ("resilient", "形", "回復力のある、立ち直りが早い",
         ("反抗的な", "従順な", "もろい"),
         "a resilient economy", "立ち直りの早い経済", "名 resilience"),
        ("ambiguous", "形", "あいまいな、複数の意味に取れる",
         ("野心的な", "きわめて明快な", "大規模な"),
         "an ambiguous answer", "あいまいな返答", "名 ambiguity"),
        ("compelling", "形", "説得力のある、非常に興味を引く",
         ("型どおりの", "見込みの薄い", "複雑で分かりにくい"),
         "compelling evidence", "説得力のある証拠", "動 compel（強制する）から意味が離れている点に注意"),
        ("inadvertently", "副", "うっかり、不注意で",
         ("意図的に", "執拗に", "ごくまれに"),
         "inadvertently delete a file", "うっかりファイルを削除する", "⇔ deliberately"),
        ("unanimously", "副", "満場一致で",
         ("匿名のままで", "圧倒的多数で", "一人ずつ個別に"),
         "vote unanimously", "満場一致で議決する", "形 unanimous。可決とは限らない（否決も満場一致でありうる）"),
        ("sparingly", "副", "控えめに、少量だけ",
         ("惜しみなく", "予備として", "不意に"),
         "use salt sparingly", "塩を控えめに使う", "spare＝節約する"),
        ("presumably", "副", "おそらく、推定するに",
         ("明らかに", "意外にも", "一見したところ"),
         "Presumably he knew.", "おそらく彼は知っていた", "動 presume"),
        ("profoundly", "副", "深く、甚大に",
         ("浅く", "たまに", "職業として"),
         "profoundly affect society", "社会に深い影響を与える", "形 profound"),
        ("get away with", "熟", "（悪事の）罰をまぬがれる、うまくやり過ごす",
         ("（同じ作業に）飽きる", "〜を手放す", "〜と折り合いをつける"),
         "get away with cheating", "不正をしても罰を免れる", "get away from（〜から逃れる）と区別"),
        ("cut back on", "熟", "（量・支出を）減らす、切り詰める",
         ("（計画・事業を）後押しする", "〜に切り替える", "〜を蒸し返す"),
         "cut back on spending", "支出を切り詰める", "≒ reduce"),
        ("at odds with", "熟", "〜と食い違って、対立して",
         ("〜と歩調を合わせて", "〜の見込みで", "〜に賭けて"),
         "at odds with the facts", "事実と食い違って", "odds＝相違・不一致"),
        ("on the verge of", "熟", "今にも〜しそうで、〜の瀬戸際で",
         ("〜の頂点に立って", "〜の代わりに", "〜を口実にして"),
         "on the verge of collapse", "崩壊寸前で", "verge＝縁・境目"),
    ]},
    # ============================== 第3回 ==============================
    {"no": 3, "title": "施策・社会を語る語", "items": [
        ("implement", "動", "〜を実施する、実行に移す",
         ("〜をほのめかす", "〜を輸入する", "〜を改良する"),
         "implement a policy", "政策を実施する", "名詞では「道具」。名 implementation"),
        ("facilitate", "動", "〜を促進する、容易にする",
         ("〜を複雑にする", "〜を施設に収容する", "〜を偽造する"),
         "facilitate communication", "意思疎通を円滑にする", "名 facilitator（進行役）"),
        ("foster", "動", "〜を育成する、助長する",
         ("〜を見捨てる", "〜を独占する", "〜を急がせる"),
         "foster innovation", "技術革新を促す", "foster child＝里子"),
        ("hamper", "動", "〜を妨げる、阻害する",
         ("〜を包み込む", "〜を誇張する", "〜を加速させる"),
         "hamper economic growth", "経済成長を妨げる", "≒ hinder, impede"),
        ("entail", "動", "〜を必然的に伴う、必要とする",
         ("〜を詳述する", "〜を尾行する", "〜を要約する"),
         "entail serious risks", "重大なリスクを伴う", "≒ involve"),
        ("impair", "動", "〜を損なう、弱める",
         ("〜を修復する", "〜を試験する", "〜を高く評価する"),
         "impair judgment", "判断力を損なう", "visually impaired＝視覚に障害のある"),
        ("incur", "動", "（損失・非難を）招く、負う",
         ("（危険・出費を）回避する", "〜を治療する", "〜を励ます"),
         "incur huge debts", "多額の借金を負う", "incur costs / criticism"),
        ("inhibit", "動", "（成長・反応を）抑える、妨げる",
         ("〜に居住する", "（水分・栄養を）吸収する", "〜を相続する"),
         "inhibit bacterial growth", "細菌の増殖を抑える", "★ inhabit（住む）と混同注意"),
        ("deploy", "動", "〜を配備する、展開する",
         ("〜を破壊する", "〜を雇用する", "〜を展示販売する"),
         "deploy troops", "部隊を配備する", "IT でも「システムを本番投入する」"),
        ("curb", "動", "〜を抑制する、制御する",
         ("〜を測定する", "〜を湾曲させる", "〜を許可する"),
         "curb inflation", "インフレを抑える", "名詞では「（歩道の）縁石」"),
        ("constraint", "名", "制約、束縛",
         ("建設工事", "一貫性", "貢献"),
         "budget constraints", "予算上の制約", "動 constrain"),
        ("disparity", "名", "（不公平な）格差、相違",
         ("（力や量の）完全な均衡", "出発", "絶望"),
         "income disparity", "所得格差", "⇔ parity（同等）"),
        ("consensus", "名", "総意、意見の一致",
         ("国勢調査", "検閲", "強い反論"),
         "reach a consensus", "合意に達する", "★ census（国勢調査）と混同注意"),
        ("hierarchy", "名", "階層、序列",
         ("遺産", "世襲財産", "隠遁生活"),
         "a rigid hierarchy", "厳格な階層構造", "形 hierarchical"),
        ("deficit", "名", "赤字、不足",
         ("黒字", "欠陥品", "定義"),
         "a trade deficit", "貿易赤字", "財政赤字は a budget deficit。⇔ 黒字"),
        ("initiative", "名", "新たな取り組み、主導権",
         ("頭文字", "最終段階", "直感"),
         "take the initiative", "主導権を握る", "a green initiative＝環境施策"),
        ("contend with", "熟", "（困難・問題に）対処する、立ち向かう",
         ("〜に賛成する", "（危険・警告を）軽視する", "〜に委ねる"),
         "contend with hardship", "苦難に立ち向かう", "contend that ...＝〜だと主張する"),
        ("in the wake of", "熟", "〜の直後に、〜の余波を受けて",
         ("〜の前に", "〜の代わりに", "〜のおかげで"),
         "in the wake of the disaster", "その災害の直後に", "wake＝船の航跡"),
        ("stem from", "熟", "〜に起因する、〜から生じる",
         ("〜を食い止める", "〜へ発展する", "〜を根元から断つ"),
         "stem from poverty", "貧困に起因する", "stem＋目的語なら「食い止める」。from を伴えば「起因する」"),
        ("take a toll on", "熟", "〜に打撃を与える、〜を損なう",
         ("〜に通行料を課す", "〜を数え上げる", "〜を大目に見る"),
         "take a toll on health", "健康を害する", "toll＝犠牲・代償"),
    ]},
    # ============================== 第4回 ==============================
    {"no": 4, "title": "議論・変化を語る語", "items": [
        ("eradicate", "動", "〜を根絶する",
         ("〜を放射する", "〜を修正する", "〜を輸出する"),
         "eradicate poverty", "貧困を根絶する", "root（根）ごと抜くイメージ"),
        ("suppress", "動", "〜を抑圧する、抑え込む",
         ("〜を表明する", "〜を圧縮して保存する", "〜を解き放つ"),
         "suppress emotions", "感情を抑える", "名 suppression"),
        ("refute", "動", "〜に反論する、〜の誤りを証明する",
         ("〜を払い戻す", "〜を拒んで受け取らない", "〜を強く要求する"),
         "refute an argument", "主張を論破する", "★ refund（払い戻す）と混同注意"),
        ("endorse", "動", "〜を支持する、推奨する",
         ("〜を耐え忍ぶ", "〜を強制する", "〜を包囲する"),
         "endorse a candidate", "候補者を支持する", "有名人の商品推薦にも使う"),
        ("streamline", "動", "〜を効率化する、合理化する",
         ("〜を放流する", "〜を細分化する", "〜を一列に並べる"),
         "streamline the process", "手続きを簡素化する", "流線形にする→無駄を省く"),
        ("offset", "動", "〜を相殺する、埋め合わせる",
         ("〜を出発させる", "〜を倍増させる", "〜を延期する"),
         "offset the loss", "損失を相殺する", "carbon offset＝炭素の相殺"),
        ("thrive", "動", "繁栄する、生き生きと育つ",
         ("衰退する", "努力する", "到着する"),
         "thrive in a harsh climate", "厳しい気候でもよく育つ", "★ strive（努力する）と混同注意"),
        ("undertake", "動", "〜を引き受ける、〜に着手する",
         ("〜を過小評価する", "〜を取り消す", "〜の下に置く"),
         "undertake a project", "事業に着手する", "過去形 undertook / 過去分詞 undertaken"),
        ("speculate", "動", "推測する、投機する",
         ("観察する", "専門とする", "明記する"),
         "speculate about the cause", "原因を推測する", "名 speculation"),
        ("deplete", "動", "〜を枯渇させる、激減させる",
         ("〜を完成させる", "〜を補充する", "〜を陳列する"),
         "deplete natural resources", "天然資源を枯渇させる", "⇔ replenish（補充する）"),
        ("aftermath", "名", "（災害などの）余波、直後の時期",
         ("（地震などの）前兆", "後回しにすること", "（式典の）後片づけ"),
         "in the aftermath of the war", "戦争の余波の中で",
         "ふつう悪い出来事（戦争・災害・事故など）の後に使う"),
        ("threshold", "名", "境界となる値、敷居",
         ("頂点", "空白部分", "網の目"),
         "the pain threshold", "痛みを感じ始める限界値", "on the threshold of＝〜の入り口で"),
        ("momentum", "名", "勢い、はずみ",
         ("記念碑", "一瞬", "独占"),
         "gain momentum", "勢いを増す", "★ monument（記念碑）と混同注意"),
        ("setback", "名", "挫折、後退",
         ("背景", "予備の計画", "分割返済"),
         "suffer a serious setback", "深刻な挫折を味わう", "⇔ breakthrough"),
        ("sanction", "名", "制裁／（公式の）認可",
         ("聖域／立ち入り禁止区域", "公衆の衛生管理", "（国家間の）休戦協定"),
         "economic sanctions against the country", "その国への経済制裁", "「制裁」と「認可」の正反対の2義を持つ"),
        ("proponent", "名", "支持者、提唱者",
         ("反対者", "所有者", "構成部品"),
         "a proponent of reform", "改革の提唱者", "⇔ opponent"),
        ("crack down on", "熟", "〜を厳しく取り締まる",
         ("〜に屈服する", "〜を解読する", "〜を粉々に砕く"),
         "crack down on fraud", "詐欺を厳しく取り締まる", "名 crackdown"),
        ("shed light on", "熟", "〜を解明する、明らかにする",
         ("〜を覆い隠す", "〜の重荷を下ろす", "〜を大目に見る"),
         "shed light on the cause", "原因を解明する", "shed＝（光を）放つ"),
        ("live up to", "熟", "（期待・評判に）応える",
         ("〜歳まで生き延びる", "（親や親戚と）同居する", "〜を見上げて憧れる"),
         "live up to expectations", "期待に応える", "直訳の「〜まで生きる」は誤り"),
        ("phase out", "熟", "〜を段階的に廃止する",
         ("〜を段階的に導入する", "〜を局面ごとに分析する", "〜を即座に全面禁止する"),
         "phase out plastic bags", "レジ袋を段階的に廃止する", "⇔ phase in（段階的に導入する）"),
    ]},
    # ============================== 第5回 ==============================
    {"no": 5, "title": "データ・経済を語る語", "items": [
        ("accumulate", "動", "〜を蓄積する、たまる",
         ("〜を計算する", "〜を使い果たす", "〜を適応させる"),
         "accumulate wealth", "富を蓄える", "名 accumulation"),
        ("compensate", "動", "（損失などの）埋め合わせをする、補償する",
         ("（意見を）競い合わせる", "〜を凝縮する", "〜を理解する"),
         "compensate for the loss", "損失を埋め合わせる",
         "compensate for 〜（自動詞）＝〜を埋め合わせる／compensate 人 for 〜（他動詞）＝人に補償する。"
         "★他動詞の目的語は「人」で、損失ではない。名 compensation"),
        ("discern", "動", "〜を識別する、見分ける",
         ("〜を懸念する", "〜を辞退する", "〜を解散させる"),
         "discern a pattern", "規則性を見分ける", "形 discernible（見分けがつく）"),
        ("denounce", "動", "〜を公然と非難する",
         ("〜を正式に発表する", "〜を放棄する", "〜を宣言する"),
         "denounce violence", "暴力を非難する", "★ announce / renounce と混同注意"),
        ("reinforce", "動", "〜を補強する、強化する",
         ("〜を再現する", "〜を強要する", "〜を改革する"),
         "reinforce the argument", "主張を補強する", "名 reinforcement"),
        ("retain", "動", "〜を保持する、維持する",
         ("〜を取り戻す", "〜を訓練する", "〜を制限する"),
         "retain customers", "顧客を維持する", "名 retention（定着率）"),
        ("trigger", "動", "〜を引き起こす、誘発する",
         ("〜を追跡する", "〜を締め付ける", "〜を交換する"),
         "trigger an allergic reaction", "アレルギー反応を引き起こす", "名詞では「引き金」"),
        ("verify", "動", "〜を検証する、正しいと確認する",
         ("〜を多様化する", "〜を変更する", "〜を無効にする"),
         "verify the data", "データを検証する", "名 verification"),
        ("contaminate", "動", "〜を汚染する",
         ("〜を内部に含む", "〜を継続する", "〜を封じ込める"),
         "contaminate the water supply", "水道水を汚染する", "★ contain と混同注意。名 contamination"),
        ("dwindle", "動", "次第に減少する、先細りになる",
         ("徐々に膨らむ", "あてもなくうろつく", "長く住みつく"),
         "dwindling resources", "先細りしていく資源", "自動詞。目的語を取らない"),
        ("anomaly", "名", "異常、例外",
         ("匿名であること", "類推", "敵意"),
         "a statistical anomaly", "統計上の異常値", "形 anomalous"),
        ("rationale", "名", "（行動・判断の）根拠、論拠",
         ("（物資の）配給", "比率", "合理主義者"),
         "the rationale behind the decision", "その決定の根拠", "★ rational（合理的な）とは別語"),
        ("repercussion", "名", "（好ましくない）影響、余波",
         ("（鏡や水面の）光の反射", "打楽器", "単なる繰り返し"),
         "serious repercussions", "深刻な影響", "通例複数形で使う"),
        ("outbreak", "名", "（病気・戦争の）発生、勃発",
         ("（研究上の）大発見", "小休止", "内訳"),
         "an outbreak of influenza", "インフルエンザの発生",
         "動詞 break out（発生する）の名詞形。★ breakthrough（大発見）と混同注意"),
        ("surplus", "名", "余剰、黒字",
         ("赤字", "追加料金", "表面積"),
         "a trade surplus", "貿易黒字", "⇔ deficit"),
        ("vicinity", "名", "近所、付近",
         ("悪徳", "勝利", "粘り強さ"),
         "in the vicinity of the station", "駅の付近に",
         "in the vicinity of が「およそ〜」になるのは数量の前だけ（in the vicinity of $1 million）。場所なら「〜の付近に」"),
        ("account for", "熟", "〜を説明する／〜を占める",
         ("〜を勘定から外す／無視する", "〜を前提とする", "〜に異議を唱える"),
         "account for 30% of sales", "売上の30%を占める", "2つの意味を必ずセットで覚える"),
        ("abide by", "熟", "（規則・決定を）順守する",
         ("（職場や学校の）そばに住む", "〜を待ちわびる", "〜を我慢する"),
         "abide by the rules", "規則を守る", "abide 単独なら「我慢する」。by を伴えば「順守する」"),
        ("single out", "熟", "〜を選び出す、名指しする",
         ("〜を独身のままにする", "〜を一つにまとめる", "〜を締め出す"),
         "single out one student", "一人の生徒を名指しする", "ほめる場合にも責める場合にも使う"),
        ("wear off", "熟", "（効果・痛みが）徐々に消える",
         ("着古してぼろぼろになる", "習慣として身につく", "〜を脱ぎ捨てる"),
         "The medicine wore off.", "薬の効き目が切れた", "★ wear out（すり減る／疲れ果てる）と区別"),
    ]},
    # ============================== 第6回 ==============================
    {"no": 6, "title": "評価を下す形容詞・副詞", "items": [
        ("adverse", "形", "不利な、好ましくない",
         ("多様な", "広告用の", "逆行する"),
         "adverse effects", "悪影響", "★ averse（〜を嫌って）と混同注意"),
        ("arbitrary", "形", "恣意的な、独断的な",
         ("仲裁による", "芸術的な", "気前のよい"),
         "an arbitrary decision", "独断的な決定", "副 arbitrarily"),
        ("compulsory", "形", "義務的な、強制の",
         ("任意の", "衝動的な", "補完的な"),
         "compulsory education", "義務教育", "≒ mandatory ⇔ voluntary"),
        ("detrimental", "形", "有害な、不利益をもたらす",
         ("決定的な", "有益な", "精密な"),
         "detrimental to health", "健康に有害な", "detrimental to が定型"),
        ("eligible", "形", "資格のある、適格な",
         ("読みやすい", "選択制の", "好都合な"),
         "eligible for the discount", "割引を受ける資格がある", "★ illegible（判読できない）と混同注意"),
        ("feasible", "形", "実行可能な、実現できる",
         ("到底できそうにない", "手ごろな値段の", "融通のきく"),
         "a feasible plan", "実行可能な計画", "名 feasibility（実現可能性）"),
        ("imminent", "形", "差し迫った、今にも起こりそうな",
         ("卓越した", "生まれつき備わった", "免疫のある"),
         "an imminent threat", "差し迫った脅威", "★ eminent（著名な）と混同注意"),
        ("indispensable", "形", "不可欠な、なくてはならない",
         ("使い捨ての", "分割できない", "不明瞭な"),
         "indispensable to the team", "チームに不可欠な", "⇔ dispensable"),
        ("obsolete", "形", "廃れた、時代遅れの",
         ("絶対的な", "執拗な", "あいまいな"),
         "obsolete technology", "時代遅れの技術", "≒ outdated"),
        ("rigorous", "形", "厳格な、厳密な",
         ("雑な", "活発な", "硬直した"),
         "rigorous testing", "厳密な検査", "名 rigor。★ rigid（硬直した）と区別"),
        ("subtle", "形", "微妙な、かすかな",
         ("明白な", "従属的な", "洗練された"),
         "a subtle difference", "微妙な違い", "b は発音しない"),
        ("versatile", "形", "多才な、用途の広い",
         ("垂直の", "口頭による", "移り気な"),
         "a versatile player", "多才な選手", "名 versatility"),
        ("vulnerable", "形", "傷つきやすい、脆弱な",
         ("揮発性の", "値打ちのある", "自発的な"),
         "vulnerable to attack", "攻撃に対して脆弱な", "名 vulnerability"),
        ("conversely", "副", "逆に、反対に",
         ("慎重に", "特に", "会話の中で"),
         "Conversely, prices may fall.", "逆に価格が下がることもある", "形 converse（逆の）"),
        ("drastically", "副", "大幅に、思い切って",
         ("まれに", "定期的に", "芝居がかって"),
         "drastically reduce costs", "コストを大幅に削減する", "形 drastic"),
        ("invariably", "副", "常に、決まって",
         ("時々", "多様に", "気づかれずに"),
         "He is invariably late.", "彼はいつも遅刻する", "vary（変わる）の否定→変わることなく"),
        ("keep abreast of", "熟", "〜に遅れずについていく、〜を把握し続ける",
         ("〜を胸にしまっておく", "〜から距離を置く", "〜を前もって知らせる"),
         "keep abreast of the news", "最新の情報を把握し続ける", "abreast＝横に並んで"),
        ("make headway", "熟", "前進する、進展する",
         ("見出しをつける", "先頭に立って歩く", "道を譲る"),
         "make headway in the talks", "交渉が進展する", "進みにくい状況で使うことが多い"),
        ("opt for", "熟", "〜を選ぶ",
         ("〜を試す", "〜に反対する", "〜を任意とする"),
         "opt for the cheaper plan", "安いほうのプランを選ぶ", "opt out of＝〜に参加しないことを選ぶ"),
        ("water down", "熟", "〜を骨抜きにする、和らげる",
         ("〜に水をやる", "〜を書き直す", "〜を撤回する"),
         "water down the proposal", "提案を骨抜きにする", "薄める→効力を弱める"),
    ]},
    # ============================== 第7回 ==============================
    {"no": 7, "title": "組織・法制度を語る語", "items": [
        ("attribute", "動", "〜を…によるものと考える、〜に帰する",
         ("〜に貢献する", "（資料を）配布する", "〜を過大に評価する"),
         "attribute success to luck", "成功を運のおかげだとする", "attribute A to B。名詞では「属性」"),
        ("bolster", "動", "〜を強化する、下支えする",
         ("〜を借り受ける", "〜を大胆にする", "〜をボルトで留める"),
         "bolster confidence", "自信を高める", "名詞では「長まくら」"),
        ("confine", "動", "〜を制限する、閉じ込める",
         ("〜を確認する", "〜を定義する", "〜を洗練させる"),
         "be confined to bed", "寝たきりである", "★ confirm と混同注意"),
        ("delegate", "動", "（権限・仕事を）委任する",
         ("（役職や等級を）格下げする", "〜を遅らせる", "〜を審議する"),
         "delegate authority", "権限を委譲する", "名詞では「代表者」"),
        ("disclose", "動", "〜を開示する、暴露する",
         ("〜を閉鎖する", "〜を割り引く", "〜を処分する"),
         "disclose information", "情報を開示する", "名 disclosure"),
        ("enforce", "動", "（法を）施行する、強制的に守らせる",
         ("（制度・規則を）廃止する", "〜を強く勧める", "〜を一時停止する"),
         "enforce the law", "法を執行する", "名 enforcement。★ reinforce（補強する）と区別"),
        ("induce", "動", "〜する気にさせる、〜を引き起こす",
         ("〜を演繹する", "〜を導入する", "〜を減らす"),
         "induce him to sign the contract", "彼に契約する気を起こさせる",
         "induce A to do＝Aに〜する気を起こさせる。★ introduce / deduce と混同注意"),
        ("prohibit", "動", "〜を禁止する",
         ("〜を促進する", "〜を予言する", "〜を保護する"),
         "prohibit smoking", "喫煙を禁止する", "prohibit A from -ing"),
        ("replicate", "動", "〜を複製する、再現する",
         ("〜に返答する", "〜を交換する", "〜を否定する"),
         "replicate the results", "実験結果を再現する", "名 replication"),
        ("revoke", "動", "〜を取り消す、無効にする",
         ("〜を回す", "〜を復活させる", "〜を思い出す"),
         "revoke a license", "免許を取り消す", "★ recall / revive と区別"),
        ("apprehension", "名", "不安、懸念",
         ("見習い期間", "称賛", "適性"),
         "with apprehension", "不安を抱いて", "形 apprehensive（心配して）"),
        ("bias", "名", "偏見、先入観",
         ("双方向性", "概略", "買収工作"),
         "a gender bias", "性別による偏見", "biased＝偏った"),
        ("commodity", "名", "商品、日用品",
         ("共同体", "委員会", "快適"),
         "a valuable commodity", "価値のある商品", "経済では「一次産品」"),
        ("negligence", "名", "怠慢、過失",
         ("交渉", "近隣地域", "全面否定"),
         "gross negligence", "重大な過失", "形 negligent"),
        ("skepticism", "名", "懐疑、疑う気持ち",
         ("確信", "専門知識", "見取り図"),
         "with skepticism", "懐疑的に", "形 skeptical"),
        ("upheaval", "名", "大変動、激変",
         ("上昇", "現状維持", "隆起した丘"),
         "social upheaval", "社会の大変動", "heave＝持ち上げる"),
        ("fall through", "熟", "（計画・取引が）だめになる、頓挫する",
         ("（トンネルなどを）通り抜ける", "〜に恋をする", "徹底的に調べ上げる"),
         "The deal fell through.", "その商談は流れた", "⇔ go through（成立する）"),
        ("gloss over", "熟", "〜を取り繕う、都合の悪い点をごまかす",
         ("〜を見渡す", "〜につやを出す", "〜に注釈する"),
         "gloss over the problem", "問題をうやむやにする", "表面をつやつやにして隠すイメージ"),
        ("pin down", "熟", "（原因などを）特定する、突き止める",
         ("〜をピンで留めて飾る", "（虫や紙を）押しつぶす", "〜を書き留める"),
         "pin down the cause", "原因を突き止める", "人に対しては「言質を取る」"),
        ("usher in", "熟", "〜の到来を告げる、〜の先駆けとなる",
         ("〜を締め出す", "（客を）静かに退場させる", "〜を急き立てる"),
         "usher in a new era", "新時代の幕開けとなる", "usher＝案内係"),
    ]},
    # ============================== 第8回 ==============================
    {"no": 8, "title": "心情・態度を表す語", "items": [
        ("alienate", "動", "〜を疎外する、〜の心を遠ざける",
         ("〜を強く励ます", "〜と手を結ばせる", "〜の負担を軽くする"),
         "alienate voters", "有権者の心を離れさせる", "alien＝よそ者"),
        ("ascertain", "動", "〜を確かめる、突き止める",
         ("〜を上げる", "〜のせいにする", "〜を断言する"),
         "ascertain the facts", "事実を確認する", "★ assert（断言する）と区別"),
        ("condone", "動", "〜を大目に見る、黙認する",
         ("〜を厳しく罰する", "〜を凝縮する", "〜に条件をつける"),
         "condone violence", "暴力を黙認する", "★ condemn（非難する）と正反対。混同注意"),
        ("deem", "動", "〜だとみなす、考える",
         ("〜を言いふらす", "〜を深める", "〜を軽んじる"),
         "deem it necessary", "それを必要だとみなす", "≒ consider（かたい語）"),
        ("emulate", "動", "〜を見習う、手本にして張り合う",
         ("〜を包む", "〜を乳化させる", "〜をからかう"),
         "emulate a role model", "手本となる人を見習う", "良い意味の「まねる」"),
        ("instill", "動", "（考え・感情を）徐々に植え付ける",
         ("（酒や水を）蒸留する", "〜を設置する", "〜を静止させる"),
         "instill confidence in students", "生徒に自信を植え付ける", "★ install（設置する）と混同注意"),
        ("relinquish", "動", "〜を（しぶしぶ）手放す、放棄する",
         ("（家具などを）磨き直す", "〜を強く要求する", "〜を消し去る"),
         "relinquish control", "支配権を手放す", "≒ give up（かたい語）"),
        ("resent", "動", "〜に憤慨する、〜を不快に思う",
         ("〜を再送する", "〜を提示する", "〜に快く同意する"),
         "resent the criticism", "その批判に腹を立てる", "名 resentment"),
        ("sustain", "動", "〜を維持する／（損害を）受ける",
         ("〜を停止させる／中断する", "〜を染色する", "〜を仮定する"),
         "sustain economic growth", "経済成長を維持する", "sustain injuries＝負傷する"),
        ("wane", "動", "衰える、次第に弱まる",
         ("待ち構える", "強く警告する", "さまよう"),
         "Interest in the topic waned.", "その話題への関心が薄れた", "⇔ wax（満ちる）"),
        ("adversity", "名", "逆境、苦難",
         ("多様", "広告宣伝", "有益な助言"),
         "overcome adversity", "逆境を乗り越える", "形 adverse"),
        ("allegation", "名", "（証拠のない）申し立て、疑惑",
         ("（主君や国への）忠誠", "たとえ話", "割り当て"),
         "deny the allegations", "疑惑を否定する", "動 allege"),
        ("deterrent", "名", "抑止力、思いとどまらせるもの",
         ("粉末状の洗剤", "決定的な要因", "品質の劣化"),
         "a nuclear deterrent", "核抑止力", "動 deter"),
        ("downturn", "名", "（景気の）低迷、悪化",
         ("（歴史の）転換点", "頭金", "縮小版"),
         "an economic downturn", "景気後退", "⇔ upturn"),
        ("quota", "名", "割当、ノルマ",
         ("引用", "割り算の商", "市場の相場"),
         "meet the quota", "ノルマを達成する", "★ quote（引用）と区別"),
        ("testimony", "名", "証言、（〜を示す）証拠",
         ("遺言", "反対尋問", "陪審の評決"),
         "give testimony in court", "法廷で証言する", "動 testify"),
        ("bank on", "熟", "〜を当てにする、頼りにする",
         ("〜を銀行に預ける", "〜に賭けて負ける", "〜を岸に寄せる"),
         "bank on his support", "彼の支持を当てにする", "≒ count on"),
        ("lash out at", "熟", "〜を激しく非難する、〜に食ってかかる",
         ("〜をひもで縛りつける", "〜をむちで打って追い出す", "〜を期限で締め切る"),
         "lash out at critics", "批判する人々を激しく攻撃する", "lash＝むちで打つ"),
        ("mull over", "熟", "〜をじっくり考える",
         ("〜を台無しにする", "〜を細かく挽く", "〜を蒸し返す"),
         "mull over the offer", "その申し出をよく考える", "≒ ponder"),
        ("ramp up", "熟", "〜を増強する、拡大する",
         ("〜をやめる", "〜を暴走させる", "〜を巻き上げる"),
         "ramp up production", "生産を増強する", "⇔ wind down（縮小する）"),
    ]},
    # ============================== 第9回 ==============================
    {"no": 9, "title": "説明文・資料で出る語", "items": [
        ("augment", "動", "〜を増大させる、増強する",
         ("〜を論じ合う", "〜を縮小する", "〜を組み立てる"),
         "augment one's income", "収入を増やす", "AR＝augmented reality（拡張現実）"),
        ("compile", "動", "（資料を集めて）〜をまとめる、編集する",
         ("〜を積み上げて崩す", "（同意や自白を）強要する", "〜を最後までやり遂げる"),
         "compile a report", "報告書をまとめる", "名 compilation"),
        ("depict", "動", "〜を描写する、表現する",
         ("〜を切り取って捨てる", "〜を選び出す", "〜を強く非難する"),
         "depict rural life", "田舎の暮らしを描く", "名 depiction"),
        ("designate", "動", "〜を指定する、任命する",
         ("〜を辞任させる", "（計画を）白紙に戻す", "〜を軽視する"),
         "a designated area", "指定された区域", "★ design とは別語。名 designation"),
        ("impose", "動", "（税・負担を）課す、押し付ける",
         ("（秘密や悩みを）打ち明ける", "〜を構成する", "〜に反対する"),
         "impose a tax on imports", "輸入品に税を課す", "impose A on B"),
        ("outweigh", "動", "〜に勝る、〜より重要である",
         ("〜を追う", "〜より劣る", "〜を量り直す"),
         "The benefits outweigh the risks.", "利点がリスクを上回る", "out-（勝る）+ weigh"),
        ("penalize", "動", "〜を罰する、〜に不利益を与える",
         ("〜を貫通する", "〜を審理にかける", "〜に報いる"),
         "penalize offenders", "違反者を罰する", "名 penalty"),
        ("subsidize", "動", "〜に補助金を出す",
         ("〜を沈下させる", "〜の代用品を使う", "〜を細かく分割する"),
         "subsidize farmers", "農家に補助金を出す", "名 subsidy"),
        ("validate", "動", "〜の正しさを裏づける、有効にする",
         ("〜に価格をつける", "〜を無効にする", "〜を歓迎する"),
         "validate the theory", "その理論の正しさを裏づける", "⇔ invalidate"),
        ("yield", "動", "〜を産出する／（圧力に）屈する",
         ("〜を大声で叫ぶ／わめく", "〜を溶接する", "〜を強く望む"),
         "yield good results", "良い成果を生む", "名詞では「収穫量・利回り」"),
        ("implication", "名", "（予想される）影響、言外の意味",
         ("（言葉を尽くした）明示的な説明", "複製物", "実地への応用"),
         "policy implications", "政策上の含意", "動 imply"),
        ("infrastructure", "名", "社会基盤、インフラ",
         ("上部構造", "下請け業者", "建物の内部構造"),
         "aging infrastructure", "老朽化したインフラ", "infra-＝下部の"),
        ("integrity", "名", "誠実さ、高潔／完全な状態",
         ("統合作業", "高い知性", "物理的な強度"),
         "a person of integrity", "高潔な人物", "データの「完全性」の意味でも使う"),
        ("peril", "名", "（重大な）危険",
         ("（貝から採れる）真珠", "一定の期間", "正式な許可"),
         "in grave peril", "重大な危機に瀕して", "形 perilous"),
        ("remnant", "名", "残り、名残",
         ("送金", "記念品", "修繕作業"),
         "remnants of the past", "過去の名残", "通例複数形"),
        ("stagnation", "名", "停滞、不振",
         ("隔離", "段階を追った発展", "（水位や気温の）急上昇"),
         "economic stagnation", "経済の停滞", "動 stagnate"),
        ("dwell on", "熟", "〜をくよくよ考える、長々と論じる",
         ("〜に住み着く", "〜を深く掘り下げて掘る", "〜を膨らませる"),
         "dwell on the past", "過去にこだわり続ける", "dwell 単独は「住む」"),
        ("fend off", "熟", "〜をかわす、撃退する",
         ("〜を囲う", "〜を仕上げる", "〜を差し出す"),
         "fend off criticism", "批判をかわす", "fend for oneself＝自活する"),
        ("sift through", "熟", "〜をふるいにかけて調べる、精査する",
         ("〜をすり抜ける", "〜を移し替える", "〜をこぼして失う"),
         "sift through the data", "データを丹念に調べる", "sift＝ふるいにかける"),
        ("wind up doing", "熟", "結局〜することになる",
         ("〜する寸前でやめる", "〜するよう説得される", "〜し慣れている"),
         "wind up paying more", "結局よけいに払うはめになる", "≒ end up doing"),
    ]},
    # ============================== 第10回 ==============================
    {"no": 10, "title": "抽象度の高い形容詞・熟語", "items": [
        ("articulate", "動", "〜を明確に述べる",
         ("〜を人工的に作り出す", "〜をあえてぼかす", "〜を丸暗記する"),
         "articulate a vision", "構想を明確に語る", "形容詞では「弁の立つ」"),
        ("constitute", "動", "〜を構成する、〜に相当する",
         ("〜を中断する", "〜の代用となる", "〜を制限する"),
         "Twelve members constitute the committee.", "12名の委員がその委員会を構成している",
         "名 constitution"),
        ("cultivate", "動", "（関係・能力を）育む／〜を耕す",
         ("〜を切り倒す／伐採する", "〜を強く非難する", "〜を暗記する"),
         "cultivate relationships", "人間関係を育む", "名 cultivation"),
        ("lure", "動", "〜を誘い込む、おびき寄せる",
         ("〜を追い払う", "〜を待ち伏せする", "〜をだまし取る"),
         "lure customers with discounts", "割引で客を引き寄せる", "名詞では「誘惑・おとり」"),
        ("perceive", "動", "〜を知覚する、〜だと捉える",
         ("〜を追い求める", "〜を保存する", "〜に耐え抜く"),
         "perceive it as a threat", "それを脅威と捉える", "名 perception。★ pursue / preserve と区別"),
        ("supplement", "動", "〜を補う、補足する",
         ("〜を頼む", "〜を交換する", "〜を単純化する"),
         "supplement one's income", "収入を補う", "名詞では「補足・栄養補助食品」"),
        ("terminate", "動", "〜を終了させる、打ち切る",
         ("〜を要約する", "〜に条件をつける", "〜を最終決定する"),
         "terminate a contract", "契約を打ち切る", "名 termination"),
        ("abundant", "形", "豊富な、大量にある",
         ("乏しい", "突発的な", "見捨てられた"),
         "abundant natural resources", "豊富な天然資源", "名 abundance"),
        ("conducive", "形", "（良い結果に）つながる、資する",
         ("（金属などが）電気を通しやすい", "誘導しやすい", "結論を示す"),
         "conducive to learning", "学習に資する", "conducive to が定型"),
        ("formidable", "形", "手ごわい、恐るべき",
         ("形を変えやすい", "好意的な", "その場限りの"),
         "a formidable opponent", "手ごわい相手", "圧倒されるほど強い、の含み"),
        ("impartial", "形", "公平な、偏らない",
         ("偏った", "不完全な", "無関心な"),
         "an impartial judge", "公平な裁判官", "⇔ partial（えこひいきする）"),
        ("lenient", "形", "寛大な、処分が甘い",
         ("けちな", "斜めに傾いた", "終始一貫した"),
         "a lenient sentence", "軽い判決", "⇔ strict, severe"),
        ("mundane", "形", "平凡な、ありふれた",
         ("月曜の", "世界的な", "気前のよい"),
         "mundane tasks", "平凡な雑務", "≒ ordinary, routine"),
        ("negligible", "形", "無視できるほど小さい",
         ("職務怠慢な", "交渉の余地がある", "判読できない"),
         "a negligible amount", "ごくわずかな量", "★ negligent（怠慢な）と区別"),
        ("sporadic", "形", "散発的な、時おり起こる",
         ("胞子の", "素早い", "連続的な"),
         "sporadic outbreaks", "散発的な発生", "副 sporadically"),
        ("stringent", "形", "（規則が）厳しい、厳格な",
         ("（分量が）おおざっぱな", "強い刺激のある", "弦楽器を使った"),
         "stringent regulations", "厳しい規制", "≒ strict, rigorous"),
        ("at the expense of", "熟", "〜を犠牲にして、〜の負担で",
         ("〜のおかげで", "〜に応じて", "〜を見越して"),
         "growth at the expense of the environment", "環境を犠牲にした成長", "expense＝代償・費用"),
        ("in tandem with", "熟", "〜と連携して、〜と並行して",
         ("〜とは対照的に", "〜の代わりに", "〜に反して"),
         "work in tandem with the police", "警察と連携して動く", "tandem＝縦一列"),
        ("on a par with", "熟", "〜と同等で、〜に匹敵して",
         ("〜に次いで", "〜より劣って", "〜より優れて"),
         "on a par with the world's best", "世界最高水準に匹敵して",
         "par＝標準・基準。★辞書の見出しは on a par with（冠詞 a が入る）"),
        ("jump the gun", "熟", "早まったことをする、フライングする",
         ("銃を飛び越える", "あえて危険を冒す", "引き金を引く"),
         "Don't jump the gun.", "先走るな", "陸上競技のフライングから"),
    ]},
]
