# -*- coding: utf-8 -*-
"""英検準1級 単語テスト（4択・全20回×20語=400語）の単一ソース。

1エントリ = (word, pos, gloss, (distractor1, distractor2, distractor3),
             usage_en, usage_ja, note)
  word      : 見出し語（英語）。熟語・句動詞も同じ枠に入れる
  pos       : 動 / 名 / 形 / 副 / 熟
  gloss     : 正解の語義（日本語）
  distractors: 誤答の語義3つ。★「その語の別の正しい語義」を絶対に入れない（2正解になる）
  usage_en / usage_ja : 解答編に載せる用例（コロケーション）
  note      : 派生語・混同注意・反意語などの一言メモ

各回16語（単語）＋4語（熟語・句動詞）。第11〜20回は準1級の中核語で構成。正解位置は build 時に word の md5 順で
0〜3へ均等配分するので、ここでは正解を先頭に書いてよい（順序に意味は無い）。
第1〜2回のコア語は scripts/eiken_junichi/data/part1_vocab.json（3段検証済み）と共有。
"""

TESTS = [
    # ============================== 第1回 ==============================
    {"no": 1, "title": "動詞・名詞の中核", "items": [
        ("alleviate", "動", "〜を和らげる、軽減する",
         ("〜を長引かせる", "〜を挑発する", "〜を強める"),
         "alleviate poverty", "貧困を軽減する", "名 alleviation／≒ ease, relieve, mitigate"),
        ("deteriorate", "動", "悪化する、劣化する",
         ("回復する", "加速する", "分散する"),
         "His health deteriorated.", "彼の健康が悪化した", "自動詞。名 deterioration"),
        ("mitigate", "動", "〜を緩和する、軽減する",
         ("〜を誇張する", "〜を延期する", "〜を模倣する"),
         "mitigate the damage", "被害を緩和する", "mitigating circumstances＝情状酌量すべき事情"),
        ("advocate", "動", "〜を主張する、擁護する",
         ("〜をためらう", "〜を撤回する", "〜を軽視する"),
         "advocate reform", "改革を主張する", "名詞にもなる。動詞は「公に支持を表明する」含み"),
        ("undermine", "動", "〜を徐々に損なう、弱体化させる",
         ("〜を強固にする", "〜を掘り起こす", "〜を見落とす"),
         "undermine trust", "信頼を損なう", "mine＝掘る。下から掘り崩すイメージ"),
        ("comply", "動", "（規則などに）従う、順守する",
         ("（サービスに）苦情を言う", "補償する", "完了する"),
         "comply with the rules", "規則に従う", "comply with が定型。名 compliance"),
        ("exacerbate", "動", "〜を悪化させる、深刻化させる",
         ("〜を正当化する", "〜を免除する", "〜を発掘する"),
         "exacerbate tensions", "緊張を悪化させる", "≒ aggravate ⇔ alleviate"),
        ("deter", "動", "〜を思いとどまらせる、やめさせる",
         ("〜を決定する", "〜をそそのかす", "〜を先延ばしにする"),
         "deter crime", "犯罪を思いとどまらせる", "deter A from -ing（Aに〜するのを思いとどまらせる）"),
        ("allocate", "動", "〜を割り当てる、配分する",
         ("〜を没収する", "〜を隠す", "〜を複製する"),
         "allocate funds", "資金を配分する", "allocate A to B。名 allocation"),
        ("scrutiny", "名", "精査、綿密な調査",
         ("気まぐれ", "概略", "中傷"),
         "under close scrutiny", "厳しい精査を受けて", "動 scrutinize"),
        ("discrepancy", "名", "食い違い、不一致",
         ("完全な一致", "遅延", "偏見"),
         "a discrepancy between the two reports", "2つの報告書の食い違い", "≒ inconsistency"),
        ("incentive", "名", "動機づけ、誘因、報奨",
         ("障害", "罰則", "偶然の一致"),
         "an incentive to study harder", "もっと勉強しようという動機づけ", "incentive to do の形で使う"),
        ("backlash", "名", "（激しい）反発、反感",
         ("（大事件の）前触れ", "政治的な妥協", "全面的な賛同"),
         "a public backlash", "世論の激しい反発", "backlash against 〜への反発"),
        ("prerequisite", "名", "前提条件、必須要件",
         ("副産物", "例外規定", "見積もり"),
         "a prerequisite for success", "成功の前提条件", "pre-（前）+ requisite（必要な）"),
        ("plight", "名", "苦境、窮状",
         ("名声", "特権", "節目"),
         "the plight of refugees", "難民の窮状", "悪い状況にのみ使う"),
        ("surge", "名", "急増、急激な高まり",
         ("停滞", "余剰", "深刻な不足"),
         "a surge in demand", "需要の急増", "動詞にもなる。波が押し寄せるイメージ"),
        ("iron out", "熟", "（意見の相違・問題を）解決する、片づける",
         ("（収まった話を）蒸し返す", "〜を黙って見過ごす", "〜を印刷して配る"),
         "iron out the differences", "意見の相違を解消する", "アイロンでしわを伸ばすイメージ"),
        ("weed out", "熟", "〜をふるい落とす、取り除く",
         ("〜を新たに採用する", "〜を植え付ける", "〜をかき集める"),
         "weed out weak candidates", "不適格な候補者をふるい落とす", "weed＝雑草を抜く"),
        ("rule out", "熟", "（可能性を）除外する、排除する",
         ("（新しい手順を）方針として定める", "〜に判定を下す", "〜を支配する"),
         "rule out the possibility", "その可能性を排除する", "⇔ rule in（候補に残す）"),
        ("come down with", "熟", "（病気に）かかる",
         ("〜を持って降りてくる", "（けんかのあと）仲直りする", "〜に潔く降参する"),
         "come down with the flu", "インフルエンザにかかる", "比較的軽い病気に使う"),
    ]},
    # ============================== 第2回 ==============================
    {"no": 2, "title": "形容詞・副詞の中核", "items": [
        ("plausible", "形", "もっともらしい、ありそうな",
         ("賞賛に値する", "疑いようのない", "実行可能な"),
         "a plausible explanation", "もっともらしい説明", "⇔ implausible。「本当らしいが確証はない」含み"),
        ("meticulous", "形", "細心の、極めて綿密な",
         ("大ざっぱな", "疑い深い", "気軽な"),
         "meticulous attention to detail", "細部への細心の注意", "≒ scrupulous／細部まで手を抜かないこと"),
        ("susceptible", "形", "（病気などに）かかりやすい、影響を受けやすい",
         ("（証拠が薄く）疑わしい", "持続可能な", "抜け目のない"),
         "susceptible to infection", "感染しやすい", "susceptible to が定型"),
        ("inevitable", "形", "避けられない、必然の",
         ("予測できない", "取るに足りない", "評価できない"),
         "an inevitable consequence", "必然の結果", "副 inevitably"),
        ("lucrative", "形", "もうかる、利益の大きい",
         ("幸運な", "ぜいたくな", "なめらかな"),
         "a lucrative business", "もうかる商売", "≒ profitable"),
        ("prevalent", "形", "広く行き渡った、はやっている",
         ("ごくまれな", "一時的な", "予防のための"),
         "a prevalent belief", "広く浸透している考え", "名 prevalence"),
        ("redundant", "形", "余分な、（人員が）余剰の",
         ("不可欠な", "潤沢な", "際立った"),
         "be made redundant", "（英）人員整理で解雇される", "IT では「冗長な＝予備の」"),
        ("tentative", "形", "暫定的な、仮の",
         ("決定的な", "強制的な", "長期的な"),
         "a tentative agreement", "暫定的な合意", "≒ provisional"),
        ("resilient", "形", "回復力のある、立ち直りが早い",
         ("反抗的な", "従順な", "もろい"),
         "a resilient economy", "立ち直りの早い経済", "名 resilience"),
        ("ambiguous", "形", "あいまいな、複数の意味に取れる",
         ("野心的な", "きわめて明快な", "大規模な"),
         "an ambiguous answer", "あいまいな返答", "名 ambiguity"),
        ("compelling", "形", "説得力のある、非常に興味を引く",
         ("型どおりの", "見込みの薄い", "複雑で分かりにくい"),
         "compelling evidence", "説得力のある証拠", "動 compel（強制する）から意味が離れている点に注意"),
        ("inadvertently", "副", "うっかり、不注意で",
         ("意図的に", "執拗に", "ごくまれに"),
         "inadvertently delete a file", "うっかりファイルを削除する", "⇔ deliberately"),
        ("unanimously", "副", "満場一致で",
         ("匿名のままで", "圧倒的多数で", "一人ずつ個別に"),
         "vote unanimously", "満場一致で議決する", "形 unanimous。可決とは限らない（否決も満場一致でありうる）"),
        ("sparingly", "副", "控えめに、少量だけ",
         ("惜しみなく", "予備として", "不意に"),
         "use salt sparingly", "塩を控えめに使う", "spare＝節約する"),
        ("presumably", "副", "おそらく、推定するに",
         ("明らかに", "意外にも", "一見したところ"),
         "Presumably he knew.", "おそらく彼は知っていた", "動 presume"),
        ("profoundly", "副", "深く、甚大に",
         ("浅く", "たまに", "職業として"),
         "profoundly affect society", "社会に深い影響を与える", "形 profound"),
        ("get away with", "熟", "（悪事の）罰をまぬがれる、うまくやり過ごす",
         ("（同じ作業に）飽きる", "〜を手放す", "〜と折り合いをつける"),
         "get away with cheating", "不正をしても罰を免れる", "get away from（〜から逃れる）と区別"),
        ("cut back on", "熟", "（量・支出を）減らす、切り詰める",
         ("（計画・事業を）後押しする", "〜に切り替える", "〜を蒸し返す"),
         "cut back on spending", "支出を切り詰める", "≒ reduce"),
        ("at odds with", "熟", "〜と食い違って、対立して",
         ("〜と歩調を合わせて", "〜の見込みで", "〜に賭けて"),
         "at odds with the facts", "事実と食い違って", "odds＝相違・不一致"),
        ("on the verge of", "熟", "今にも〜しそうで、〜の瀬戸際で",
         ("〜の頂点に立って", "〜の代わりに", "〜を口実にして"),
         "on the verge of collapse", "崩壊寸前で", "verge＝縁・境目"),
    ]},
    # ============================== 第3回 ==============================
    {"no": 3, "title": "施策・社会を語る語", "items": [
        ("implement", "動", "〜を実施する、実行に移す",
         ("〜をほのめかす", "〜を輸入する", "〜を改良する"),
         "implement a policy", "政策を実施する", "名詞では「道具」。名 implementation"),
        ("facilitate", "動", "〜を促進する、容易にする",
         ("〜を複雑にする", "〜を施設に収容する", "〜を偽造する"),
         "facilitate communication", "意思疎通を円滑にする", "名 facilitator（進行役）"),
        ("foster", "動", "〜を育成する、助長する",
         ("〜を見捨てる", "〜を独占する", "〜を急がせる"),
         "foster innovation", "技術革新を促す", "foster child＝里子"),
        ("hamper", "動", "〜を妨げる、阻害する",
         ("〜を包み込む", "〜を誇張する", "〜を加速させる"),
         "hamper economic growth", "経済成長を妨げる", "≒ hinder, impede"),
        ("entail", "動", "〜を必然的に伴う、必要とする",
         ("〜を詳述する", "〜を尾行する", "〜を要約する"),
         "entail serious risks", "重大なリスクを伴う", "≒ involve"),
        ("impair", "動", "〜を損なう、弱める",
         ("〜を修復する", "〜を試験する", "〜を高く評価する"),
         "impair judgment", "判断力を損なう", "visually impaired＝視覚に障害のある"),
        ("incur", "動", "（損失・非難を）招く、負う",
         ("（危険・出費を）回避する", "〜を治療する", "〜を励ます"),
         "incur huge debts", "多額の借金を負う", "incur costs / criticism"),
        ("inhibit", "動", "（成長・反応を）抑える、妨げる",
         ("〜に居住する", "（水分・栄養を）吸収する", "〜を相続する"),
         "inhibit bacterial growth", "細菌の増殖を抑える", "★ inhabit（住む）と混同注意"),
        ("deploy", "動", "〜を配備する、展開する",
         ("〜を破壊する", "〜を雇用する", "〜を展示販売する"),
         "deploy troops", "部隊を配備する", "IT でも「システムを本番投入する」"),
        ("curb", "動", "〜を抑制する、制御する",
         ("〜を測定する", "〜を湾曲させる", "〜を許可する"),
         "curb inflation", "インフレを抑える", "名詞では「（歩道の）縁石」"),
        ("constraint", "名", "制約、束縛",
         ("建設工事", "一貫性", "貢献"),
         "budget constraints", "予算上の制約", "動 constrain"),
        ("disparity", "名", "（不公平な）格差、相違",
         ("（力や量の）完全な均衡", "出発", "絶望"),
         "income disparity", "所得格差", "dis-（打ち消し）＋ par（等しい）から"),
        ("consensus", "名", "総意、意見の一致",
         ("国勢調査", "検閲", "強い反論"),
         "reach a consensus", "合意に達する", "by consensus＝合意によって。反対が出ていない状態を指す"),
        ("hierarchy", "名", "階層、序列",
         ("遺産", "世襲財産", "隠遁生活"),
         "a rigid hierarchy", "厳格な階層構造", "形 hierarchical"),
        ("deficit", "名", "赤字、不足",
         ("黒字", "欠陥品", "定義"),
         "a trade deficit", "貿易赤字", "財政赤字は a budget deficit。⇔ 黒字"),
        ("initiative", "名", "新たな取り組み、主導権",
         ("頭文字", "最終段階", "直感"),
         "take the initiative", "主導権を握る", "a green initiative＝環境施策"),
        ("contend with", "熟", "（困難・問題に）対処する、立ち向かう",
         ("〜に賛成する", "（危険・警告を）軽視する", "〜に委ねる"),
         "contend with hardship", "苦難に立ち向かう", "contend that ...＝〜だと主張する"),
        ("in the wake of", "熟", "〜の直後に、〜の余波を受けて",
         ("〜の前に", "〜の代わりに", "〜のおかげで"),
         "in the wake of the disaster", "その災害の直後に", "wake＝船の航跡"),
        ("stem from", "熟", "〜に起因する、〜から生じる",
         ("〜を食い止める", "〜へ発展する", "〜を根元から断つ"),
         "stem from poverty", "貧困に起因する", "stem＋目的語なら「食い止める」。from を伴えば「起因する」"),
        ("take a toll on", "熟", "〜に打撃を与える、〜を損なう",
         ("〜に通行料を課す", "〜を数え上げる", "〜を大目に見る"),
         "take a toll on health", "健康を害する", "toll＝犠牲・代償"),
    ]},
    # ============================== 第4回 ==============================
    {"no": 4, "title": "議論・変化を語る語", "items": [
        ("eradicate", "動", "〜を根絶する",
         ("〜を放射する", "〜を修正する", "〜を輸出する"),
         "eradicate poverty", "貧困を根絶する", "root（根）ごと抜くイメージ"),
        ("suppress", "動", "〜を抑圧する、抑え込む",
         ("〜を表明する", "〜を圧縮して保存する", "〜を解き放つ"),
         "suppress emotions", "感情を抑える", "名 suppression"),
        ("refute", "動", "〜に反論する、〜の誤りを証明する",
         ("〜を払い戻す", "〜を拒んで受け取らない", "〜を強く要求する"),
         "refute an argument", "主張を論破する", "★ refund（払い戻す）と混同注意"),
        ("endorse", "動", "〜を支持する、推奨する",
         ("〜を耐え忍ぶ", "〜を強制する", "〜を包囲する"),
         "endorse a candidate", "候補者を支持する", "有名人の商品推薦にも使う"),
        ("streamline", "動", "〜を効率化する、合理化する",
         ("〜を放流する", "〜を細分化する", "〜を一列に並べる"),
         "streamline the process", "手続きを簡素化する", "流線形にする→無駄を省く"),
        ("offset", "動", "〜を相殺する、埋め合わせる",
         ("〜を出発させる", "〜を倍増させる", "〜を延期する"),
         "offset the loss", "損失を相殺する", "carbon offset＝炭素の相殺"),
        ("thrive", "動", "繁栄する、生き生きと育つ",
         ("衰退する", "努力する", "到着する"),
         "thrive in a harsh climate", "厳しい気候でもよく育つ", "★ strive（努力する）と混同注意"),
        ("undertake", "動", "〜を引き受ける、〜に着手する",
         ("〜を過小評価する", "〜を取り消す", "〜の下に置く"),
         "undertake a project", "事業を引き受ける", "過去形 undertook / 過去分詞 undertaken"),
        ("speculate", "動", "推測する、投機する",
         ("観察する", "専門とする", "明記する"),
         "speculate about the cause", "原因を推測する", "名 speculation"),
        ("deplete", "動", "〜を枯渇させる、激減させる",
         ("〜を完成させる", "〜を補充する", "〜を陳列する"),
         "deplete natural resources", "天然資源を枯渇させる", "名 depletion。資源・体力が尽きる方向に減ること"),
        ("aftermath", "名", "（災害などの）余波、直後の時期",
         ("（地震などの）前兆", "後回しにすること", "（式典の）後片づけ"),
         "in the aftermath of the war", "戦争の余波の中で",
         "ふつう悪い出来事（戦争・災害・事故など）の後に使う"),
        ("threshold", "名", "境界となる値、敷居",
         ("頂点", "空白部分", "網の目"),
         "the pain threshold", "痛みを感じ始める限界値", "on the threshold of＝〜の入り口で"),
        ("momentum", "名", "勢い、はずみ",
         ("記念碑", "一瞬", "独占"),
         "gain momentum", "勢いを増す", "★ monument（記念碑）と混同注意"),
        ("setback", "名", "挫折、後退",
         ("背景", "予備の計画", "分割返済"),
         "suffer a serious setback", "深刻な挫折を味わう", "⇔ breakthrough"),
        ("sanction", "名", "制裁／（公式の）認可",
         ("聖域／立ち入り禁止区域", "公衆の衛生管理", "（国家間の）休戦協定"),
         "economic sanctions against the country", "その国への経済制裁", "「制裁」と「認可」の正反対の2義を持つ"),
        ("proponent", "名", "支持者、提唱者",
         ("反対者", "所有者", "構成部品"),
         "a proponent of reform", "改革の提唱者", "⇔ opponent"),
        ("crack down on", "熟", "〜を厳しく取り締まる",
         ("〜に屈服する", "〜を解読する", "〜を粉々に砕く"),
         "crack down on fraud", "詐欺を厳しく取り締まる", "名 crackdown"),
        ("shed light on", "熟", "〜を解明する、明らかにする",
         ("〜を覆い隠す", "〜の重荷を下ろす", "〜を大目に見る"),
         "shed light on the cause", "原因を解明する", "shed＝（光を）放つ"),
        ("live up to", "熟", "（期待・評判に）応える",
         ("〜歳まで生き延びる", "（親や親戚と）同居する", "〜を見上げて憧れる"),
         "live up to expectations", "期待に応える", "直訳の「〜まで生きる」は誤り"),
        ("phase out", "熟", "〜を段階的に廃止する",
         ("〜を段階的に導入する", "〜を局面ごとに分析する", "〜を即座に全面禁止する"),
         "phase out plastic bags", "レジ袋を段階的に廃止する", "⇔ phase in（段階的に導入する）"),
    ]},
    # ============================== 第5回 ==============================
    {"no": 5, "title": "データ・経済を語る語", "items": [
        ("accumulate", "動", "〜を蓄積する、たまる",
         ("〜を計算する", "〜を使い果たす", "〜を適応させる"),
         "accumulate wealth", "富を蓄える", "名 accumulation"),
        ("compensate", "動", "（損失などの）埋め合わせをする、補償する",
         ("（意見を）競い合わせる", "〜を凝縮する", "〜を理解する"),
         "compensate for the loss", "損失を埋め合わせる",
         "compensate for 〜（自動詞）＝〜を埋め合わせる／compensate 人 for 〜（他動詞）＝人に補償する。"
         "★他動詞の目的語は「人」で、損失ではない。名 compensation"),
        ("discern", "動", "〜を識別する、見分ける",
         ("〜を懸念する", "〜を辞退する", "〜を解散させる"),
         "discern a pattern", "規則性を見分ける", "形 discernible（見分けがつく）"),
        ("denounce", "動", "〜を公然と非難する",
         ("〜を正式に発表する", "〜を放棄する", "〜を宣言する"),
         "denounce violence", "暴力を非難する", "★ announce / renounce と混同注意"),
        ("reinforce", "動", "〜を補強する、強化する",
         ("〜を再現する", "〜を強要する", "〜を改革する"),
         "reinforce the argument", "主張を補強する", "名 reinforcement"),
        ("retain", "動", "〜を保持する、維持する",
         ("〜を取り戻す", "〜を訓練する", "〜を制限する"),
         "retain customers", "顧客を維持する", "名 retention（定着率）"),
        ("trigger", "動", "〜を引き起こす、誘発する",
         ("〜を追跡する", "〜を締め付ける", "〜を交換する"),
         "trigger an allergic reaction", "アレルギー反応を引き起こす", "名詞では「引き金」"),
        ("verify", "動", "〜を検証する、正しいと確認する",
         ("〜を多様化する", "〜を変更する", "〜を無効にする"),
         "verify the data", "データを検証する", "名 verification"),
        ("contaminate", "動", "〜を汚染する",
         ("〜を内部に含む", "〜を継続する", "〜を封じ込める"),
         "contaminate the water supply", "水道水を汚染する", "★ contain と混同注意。名 contamination"),
        ("dwindle", "動", "次第に減少する、先細りになる",
         ("徐々に膨らむ", "あてもなくうろつく", "長く住みつく"),
         "dwindling resources", "先細りしていく資源", "自動詞。目的語を取らない"),
        ("anomaly", "名", "異常、例外",
         ("匿名であること", "類推", "敵意"),
         "a statistical anomaly", "統計上の異常値", "形 anomalous"),
        ("rationale", "名", "（行動・判断の）根拠、論拠",
         ("（物資の）配給", "比率", "合理主義者"),
         "the rationale behind the decision", "その決定の根拠", "★ rational（合理的な）とは別語"),
        ("repercussion", "名", "（好ましくない）影響、余波",
         ("（鏡や水面の）光の反射", "打楽器", "単なる繰り返し"),
         "serious repercussions", "深刻な影響", "通例複数形で使う"),
        ("outbreak", "名", "（病気・戦争の）発生、勃発",
         ("（研究上の）大発見", "小休止", "内訳"),
         "an outbreak of influenza", "インフルエンザの発生",
         "動詞 break out（発生する）の名詞形。★ breakthrough（大発見）と混同注意"),
        ("surplus", "名", "余剰、黒字",
         ("赤字", "追加料金", "表面積"),
         "a trade surplus", "貿易黒字", "⇔ deficit"),
        ("vicinity", "名", "近所、付近",
         ("悪徳", "勝利", "粘り強さ"),
         "in the vicinity of the station", "駅の付近に",
         "in the vicinity of が「およそ〜」になるのは数量の前だけ（in the vicinity of $1 million）。場所なら「〜の付近に」"),
        ("account for", "熟", "〜を説明する／〜を占める",
         ("〜を勘定から外す／無視する", "〜を前提とする", "〜に異議を唱える"),
         "account for 30% of sales", "売上の30%を占める", "2つの意味を必ずセットで覚える"),
        ("abide by", "熟", "（規則・決定を）順守する",
         ("（職場や学校の）そばに住む", "〜を待ちわびる", "〜を我慢する"),
         "abide by the rules", "規則を守る", "abide 単独なら「我慢する」。by を伴えば「順守する」"),
        ("single out", "熟", "〜を選び出す、名指しする",
         ("〜を独身のままにする", "〜を二つに分ける", "〜を締め出す"),
         "single out one student", "一人の生徒を名指しする", "ほめる場合にも責める場合にも使う"),
        ("wear off", "熟", "（効果・痛みが）徐々に消える",
         ("着古してぼろぼろになる", "習慣として身につく", "〜を脱ぎ捨てる"),
         "The medicine wore off.", "薬の効き目が切れた", "★ wear out（すり減る／疲れ果てる）と区別"),
    ]},
    # ============================== 第6回 ==============================
    {"no": 6, "title": "評価を下す形容詞・副詞", "items": [
        ("adverse", "形", "不利な、好ましくない",
         ("多様な", "広告用の", "逆行する"),
         "adverse effects", "悪影響", "★ averse（〜を嫌って）と混同注意"),
        ("arbitrary", "形", "恣意的な、独断的な",
         ("仲裁による", "芸術的な", "気前のよい"),
         "an arbitrary decision", "独断的な決定", "副 arbitrarily"),
        ("compulsory", "形", "義務的な、強制の",
         ("任意の", "衝動的な", "補完的な"),
         "compulsory education", "義務教育", "≒ mandatory ⇔ voluntary"),
        ("detrimental", "形", "有害な、不利益をもたらす",
         ("決定的な", "有益な", "精密な"),
         "detrimental to health", "健康に有害な", "detrimental to が定型"),
        ("eligible", "形", "資格のある、適格な",
         ("読みやすい", "選択制の", "好都合な"),
         "eligible for the discount", "割引を受ける資格がある", "★ illegible（判読できない）と混同注意"),
        ("feasible", "形", "実行可能な、実現できる",
         ("到底できそうにない", "手ごろな値段の", "融通のきく"),
         "a feasible plan", "実行可能な計画", "名 feasibility（実現可能性）"),
        ("imminent", "形", "差し迫った、今にも起こりそうな",
         ("卓越した", "生まれつき備わった", "免疫のある"),
         "an imminent threat", "差し迫った脅威", "★ eminent（著名な）と混同注意"),
        ("indispensable", "形", "不可欠な、なくてはならない",
         ("使い捨ての", "分割できない", "不明瞭な"),
         "indispensable to the team", "チームに不可欠な", "⇔ dispensable"),
        ("obsolete", "形", "廃れた、時代遅れの",
         ("絶対的な", "執拗な", "あいまいな"),
         "obsolete technology", "時代遅れの技術", "≒ outdated"),
        ("rigorous", "形", "厳格な、厳密な",
         ("雑な", "活発な", "硬直した"),
         "rigorous testing", "厳密な検査", "名 rigor。★ rigid（硬直した）と区別"),
        ("subtle", "形", "微妙な、かすかな",
         ("明白な", "従属的な", "洗練された"),
         "a subtle difference", "微妙な違い", "b は発音しない"),
        ("versatile", "形", "多才な、用途の広い",
         ("垂直の", "口頭による", "移り気な"),
         "a versatile player", "多才な選手", "名 versatility"),
        ("vulnerable", "形", "傷つきやすい、脆弱な",
         ("揮発性の", "値打ちのある", "自発的な"),
         "vulnerable to attack", "攻撃に対して脆弱な", "名 vulnerability"),
        ("conversely", "副", "逆に、反対に",
         ("慎重に", "特に", "会話の中で"),
         "Conversely, prices may fall.", "逆に価格が下がることもある", "形 converse（逆の）"),
        ("drastically", "副", "大幅に、思い切って",
         ("まれに", "定期的に", "芝居がかって"),
         "drastically reduce costs", "コストを大幅に削減する", "形 drastic"),
        ("invariably", "副", "常に、決まって",
         ("時々", "多様に", "気づかれずに"),
         "He is invariably late.", "彼はいつも遅刻する", "vary（変わる）の否定→変わることなく"),
        ("keep abreast of", "熟", "〜に遅れずについていく、〜を把握し続ける",
         ("〜を胸にしまっておく", "〜から距離を置く", "〜を前もって知らせる"),
         "keep abreast of the news", "最新の情報を把握し続ける", "abreast＝横に並んで"),
        ("make headway", "熟", "前進する、進展する",
         ("見出しをつける", "先頭に立って歩く", "道を譲る"),
         "make headway in the talks", "交渉が進展する", "進みにくい状況で使うことが多い"),
        ("opt for", "熟", "〜を選ぶ",
         ("〜を試す", "〜に反対する", "〜を任意とする"),
         "opt for the cheaper plan", "安いほうのプランを選ぶ", "opt out of＝〜に参加しないことを選ぶ"),
        ("water down", "熟", "〜を骨抜きにする、和らげる",
         ("〜に水をやる", "〜を書き直す", "〜を撤回する"),
         "water down the proposal", "提案を骨抜きにする", "薄める→効力を弱める"),
    ]},
    # ============================== 第7回 ==============================
    {"no": 7, "title": "組織・法制度を語る語", "items": [
        ("attribute", "動", "〜を…によるものと考える、〜に帰する",
         ("〜に貢献する", "（資料を）配布する", "〜を過大に評価する"),
         "attribute success to luck", "成功を運のおかげだとする", "attribute A to B。名詞では「属性」"),
        ("bolster", "動", "〜を強化する、下支えする",
         ("〜を借り受ける", "〜を大胆にする", "〜をボルトで留める"),
         "bolster confidence", "自信を高める", "名詞では「長まくら」"),
        ("confine", "動", "〜を制限する、閉じ込める",
         ("〜を確認する", "〜を定義する", "〜を洗練させる"),
         "be confined to bed", "寝たきりである", "★ confirm と混同注意"),
        ("delegate", "動", "（権限・仕事を）委任する",
         ("（役職や等級を）格下げする", "〜を遅らせる", "〜を審議する"),
         "delegate authority", "権限を委譲する", "名詞では「代表者」"),
        ("disclose", "動", "〜を開示する、暴露する",
         ("〜を閉鎖する", "〜を割り引く", "〜を処分する"),
         "disclose information", "情報を開示する", "名 disclosure"),
        ("enforce", "動", "（法を）施行する、強制的に守らせる",
         ("（制度・規則を）廃止する", "〜を強く勧める", "〜を一時停止する"),
         "enforce the law", "法を執行する", "名 enforcement。★ reinforce（補強する）と区別"),
        ("induce", "動", "〜する気にさせる、〜を引き起こす",
         ("〜を演繹する", "〜を導入する", "〜を減らす"),
         "induce him to sign the contract", "彼に契約する気を起こさせる",
         "induce A to do＝Aに〜する気を起こさせる。★ introduce と混同注意"),
        ("prohibit", "動", "〜を禁止する",
         ("〜を促進する", "〜を予言する", "〜を保護する"),
         "prohibit smoking", "喫煙を禁止する", "prohibit A from -ing"),
        ("replicate", "動", "〜を複製する、再現する",
         ("〜に返答する", "〜を交換する", "〜を否定する"),
         "replicate the results", "実験結果を再現する", "名 replication"),
        ("revoke", "動", "〜を取り消す、無効にする",
         ("〜を回す", "〜を復活させる", "〜を思い出す"),
         "revoke a license", "免許を取り消す", "★ recall（呼び戻す）と区別。名 revocation"),
        ("apprehension", "名", "不安、懸念",
         ("見習い期間", "称賛", "適性"),
         "with apprehension", "不安を抱いて", "形 apprehensive（心配して）"),
        ("bias", "名", "偏見、先入観",
         ("双方向性", "概略", "買収工作"),
         "a gender bias", "性別による偏見", "biased＝偏った"),
        ("commodity", "名", "商品、日用品",
         ("共同体", "委員会", "快適"),
         "a valuable commodity", "価値のある商品", "経済では「一次産品」"),
        ("negligence", "名", "怠慢、過失",
         ("交渉", "近隣地域", "全面否定"),
         "gross negligence", "重大な過失", "形 negligent"),
        ("skepticism", "名", "懐疑、疑う気持ち",
         ("確信", "専門知識", "見取り図"),
         "with skepticism", "懐疑的に", "形 skeptical"),
        ("upheaval", "名", "大変動、激変",
         ("上昇", "現状維持", "隆起した丘"),
         "social upheaval", "社会の大変動", "heave＝持ち上げる"),
        ("fall through", "熟", "（計画・取引が）だめになる、頓挫する",
         ("（トンネルなどを）通り抜ける", "〜に恋をする", "徹底的に調べ上げる"),
         "The deal fell through.", "その商談は流れた", "⇔ go through（成立する）"),
        ("gloss over", "熟", "〜を取り繕う、都合の悪い点をごまかす",
         ("〜を見渡す", "〜につやを出す", "〜に注釈する"),
         "gloss over the problem", "問題をうやむやにする", "表面をつやつやにして隠すイメージ"),
        ("pin down", "熟", "（原因などを）特定する、突き止める",
         ("〜をピンで留めて飾る", "（虫や紙を）押しつぶす", "〜を書き留める"),
         "pin down the cause", "原因を突き止める", "人に対しては「言質を取る」"),
        ("usher in", "熟", "〜の到来を告げる、〜の先駆けとなる",
         ("〜を締め出す", "（客を）静かに退場させる", "〜を急き立てる"),
         "usher in a new era", "新時代の幕開けとなる", "usher＝案内係"),
    ]},
    # ============================== 第8回 ==============================
    {"no": 8, "title": "心情・態度を表す語", "items": [
        ("alienate", "動", "〜を疎外する、〜の心を遠ざける",
         ("〜を強く励ます", "〜と手を結ばせる", "〜の負担を軽くする"),
         "alienate voters", "有権者の心を離れさせる", "alien＝よそ者"),
        ("ascertain", "動", "〜を確かめる、突き止める",
         ("〜を上げる", "〜のせいにする", "〜を断言する"),
         "ascertain the facts", "事実を確認する", "certain が入っている＝確かにする。推測ではなく確認すること"),
        ("condone", "動", "〜を大目に見る、黙認する",
         ("〜を厳しく罰する", "〜を凝縮する", "〜に条件をつける"),
         "condone violence", "暴力を黙認する", "見て見ぬふりをして許すこと。approve（積極的に賛成する）とは違う"),
        ("deem", "動", "〜だとみなす、考える",
         ("〜を言いふらす", "〜を深める", "〜を軽んじる"),
         "deem it necessary", "それを必要だとみなす", "≒ consider（かたい語）"),
        ("emulate", "動", "〜を見習う、手本にして張り合う",
         ("〜を包む", "〜を乳化させる", "〜をからかう"),
         "emulate a role model", "手本となる人を見習う", "良い意味の「まねる」"),
        ("instill", "動", "（考え・感情を）徐々に植え付ける",
         ("（酒や水を）蒸留する", "〜を設置する", "〜を静止させる"),
         "instill confidence in students", "生徒に自信を植え付ける", "★ install（設置する）と混同注意"),
        ("relinquish", "動", "〜を（しぶしぶ）手放す、放棄する",
         ("（家具などを）磨き直す", "〜を強く要求する", "〜を消し去る"),
         "relinquish control", "支配権を手放す", "≒ give up（かたい語）"),
        ("resent", "動", "〜に憤慨する、〜を不快に思う",
         ("〜を再送する", "〜を提示する", "〜に快く同意する"),
         "resent the criticism", "その批判に腹を立てる", "名 resentment"),
        ("sustain", "動", "〜を維持する／（損害を）受ける",
         ("〜を停止させる／中断する", "〜を染色する", "〜を仮定する"),
         "sustain economic growth", "経済成長を維持する", "sustain injuries＝負傷する"),
        ("wane", "動", "衰える、次第に弱まる",
         ("待ち構える", "強く警告する", "さまよう"),
         "Interest in the topic waned.", "その話題への関心が薄れた", "⇔ wax（満ちる）"),
        ("adversity", "名", "逆境、苦難",
         ("多様", "広告宣伝", "有益な助言"),
         "overcome adversity", "逆境を乗り越える", "形 adverse"),
        ("allegation", "名", "（証拠のない）申し立て、疑惑",
         ("（主君や国への）忠誠", "たとえ話", "言い伝え"),
         "deny the allegations", "疑惑を否定する", "証拠が固まる前の申し立て。事実と確定していない含みがある"),
        ("deterrent", "名", "抑止力、思いとどまらせるもの",
         ("粉末状の洗剤", "決定的な要因", "品質の劣化"),
         "a nuclear deterrent", "核抑止力", "動 deter"),
        ("downturn", "名", "（景気の）低迷、悪化",
         ("（歴史の）転換点", "頭金", "縮小版"),
         "an economic downturn", "景気後退", "⇔ upturn"),
        ("quota", "名", "割当、ノルマ",
         ("引用", "割り算の商", "市場の相場"),
         "meet the quota", "ノルマを達成する", "★ quote（引用）と区別"),
        ("testimony", "名", "証言、（〜を示す）証拠",
         ("遺言", "反対尋問", "陪審の評決"),
         "give testimony in court", "法廷で証言を行う", "法廷で証人が述べる内容。書面ではなく口頭で述べたものを指す"),
        ("bank on", "熟", "〜を当てにする、頼りにする",
         ("〜を銀行に預ける", "〜に賭けて負ける", "〜のふちに寄せる"),
         "bank on his support", "彼の支持を当てにする", "≒ count on"),
        ("lash out at", "熟", "〜を激しく非難する、〜に食ってかかる",
         ("〜をひもで縛りつける", "〜をむちで打って追い出す", "〜を期限で締め切る"),
         "lash out at critics", "批判する人々を激しく攻撃する", "lash＝むちで打つ"),
        ("mull over", "熟", "〜をじっくり考える",
         ("〜を台無しにする", "〜を粉にする", "〜を蒸し返す"),
         "mull over the offer", "その申し出をよく考える", "≒ ponder"),
        ("ramp up", "熟", "〜を増強する、拡大する",
         ("〜をやめる", "〜を暴走させる", "〜を巻き上げる"),
         "ramp up production", "生産を増強する", "⇔ wind down（縮小する）"),
    ]},
    # ============================== 第9回 ==============================
    {"no": 9, "title": "説明文・資料で出る語", "items": [
        ("augment", "動", "〜を増大させる、増強する",
         ("〜を論じ合う", "〜を縮小する", "〜を組み立てる"),
         "augment one's income", "収入を増やす", "AR＝augmented reality（拡張現実）"),
        ("compile", "動", "（資料を集めて）〜をまとめる、編集する",
         ("〜を積み上げて崩す", "（同意や自白を）強要する", "〜を最後までやり遂げる"),
         "compile a report", "報告書をまとめる", "名 compilation"),
        ("depict", "動", "〜を描写する、表現する",
         ("〜を切り取って捨てる", "〜を選び出す", "〜を強く非難する"),
         "depict rural life", "田舎の暮らしを描く", "名 depiction"),
        ("designate", "動", "〜を指定する、任命する",
         ("〜を辞任させる", "（計画を）白紙に戻す", "〜を軽視する"),
         "a designated area", "指定された区域", "★ design とは別語。名 designation"),
        ("impose", "動", "（税・負担を）課す、押し付ける",
         ("（秘密や悩みを）打ち明ける", "〜を構成する", "〜に反対する"),
         "impose a tax on imports", "輸入品に税を課す", "impose A on B"),
        ("outweigh", "動", "〜に勝る、〜より重要である",
         ("〜を追う", "〜より劣る", "〜を量り直す"),
         "The benefits outweigh the risks.", "利点がリスクを上回る", "out-（勝る）+ weigh"),
        ("penalize", "動", "〜を罰する、〜に不利益を与える",
         ("〜を貫通する", "〜を審理にかける", "〜に報いる"),
         "penalize offenders", "違反者を罰する", "名 penalty"),
        ("subsidize", "動", "〜に補助金を出す",
         ("〜を沈下させる", "〜の代用品を使う", "〜を細かく分割する"),
         "subsidize farmers", "農家に補助金を出す", "名 subsidy"),
        ("validate", "動", "〜の正しさを裏づける、有効にする",
         ("〜に価格をつける", "〜を無効にする", "〜を歓迎する"),
         "validate the theory", "その理論の正しさを裏づける", "⇔ invalidate"),
        ("yield", "動", "〜を産出する／（圧力に）屈する",
         ("〜を大声で叫ぶ／わめく", "〜を溶接する", "〜を強く望む"),
         "yield good results", "良い成果を生む", "名詞では「収穫量・利回り」"),
        ("implication", "名", "（予想される）影響、波及効果",
         ("（言葉を尽くした）明示的な説明", "複製物", "実地への応用"),
         "policy implications", "政策上の含意", "はっきり言われていないが読み取れること。複数形で影響・波及"),
        ("infrastructure", "名", "社会基盤、インフラ",
         ("上部構造", "下請け業者", "建物の内部構造"),
         "aging infrastructure", "老朽化したインフラ", "infra-＝下部の"),
        ("integrity", "名", "誠実さ、高潔／完全な状態",
         ("統合作業", "高い知性", "物理的な強度"),
         "a person of integrity", "高潔な人物", "データの「完全性」の意味でも使う"),
        ("peril", "名", "（重大な）危険",
         ("（貝から採れる）真珠", "一定の期間", "正式な許可"),
         "in grave peril", "重大な危機に瀕して", "形 perilous"),
        ("remnant", "名", "残り、名残",
         ("送金", "記念品", "修繕作業"),
         "remnants of the past", "過去の名残", "通例複数形"),
        ("stagnation", "名", "停滞、不振",
         ("隔離", "段階を追った発展", "（水位や気温の）急上昇"),
         "economic stagnation", "経済の停滞", "動 stagnate"),
        ("dwell on", "熟", "〜をくよくよ考える、長々と論じる",
         ("〜に住み着く", "〜を深く掘り下げて掘る", "〜を膨らませる"),
         "dwell on the past", "過去にこだわり続ける", "dwell 単独は「住む」"),
        ("fend off", "熟", "〜をかわす、撃退する",
         ("〜を囲う", "〜を仕上げる", "〜をあてがう"),
         "fend off criticism", "批判をかわす", "fend for oneself＝自活する"),
        ("sift through", "熟", "〜をふるいにかけて調べる、精査する",
         ("〜をすり抜ける", "〜を移し替える", "〜をこぼして失う"),
         "sift through the data", "データを丹念に調べる", "sift＝ふるいにかける"),
        ("wind up doing", "熟", "結局〜することになる",
         ("〜する寸前でやめる", "〜するよう説得される", "〜し慣れている"),
         "wind up paying more", "結局よけいに払うはめになる", "≒ end up doing"),
    ]},
    # ============================== 第10回 ==============================
    {"no": 10, "title": "抽象度の高い形容詞・熟語", "items": [
        ("articulate", "動", "〜を明確に述べる",
         ("〜を人工的に作り出す", "〜をあえてぼかす", "〜を丸暗記する"),
         "articulate a vision", "構想を明確に語る", "形容詞では「弁の立つ」"),
        ("constitute", "動", "〜を構成する、〜に相当する",
         ("〜を中断する", "〜の代用となる", "〜を制限する"),
         "Twelve members constitute the committee.", "12名の委員がその委員会を構成している",
         "名 constitution"),
        ("cultivate", "動", "（関係・能力を）育む／〜を耕す",
         ("〜を切り倒す／伐採する", "〜を強く非難する", "〜を暗記する"),
         "cultivate relationships", "人間関係を育む", "名 cultivation"),
        ("lure", "動", "〜を誘い込む、おびき寄せる",
         ("〜を追い払う", "〜を待ち伏せする", "〜をだまし取る"),
         "lure customers with discounts", "割引で客を引き寄せる", "名詞では「誘惑・おとり」"),
        ("perceive", "動", "〜を知覚する、〜だと捉える",
         ("〜を追い求める", "〜を保存する", "〜に耐え抜く"),
         "perceive it as a threat", "それを脅威と捉える", "名 perception／perceive A as B＝AをBだと捉える"),
        ("supplement", "動", "〜を補う、補足する",
         ("〜を頼む", "〜を交換する", "〜を単純化する"),
         "supplement one's income", "収入を補う", "名詞では「補足・栄養補助食品」"),
        ("terminate", "動", "〜を終了させる、打ち切る",
         ("〜を要約する", "〜に条件をつける", "〜を最終決定する"),
         "terminate a contract", "契約を打ち切る", "名 termination"),
        ("abundant", "形", "豊富な、大量にある",
         ("乏しい", "突発的な", "見捨てられた"),
         "abundant natural resources", "豊富な天然資源", "名 abundance"),
        ("conducive", "形", "（良い結果に）つながる、資する",
         ("（金属などが）電気を通しやすい", "誘導しやすい", "結論を示す"),
         "conducive to learning", "学習に資する", "conducive to が定型"),
        ("formidable", "形", "手ごわい、恐るべき",
         ("形を変えやすい", "好意的な", "その場限りの"),
         "a formidable opponent", "手ごわい相手", "圧倒されるほど強い、の含み"),
        ("impartial", "形", "公平な、偏らない",
         ("偏った", "不完全な", "無関心な"),
         "an impartial judge", "公平な裁判官", "⇔ partial（えこひいきする）"),
        ("lenient", "形", "寛大な、処分が甘い",
         ("けちな", "斜めに傾いた", "終始一貫した"),
         "a lenient sentence", "軽い判決", "⇔ strict, severe"),
        ("mundane", "形", "平凡な、ありふれた",
         ("月曜の", "世界的な", "気前のよい"),
         "mundane tasks", "平凡な雑務", "≒ ordinary, routine"),
        ("negligible", "形", "無視できるほど小さい",
         ("職務怠慢な", "交渉の余地がある", "判読できない"),
         "a negligible amount", "無視できるほどの量", "★ negligent（怠慢な）と区別"),
        ("sporadic", "形", "散発的な、時おり起こる",
         ("胞子の", "素早い", "連続的な"),
         "sporadic outbreaks", "散発的な発生", "副 sporadically"),
        ("stringent", "形", "（規則が）厳しい、厳格な",
         ("（分量が）おおざっぱな", "強い刺激のある", "弦楽器を使った"),
         "stringent regulations", "厳しい規制", "≒ strict, rigorous"),
        ("at the expense of", "熟", "〜を犠牲にして、〜の負担で",
         ("〜のおかげで", "〜に応じて", "〜を見越して"),
         "growth at the expense of the environment", "環境を犠牲にした成長", "expense＝代償・費用"),
        ("in tandem with", "熟", "〜と連携して、〜と並行して",
         ("〜とは対照的に", "〜の代わりに", "〜に反して"),
         "work in tandem with the police", "警察と連携して動く", "tandem＝縦一列"),
        ("on a par with", "熟", "〜と同等で、〜に匹敵して",
         ("〜に次いで", "〜より劣って", "〜より優れて"),
         "on a par with the world's best", "世界最高水準に匹敵して",
         "par＝標準・基準。★辞書の見出しは on a par with（冠詞 a が入る）"),
        ("jump the gun", "熟", "早まったことをする、フライングする",
         ("銃を飛び越える", "わざとやり過ごす", "引き金を引く"),
         "Don't jump the gun.", "先走るな", "陸上競技のフライングから"),
    ]},
    # ============================== 第11回 ==============================
    {"no": 11, "title": "変化・増減を表す動詞", "items": [
        ("diminish", "動", "減少する、〜を減らす",
         ("膨張する", "停滞する", "分散する"),
         "diminish over time", "時とともに減少する",
         "名 diminution／自動詞・他動詞の両方で使う"),
        ("escalate", "動", "次第に激化する、エスカレートする",
         ("徐々に沈静する", "一定に保たれる", "急に途切れる"),
         "Tensions escalated rapidly.", "緊張が急速に激化した",
         "⇔ de-escalate（沈静化させる）"),
        ("fluctuate", "動", "変動する、上下に揺れる",
         ("収束する", "均衡する", "硬直する"),
         "Prices fluctuate daily.", "価格は日々変動する",
         "名 fluctuation。上下の反復がある動き"),
        ("plummet", "動", "急落する、真っ逆さまに落ちる",
         ("急騰する", "反転する", "浮上する"),
         "Sales plummeted last year.", "売上が昨年急落した",
         "≒ plunge, nosedive。数値の暴落に使う"),
        ("soar", "動", "急上昇する、舞い上がる",
         ("急降下する", "横ばいが続く", "徐々に鈍る"),
         "Prices soared overnight.", "価格が一夜で急上昇した",
         "物価・気温・鳥のどれにも使う"),
        ("amplify", "動", "〜を増幅する、〜を大きくする",
         ("〜を要約する", "〜を分類する", "〜を模倣する"),
         "amplify the signal", "信号を増幅する",
         "amp（アンプ）と同語源。名 amplification"),
        ("intensify", "動", "〜を強める、いっそう強まる",
         ("〜を薄める", "〜を早める", "〜を控える"),
         "intensify the pressure", "圧力を強める",
         "形 intense／名 intensity"),
        ("subside", "動", "おさまる、静まる",
         ("ぶり返す", "こみ上げる", "行き渡る"),
         "The storm subsided.", "嵐がおさまった",
         "痛み・怒り・嵐など高ぶったものが引くとき"),
        ("magnify", "動", "〜を拡大する、〜を大きく見せる",
         ("〜を分割する", "〜を測定する", "〜を固定する"),
         "magnify the image", "画像を拡大する",
         "名 magnification（拡大）。magnitude は同じ magnus 由来の別語で派生形ではない"),
        ("stabilize", "動", "〜を安定させる、安定する",
         ("〜を細分化する", "〜を移転させる", "〜を凍結する"),
         "stabilize the economy", "経済を安定させる",
         "形 stable／名 stability"),
        ("proliferate", "動", "急激に増える、拡散する",
         ("徐々に絶える", "偶然に生じる", "一部に留まる"),
         "proliferate rapidly", "急激に増える",
         "名 proliferation。数が増えて広がる含み"),
        ("erode", "動", "〜を侵食する、少しずつ弱める",
         ("〜を清算する", "〜を包囲する", "〜を分配する"),
         "erode public trust", "国民の信頼を侵食する",
         "名 erosion。地形にも信頼にも使う"),
        ("surpass", "動", "〜をしのぐ、上回る",
         ("〜に見合う", "〜に逆らう", "〜を代表する"),
         "surpass expectations", "予想をしのぐ",
         "sur-（越えて）+ pass。≒ outdo"),
        ("exceed", "動", "〜を超える、〜を超過する",
         ("〜を満たす", "〜を見送る", "〜を占める"),
         "exceed the speed limit", "制限速度を超える",
         "名 excess／形 excessive"),
        ("curtail", "動", "〜を切り詰める、短縮する",
         ("〜を持ち越す", "〜を積み増す", "〜を引き延ばす"),
         "curtail spending", "支出を切り詰める",
         "curt（短い）から。tail の綴りは後世の影響。期間・費用の両方に使う"),
        ("swell", "動", "膨れ上がる、増大する",
         ("しぼんでいく", "固まってくる", "傾いていく"),
         "The crowd swelled.", "群衆が膨れ上がった",
         "過去分詞 swollen。名詞で「うねり」"),
        ("taper off", "熟", "少しずつ減っていく、先細りになる",
         ("一気に噴き出す", "元の水準に戻る", "そのまま続いていく"),
         "The rain tapered off.", "雨が少しずつ弱まっていった",
         "taper＝先細りの形。勢いが細っていく"),
        ("level off", "熟", "横ばいになる、水平に近づく",
         ("上下に揺れ動く", "一段と伸びる", "がくんと下がる"),
         "Sales leveled off.", "売上が横ばいになった",
         "≒ plateau。off は動きが止まる感じ"),
        ("fall short of", "熟", "〜に届かない、〜に達しない",
         ("〜を果たす", "〜にちょうど並ぶ", "〜を先に済ませる"),
         "fall short of expectations", "期待に届かない",
         "short of＝〜に足りない状態"),
        ("give rise to", "熟", "〜を生じさせる、〜のもとになる",
         ("〜を未然に防ぐ", "〜から派生する", "〜を打ち消す"),
         "give rise to controversy", "論争を生じさせる",
         "rise＝生じる。原因の側が主語に立つ"),
    ]},
    # ============================== 第12回 ==============================
    {"no": 12, "title": "主張・判断を表す動詞", "items": [
        ("assert", "動", "〜を断言する、言い張る",
         ("〜を聞き流す", "〜を書き留める", "〜を割り引く"),
         "assert one's innocence", "自らの潔白を断言する",
         "名 assertion。証拠を示さずに言い切る含み"),
        ("allege", "動", "〜だと申し立てる、〜だと言い張る",
         ("〜だと聞き返す", "〜だと請け合う", "〜だと打ち明ける"),
         "allege misconduct", "不正行為があったと申し立てる",
         "副 allegedly（〜とされている）。証拠は未確定"),
        ("affirm", "動", "〜を肯定する、〜が正しいと認める",
         ("〜を保留する", "〜を委任する", "〜を否認する"),
         "affirm the decision", "その決定を肯定する",
         "⇔ deny。名 affirmation"),
        ("concede", "動", "〜をしぶしぶ認める、〜を譲る",
         ("〜をきっぱり断る", "〜をあっさり忘れる", "〜をこっそり進める"),
         "concede defeat", "敗北をしぶしぶ認める",
         "名 concession（譲歩・売店）"),
        ("dispute", "動", "〜に異議を唱える、〜を争う",
         ("〜をそのまま伝える", "〜を静かに見守る", "〜をひそかに望む"),
         "dispute the claim", "その主張に異議を唱える",
         "名詞で「論争」。a labor dispute＝労働争議"),
        ("infer", "動", "〜を推論する、〜と推し量る",
         ("〜を暗記する", "〜を歓迎する", "〜を宣伝する"),
         "infer the meaning from context", "文脈から意味を推論する",
         "受け手が読み取る側の行為"),
        ("deduce", "動", "〜を導き出す、演繹する",
         ("〜を書き換える", "〜を取り下げる", "〜を裏づける"),
         "deduce the answer from the clues", "手がかりから答えを導き出す",
         "名 deduction。一般則から個別の結論へ"),
        ("imply", "動", "〜をほのめかす、それとなく示す",
         ("〜を言いふらす", "〜を問いただす", "〜を書き添える"),
         "imply criticism", "批判をほのめかす",
         "話し手・書き手の側の行為"),
        ("justify", "動", "〜を正当化する、〜の根拠を示す",
         ("〜を訂正する", "〜を代弁する", "〜を規制する"),
         "justify the decision", "その決定を正当化する",
         "名 justification。形 justifiable"),
        ("acknowledge", "動", "〜を認める、〜を認知する",
         ("〜を訴える", "〜を書き足す", "〜を思い出す"),
         "acknowledge the mistake", "誤りを認める",
         "「受領を知らせる」意味もある。名 acknowledgment"),
        ("dismiss", "動", "〜を却下する、〜を解雇する",
         ("〜を持ち出す", "〜を数え直す", "〜を書き写す"),
         "dismiss the idea", "その考えを却下する",
         "名 dismissal。授業を「解散させる」意味も"),
        ("uphold", "動", "〜を堅持する、〜を守り抜く",
         ("〜を撤回する", "〜を模索する", "〜を発注する"),
         "uphold traditional values", "伝統的な価値観を堅持する",
         "hold up（下から支える）から。⇔ overturn"),
        ("condemn", "動", "〜を強く非難する、〜に有罪判決を下す",
         ("〜を高く評価する", "〜を細かく分ける", "〜を大幅に見直す"),
         "condemn the attack", "その攻撃を強く非難する",
         "建物に「使用禁止を宣告する」意味もある"),
        ("proclaim", "動", "〜を公に宣言する、〜を宣告する",
         ("〜を内々に伝える", "〜を後回しにする", "〜を小声でつぶやく"),
         "proclaim independence", "独立を公に宣言する",
         "名 proclamation。国家的な布告に使う"),
        ("testify", "動", "証言する、〜を証明する",
         ("同席する", "傍聴する", "起訴する"),
         "testify in court", "法廷で証言する",
         "testimony と同語源で testis＝証人。名詞 test（試験）とは別語源。testify to＝〜の証拠となる"),
        ("contradict", "動", "〜と矛盾する、〜に反論する",
         ("〜と併存する", "〜に追随する", "〜を引用する"),
         "contradict the evidence", "証拠と矛盾する",
         "名 contradiction。self-contradictory＝自己矛盾の"),
        ("stand by", "熟", "〜を支持し続ける、待機する",
         ("〜から手を引く", "〜のそばを通る", "〜を横取りする"),
         "stand by one's decision", "自分の決定を支持し続ける",
         "人を目的語にすると「見捨てずにいる」"),
        ("stand for", "熟", "〜の略語である、〜を象徴する",
         ("〜の続きである", "〜の写しである", "〜の見本である"),
         "UN stands for the United Nations.", "UN は United Nations の略語である",
         "否定文では「〜を我慢する」"),
        ("back down", "熟", "自説を引っ込める、譲る",
         ("主張を押し通す", "反論を書き並べる", "議論を長引かせる"),
         "refuse to back down", "自説を引っ込めようとしない",
         "喧嘩や交渉で後退する。⇔ stand firm"),
        ("go along with", "熟", "〜に同調する、〜に賛成する",
         ("〜に先回りする", "〜に立ち会う", "〜を言い直す"),
         "go along with the plan", "その計画に同調する",
         "積極的な賛成というより「合わせる」含み"),
    ]},
    # ============================== 第13回 ==============================
    {"no": 13, "title": "対処・実行を表す動詞", "items": [
        ("tackle", "動", "〜に取り組む、（難題に）立ち向かう",
         ("〜を放棄する", "〜を先送りする", "〜を黙認する"),
         "tackle the housing shortage", "住宅不足に取り組む",
         "名詞ではラグビーなどのタックル。難題に正面から当たる含み"),
        ("cope", "動", "何とか対処する、切り抜ける",
         ("強引に押し通す", "途中で投げ出す", "他人任せにする"),
         "cope with stress", "ストレスに何とか対処する",
         "自動詞。cope with の形で使う"),
        ("execute", "動", "〜を遂行する、やり遂げる",
         ("〜を延期する", "〜を委任する", "〜を検証する"),
         "execute a plan", "計画を遂行する",
         "名 execution。「死刑を執行する」の意味もある"),
        ("administer", "動", "〜を管理運営する、（薬を）投与する",
         ("〜を外部に託す", "〜を大幅に削る", "〜を独占する"),
         "administer the fund", "基金を管理運営する",
         "名 administration。医療では「投与する」"),
        ("oversee", "動", "〜を統括する、（全体を）見渡す",
         ("〜を見落とす", "〜を代行する", "〜を打診する"),
         "oversee the project", "事業を統括する",
         "★ overlook（見落とす）と混同注意。上から全体を見る側"),
        ("supervise", "動", "〜を監督する、（作業を）見守る",
         ("〜を採点する", "〜を扇動する", "〜を弁護する"),
         "supervise the staff", "職員を監督する",
         "名 supervisor（監督者）／supervision"),
        ("coordinate", "動", "〜を調整する、（連携を）取りまとめる",
         ("〜を分担する", "〜を模倣する", "〜を撤回する"),
         "coordinate the relief effort", "救援活動を調整する",
         "co-（共に）+ ordinate（並べる）。名 coordination"),
        ("devise", "動", "〜を考案する、工夫して作り出す",
         ("〜を廃止する", "〜を暗記する", "〜を負担する"),
         "devise a new method", "新しい方法を考案する",
         "★ 名詞 device（装置）と品詞で区別"),
        ("formulate", "動", "〜を練り上げる、（考えを）明確に述べる",
         ("〜を書き換える", "〜を数え上げる", "〜を締めくくる"),
         "formulate a policy", "方針を練り上げる",
         "formula（公式）から。名 formulation"),
        ("commence", "動", "開始する、（式などが）始まる",
         ("延期になる", "休会にする", "途中で抜ける"),
         "commence operations", "業務を開始する",
         "改まった語。名 commencement（開始・卒業式）"),
        ("pursue", "動", "〜を追求する、（学業を）続ける",
         ("〜を断念する", "〜を暴露する", "〜を賞賛する"),
         "pursue a goal", "目標を追求する",
         "名 pursuit。「〜を追いかける」の意味もある"),
        ("consolidate", "動", "〜を統合する、（地位を）強固にする",
         ("〜を統制する", "〜を凍結する", "〜を公表する"),
         "consolidate the two divisions", "2つの部門を統合する",
         "solid（固い）から。名 consolidation"),
        ("prioritize", "動", "〜を優先する、優先順位をつける",
         ("〜を保留する", "〜を試算する", "〜を委託する"),
         "prioritize safety", "安全を優先する",
         "名 priority。英つづりは prioritise"),
        ("mobilize", "動", "〜を動員する、（資源を）結集する",
         ("〜を解散させる", "〜を封鎖する", "〜を分配する"),
         "mobilize volunteers", "ボランティアを動員する",
         "mobile（動かせる）から。名 mobilization"),
        ("orchestrate", "動", "〜を画策する、（周到に）取り仕切る",
         ("〜を中傷する", "〜を伝授する", "〜を黙殺する"),
         "orchestrate a protest campaign", "抗議運動を画策する",
         "orchestra の指揮から。裏で周到に仕組む含み"),
        ("expedite", "動", "〜を迅速に進める、（手続きを）早める",
         ("〜を慎重に見送る", "〜を厳重に封じる", "〜を丁重に断る"),
         "expedite the process", "手続きを迅速に進める",
         "ex-（外へ）+ ped（足）。形 expedited（迅速処理の）"),
        ("follow through on", "熟", "〜をやり遂げる、最後までやり通す",
         ("〜を後回しにする", "〜を引き継ぐ", "〜に追従する"),
         "follow through on the promise", "約束を最後までやり遂げる",
         "through＝最後まで。やりかけたことを途中で放り出さない含み"),
        ("work out", "熟", "うまくいく、（数値を）算出する",
         ("行き詰まる", "からまわりする", "先送りになる"),
         "The plan worked out well.", "その計画はうまくいった",
         "「体を鍛える」「答えを出す」の意味もある"),
        ("set out", "熟", "着手する、（旅に）出発する",
         ("撤収する", "同席する", "留任する"),
         "set out to reform the system", "制度の改革に着手する",
         "set out to do＝〜しようと乗り出す"),
        ("take on", "熟", "〜を自ら引き受ける、（仕事を）背負い込む",
         ("〜を人に丸投げする", "〜を後任に譲る", "〜を言い当てる"),
         "take on extra duties", "追加の職務を自ら引き受ける",
         "「人を雇う」「性質を帯びる」「強敵に挑む」の意味もある"),
    ]},
    # ============================== 第14回 ==============================
    {"no": 14, "title": "社会・制度の名詞", "items": [
        ("legislation", "名", "法律の制定、（制定された）法律",
         ("条例の廃止", "予算の執行", "判例の蓄積"),
         "pass new legislation", "新しい法律を制定する",
         "動 legislate。集合名詞で「法律（全体）」も指す"),
        ("jurisdiction", "名", "管轄権、（権限の及ぶ）区域",
         ("議決権", "拒否権", "所有権"),
         "fall under federal jurisdiction", "連邦の管轄権に属する",
         "juris（法）+ diction（言うこと）"),
        ("mandate", "名", "委任、（有権者からの）負託",
         ("請願", "答申", "罷免"),
         "a clear mandate from voters", "有権者からの明確な委任",
         "動詞で「〜を義務づける」。形 mandatory"),
        ("referendum", "名", "国民投票、住民投票",
         ("行政訴訟", "投票率", "臨時国会"),
         "hold a referendum", "国民投票を行う",
         "refer（委ねる）から。複数形は referendums / referenda"),
        ("regime", "名", "統治体制、（特定の）政権",
         ("外交方針", "報道規制", "納税義務"),
         "under the old regime", "旧統治体制の下で",
         "発音は「レイジーム」。批判的な響きを伴うことが多い"),
        ("bureaucracy", "名", "官僚制、（形式ばった）お役所仕事",
         ("共和制", "多数決", "議事録"),
         "government bureaucracy", "政府の官僚制",
         "bureau（局）+ -cracy（支配）。名 bureaucrat"),
        ("autonomy", "名", "自治、（個人の）自律",
         ("併合", "介入", "駐留"),
         "grant regional autonomy", "地域に自治を認める",
         "auto（自ら）+ nomy（法）。形 autonomous"),
        ("sovereignty", "名", "主権、（国家の）統治権",
         ("領土", "国籍", "同盟"),
         "national sovereignty", "国家の主権",
         "形 sovereign（主権を持つ／君主）"),
        ("treaty", "名", "条約、（国家間の）取り決め",
         ("条例", "批准", "領海"),
         "sign a peace treaty", "平和条約に調印する",
         "treat（扱う）から。国家間の正式な合意にのみ使う"),
        ("coalition", "名", "連立、（複数勢力の）連合",
         ("棄権", "亡命", "解散"),
         "form a coalition", "連立を組む",
         "a coalition government＝連立政権"),
        ("statute", "名", "成文法、法令",
         ("慣習法", "判例集", "自然法"),
         "a state statute", "州の成文法",
         "形 statutory（法定の）。文書として定められた法"),
        ("amendment", "名", "修正、（法案・憲法の）改正",
         ("施行", "公布", "廃案"),
         "propose an amendment", "修正を提案する",
         "動 amend。the First Amendment＝合衆国憲法修正第1条"),
        ("ballot", "名", "投票用紙、（無記名の）投票",
         ("選挙公報", "開票速報", "議席配分"),
         "cast a ballot", "投票用紙を投じる",
         "★ ballet（バレエ）とつづりが紛らわしい"),
        ("census", "名", "国勢調査、（人口の）全数調査",
         ("住民登録", "世論調査", "戸籍謄本"),
         "conduct a census", "国勢調査を行う",
         "抜き取りの意見調査ではなく、全人口を数える調査"),
        ("verdict", "名", "評決、（下された）判断",
         ("起訴", "控訴", "示談"),
         "reach a verdict", "評決に達する",
         "主に陪審が下す事実認定。裁判官が言い渡す刑は sentence"),
        ("welfare", "名", "福祉、（人々の）幸福",
         ("徴兵制度", "予防接種", "課税対象"),
         "the welfare of citizens", "市民の福祉",
         "米では「生活保護」の意（be on welfare）。a welfare state＝福祉国家"),
        ("in accordance with", "熟", "〜に従って、（規定に）のっとって",
         ("〜に反して", "〜を除いて", "〜に先立って"),
         "in accordance with the rules", "規則に従って",
         "according to は「〜によれば」が中心。こちらは規則・法に従う堅い語"),
        ("on behalf of", "熟", "〜を代表して、（人）の代わりに",
         ("〜と並行して", "〜に付随して", "〜に対抗して"),
         "speak on behalf of the group", "その団体を代表して発言する",
         "代理・代表の意。手紙や式辞の決まり文句として使う"),
        ("in the face of", "熟", "〜に直面して、（困難を）ものともせず",
         ("〜に先行して", "〜に便乗して", "〜を後ろ盾に"),
         "in the face of strong opposition", "強い反対に直面して",
         "困難・危険・批判など、望ましくないものとともに使う"),
        ("subject to", "熟", "〜を受けやすい、（承認を）条件として",
         ("〜を免れた", "〜に反対された", "〜と無関係な"),
         "subject to sudden change", "急な変更を受けやすい",
         "subject to approval＝承認を条件として"),
    ]},
    # ============================== 第15回 ==============================
    {"no": 15, "title": "思考・議論の名詞", "items": [
        ("premise", "名", "前提、論の出発点",
         ("結論", "反論", "要約"),
         "start from a false premise", "誤った前提から出発する",
         "複数形 premises は「建物・敷地」を指す別の意味"),
        ("hypothesis", "名", "仮説、検証すべき仮定",
         ("定説", "反証", "見込み"),
         "test a hypothesis", "仮説を検証する",
         "複数形 hypotheses。形 hypothetical（仮定の）"),
        ("paradigm", "名", "思考の枠組み、規範となる型",
         ("議論の手順", "知識の集大成", "対立する学説"),
         "a paradigm shift in medicine", "医学における思考の枠組みの転換",
         "paradigm shift＝ものの見方が根本から変わること"),
        ("notion", "名", "概念、漠然とした考え",
         ("通告", "動機", "反感"),
         "the notion of free will", "自由意志という概念",
         "≒ idea。はっきり形になっていない考えにも使う"),
        ("doctrine", "名", "教義、公式に掲げる原則",
         ("異端", "儀式", "布告"),
         "religious doctrine", "宗教の教義",
         "政治では国家の基本方針を指すこともある"),
        ("ideology", "名", "思想体系、政治的信条",
         ("理想郷", "観念論", "宣伝活動"),
         "political ideology", "政治的な思想体系",
         "形 ideological。集団が共有する考えの体系"),
        ("discourse", "名", "論説、改まった議論",
         ("独白", "口論", "風刺"),
         "academic discourse", "学術的な論説",
         "discourse on 〜＝〜についての論述"),
        ("rhetoric", "名", "修辞、巧みな言い回し",
         ("韻律", "暗唱", "論理"),
         "master the art of rhetoric", "修辞の技術を身につける",
         "形 rhetorical。rhetorical question＝答えを求めない問いかけ"),
        ("fallacy", "名", "誤った考え、論理の誤り",
         ("有力な学説", "一般の通念", "率直な感想"),
         "a common fallacy", "よくある誤った考え",
         "logical fallacy＝筋道の通らない議論"),
        ("analogy", "名", "類推、たとえによる説明",
         ("逸話", "対比", "暗示"),
         "reason by analogy", "類推によって考える",
         "形 analogous（似通った）"),
        ("connotation", "名", "言外の意味、言葉に伴う含み",
         ("語源の説明", "発音の変化", "文字どおりの語義"),
         "the negative connotations of the word", "その語が持つ否定的な含み",
         "辞書どおりの意味を指す語と対になる。良い含み・悪い含みの両方に使う"),
        ("conjecture", "名", "推測、確証のない見解",
         ("実証", "弁明", "合致"),
         "pure conjecture", "単なる推測",
         "動詞でも使う。根拠が弱いという含みがある"),
        ("paradox", "名", "逆説、矛盾するようで真である説",
         ("定理", "皮肉", "妥協"),
         "the paradox of choice", "選択肢が多いほど選べないという逆説",
         "形 paradoxical"),
        ("dilemma", "名", "板挟み、二者択一の窮地",
         ("打開策", "独断", "言い分"),
         "face a moral dilemma", "道徳上の板挟みに直面する",
         "どちらを選んでも不都合が残る状況を指す"),
        ("criterion", "名", "判断基準、評価のものさし",
         ("暫定合意", "多数意見", "最終期限"),
         "meet the criteria", "判断基準を満たす",
         "複数形 criteria。単数形と取り違えやすい"),
        ("perspective", "名", "視点、ものの見方",
         ("先入観", "思い込み", "無関心"),
         "from a different perspective", "別の視点から",
         "put ... in perspective＝全体の中で位置づける"),
        ("in light of", "熟", "〜を考慮して、〜をふまえて",
         ("〜に逆らって", "〜を軽んじて", "〜に先立って"),
         "in light of the new evidence", "新しい証拠を考慮して",
         "in the light of の形もある"),
        ("by virtue of", "熟", "〜のおかげで、〜という理由で",
         ("〜に反して", "〜と引き換えに", "〜をよそに"),
         "by virtue of his experience", "彼の経験のおかげで",
         "virtue＝長所。かたい書き言葉で使う"),
        ("in terms of", "熟", "〜の観点から、〜の面で",
         ("〜を通じて", "〜に加えて", "〜の代わりに"),
         "in terms of cost", "費用の観点から",
         "比べる側面を指定するときに使う"),
        ("with regard to", "熟", "〜に関して、〜については",
         ("〜と同時に", "〜を頼りに", "〜の直前に"),
         "with regard to your request", "あなたの依頼に関して",
         "regarding 1語でも同じ意味になる"),
    ]},
    # ============================== 第16回 ==============================
    {"no": 16, "title": "評価・程度の形容詞", "items": [
        ("substantial", "形", "相当な、規模が大きい",
         ("一時的な", "表面的な", "見せかけの"),
         "a substantial increase in sales", "売上の相当な増加",
         "動 substantiate（裏づける）は意味が別"),
        ("considerable", "形", "かなり多い、無視できない",
         ("型どおりの", "あいまいな", "たまにある"),
         "a considerable amount of time", "かなり多くの時間",
         "副 considerably。綴りの近い別語と取り違えやすい"),
        ("marginal", "形", "ごくわずかな、重要でない",
         ("並外れた", "気まぐれな", "見当違いの"),
         "a marginal improvement", "ごくわずかな改善",
         "margin＝余白。「欄外の・周辺の」の意味もある"),
        ("moderate", "形", "適度な、穏やかな",
         ("過激な", "無理な", "雑な"),
         "moderate exercise", "適度な運動",
         "動詞では「〜を和らげる」。副 moderately"),
        ("extensive", "形", "広範な、大規模な",
         ("集中的な", "短期間の", "試験的な"),
         "extensive research", "広範な研究",
         "extend（広げる）から。extensive damage＝広範囲の被害"),
        ("comprehensive", "形", "包括的な、全分野にわたる",
         ("入門的な", "専門的な", "実験的な"),
         "a comprehensive survey", "包括的な調査",
         "一部だけでなく全体をカバーする含み"),
        ("exhaustive", "形", "網羅的な、もれのない",
         ("一面的な", "疲れ果てた", "補足的な"),
         "an exhaustive list", "網羅的な一覧",
         "exhausted（疲れ切った）と混同注意"),
        ("thorough", "形", "徹底的な、入念な",
         ("形式的な", "事務的な", "手早い"),
         "a thorough investigation", "徹底的な調査",
         "副 thoroughly。through（〜を通って）と別語"),
        ("ample", "形", "十分な、あり余るほどの",
         ("精密な", "一律の", "不均等な"),
         "ample evidence", "十分な証拠",
         "時間・空間・量のどれにも使える"),
        ("meager", "形", "乏しい、貧弱な",
         ("型破りな", "不慣れな", "割高な"),
         "a meager income", "乏しい収入",
         "英つづり meagre。量が足りず貧しい含み"),
        ("sparse", "形", "まばらな、密度の低い",
         ("均質な", "不規則な", "入り組んだ"),
         "a sparse population", "まばらな人口",
         "副 sparsely。sparsely populated＝人口がまばらな"),
        ("widespread", "形", "広く見られる、行き渡った",
         ("目新しい", "うわさ話の", "言い伝えの"),
         "a widespread belief", "広く見られる考え",
         "spread（広がる）から。地域や人の範囲の広さを言う"),
        ("pervasive", "形", "浸透した、隅々に及ぶ",
         ("見過ごされた", "一時の", "行き詰まった"),
         "a pervasive influence", "広く浸透した影響",
         "動 pervade。好ましくないものに使うことが多い"),
        ("ubiquitous", "形", "至る所にある、遍在する",
         ("使い道の狭い", "持ち運べない", "値段の高い"),
         "ubiquitous smartphones", "至る所にあるスマートフォン",
         "ラテン語 ubique（どこでも）から"),
        ("staggering", "形", "驚異的な、途方もなく大きい",
         ("ありふれた", "見え透いた", "悲観的な"),
         "a staggering amount of money", "驚異的な額の金",
         "動 stagger（よろめく）から。数量の大きさに驚く含み"),
        ("modest", "形", "控えめな、大きくはない",
         ("派手な", "強引な", "気ままな"),
         "a modest increase", "控えめな増加",
         "量や規模が「大きくはない」と述べるときに使う"),
        ("boil down to", "熟", "結局〜に行き着く、要は〜だ",
         ("〜へ発展する", "〜から目をそらす", "〜を大げさに言う"),
         "It all boils down to money.", "結局はすべて金の問題に行き着く",
         "複雑な話の要点が1つに絞られる含み"),
        ("add up to", "熟", "合計〜になる、つまり〜を意味する",
         ("〜を上回る", "〜に付け加える", "〜から差し引く"),
         "The costs add up to $500.", "費用は合計500ドルになる",
         "add up だけなら「つじつまが合う」"),
        ("amount to", "熟", "〜に等しい、結果的に〜になる",
         ("〜に劣る", "〜を下回る", "〜と衝突する"),
         "The delay amounts to a breach of contract.", "その遅延は契約違反に等しい",
         "金額以外に「実質的に〜だ」と述べるのにも使う"),
        ("by and large", "熟", "概して、全体的に見て",
         ("まれに", "一つ残らず", "不本意ながら"),
         "By and large, the plan worked.", "概して計画はうまくいった",
         "文頭に置いて文全体を修飾することが多い"),
    ]},
    # ============================== 第17回 ==============================
    {"no": 17, "title": "性質・態度の形容詞", "items": [
        ("diligent", "形", "勤勉な、こつこつ努力する",
         ("軽率な", "大胆な", "無口な"),
         "a diligent student", "勤勉な学生",
         "副 diligently／名 diligence。地道に手を抜かない含み"),
        ("conscientious", "形", "良心的な、誠実で入念な",
         ("独創的な", "排他的な", "場当たり的な"),
         "a conscientious worker", "良心的でまじめに働く人",
         "conscience（良心）から。任された務めをきちんと果たす含み"),
        ("prudent", "形", "慎重な、思慮分別のある",
         ("強引な", "陽気な", "執拗な"),
         "a prudent decision", "慎重な判断",
         "名 prudence。危険を見越して先に手を打つ含み"),
        ("discreet", "形", "口が堅い、思慮深く控えめな",
         ("耳が早い", "腰が低い", "気が短い"),
         "be discreet about the matter", "その件については口が堅い",
         "名 discretion（分別）。綴りの近い別語と取り違えやすい"),
        ("candid", "形", "率直な、包み隠さない",
         ("軽薄な", "内気な", "陰気な"),
         "a candid opinion", "率直な意見",
         "名 candor。candid camera＝隠し撮り"),
        ("blunt", "形", "無遠慮な、ぶっきらぼうな",
         ("気の弱い", "愛想のよい", "如才のない"),
         "a blunt refusal", "無遠慮な断り方",
         "副 bluntly。刃物についてなら「切れ味が鈍い」"),
        ("assertive", "形", "自己主張の強い、はきはきと意見を言う",
         ("人当たりのよい", "後先を考えない", "打たれ強い"),
         "an assertive leader", "自己主張の強い指導者",
         "名 assertiveness。攻撃的にならずに要求を伝える態度"),
        ("arrogant", "形", "傲慢な、横柄な",
         ("内向的な", "実直な", "無頓着な"),
         "an arrogant attitude", "傲慢な態度",
         "名 arrogance。自分の力を過信して人を軽んじる含み"),
        ("humble", "形", "謙虚な、控えめな",
         ("頑丈な", "軽快な", "気長な"),
         "a humble attitude toward learning", "学ぶことに謙虚な姿勢",
         "動詞では「〜の思い上がりをくじく」。名 humility"),
        ("stubborn", "形", "頑として譲らない、頑固な",
         ("気が変わりやすい", "落ち着きはらった", "面倒見のよい"),
         "a stubborn refusal to compromise", "頑として妥協を拒むこと",
         "汚れなら「落ちにくい」。名 stubbornness"),
        ("adaptable", "形", "順応性のある、融通のきく",
         ("持久力のある", "独創性のある", "計画性のある"),
         "adaptable to change", "変化に順応できる",
         "動 adapt／名 adaptability。環境に合わせて自分を変えられる"),
        ("complacent", "形", "現状に甘んじた、自己満足の",
         ("気が休まらない", "口やかましい", "危機感の強い"),
         "become complacent about safety", "安全対策で現状に甘んじる",
         "名 complacency。うまくいっていると思い込んで手を緩めた状態"),
        ("indifferent", "形", "無関心な、どうでもよいと思っている",
         ("気難しい", "感傷的な", "うぬぼれた"),
         "indifferent to criticism", "批判に無関心で",
         "be indifferent to 〜 の形で使う。名 indifference"),
        ("reluctant", "形", "気が進まない、しぶしぶの",
         ("待ちきれない", "落ち着きのない", "物わかりのよい"),
         "reluctant to change", "変化に気が進まない",
         "副 reluctantly。be reluctant to do の形で使う"),
        ("cynical", "形", "冷笑的な、人の善意を信じない",
         ("楽天的な", "情熱的な", "内省的な"),
         "a cynical view of politics", "政治に対する冷笑的な見方",
         "名 cynicism。相手の動機を疑ってかかる態度"),
        ("ruthless", "形", "冷酷な、容赦のない",
         ("臆病な", "純朴な", "従順な"),
         "a ruthless dictator", "冷酷な独裁者",
         "ruth（哀れみ）+ less。名 ruthlessness"),
        ("look down on", "熟", "〜を軽蔑する、見下す",
         ("〜に付き添う", "〜を言いふらす", "〜の機嫌を取る"),
         "look down on manual work", "肉体労働を軽蔑する",
         "down が評価の低さを表す。相手を自分より下に置くイメージ"),
        ("look up to", "熟", "〜を尊敬する、手本とみなす",
         ("〜に取り入る", "〜を励ます", "〜を見張る"),
         "look up to one's mentor", "指導してくれる人を尊敬する",
         "≒ admire。人を上に見るイメージ"),
        ("put up with", "熟", "〜を辛抱する、我慢して受け入れる",
         ("〜を言い張る", "〜に泊まる", "〜を掲げる"),
         "put up with the noise", "騒音を辛抱する",
         "put up（掲げる・泊める）に with が付くと意味が変わる"),
        ("take after", "熟", "〜に似ている",
         ("〜を見送る", "〜の世話をする", "〜を横取りする"),
         "take after his father", "父親に似ている",
         "主に家族の外見や性格が似ているときに使う。進行形にしない"),
    ]},
    # ============================== 第18回 ==============================
    {"no": 18, "title": "紛らわしい形容詞・副詞", "items": [
        ("literal", "形", "文字どおりの、逐語的な",
         ("文学に通じた", "読み書きのできる", "言外の意味を含む"),
         "the literal meaning of a word", "語の文字どおりの意味",
         "副 literally。比喩ではなく字義どおりに、の意味"),
        ("discrete", "形", "互いに別個の、分離した",
         ("重なり合った", "絶えず変化する", "口が堅く慎重な"),
         "discrete categories", "互いに別個の区分",
         "数学・IT では「離散的な」。綴りの近い別語と取り違えやすい"),
        ("principal", "形", "最も重要な、主要な",
         ("型どおりの", "付随的な", "原則的な"),
         "the principal reason", "最も重要な理由",
         "名詞では「校長・元金」。同じ発音の別語と混同しやすい"),
        ("sensible", "形", "分別のある、賢明な",
         ("口の達者な", "敏感な", "上品な"),
         "a sensible decision", "分別のある決断",
         "sense（良識）から。「感じやすい」意味の似た語と混同注意"),
        ("economical", "形", "むだのない、費用のかからない",
         ("気前のよい", "豪華な", "割高な"),
         "an economical use of fuel", "むだのない燃料の使い方",
         "副 economically。お金や資源を節約する側の意味"),
        ("historic", "形", "歴史に残る、後世に語り継がれる",
         ("目立たない", "史実に基づく", "作り話に近い"),
         "a historic agreement", "歴史に残る合意",
         "「歴史上重要な」の意味。単に歴史に関する、という似た語と区別する"),
        ("continual", "形", "断続的な、何度も繰り返される",
         ("一時的な", "一斉に起こる", "思いがけない"),
         "continual interruptions", "断続的に繰り返される中断",
         "何度も起こって間が空く含み。ただし「途切れず続く」の意味で使う辞書もある"),
        ("respective", "形", "それぞれの、各自の",
         ("ありふれた", "敬意を払った", "世間体のよい"),
         "their respective roles", "それぞれの役割",
         "副 respectively（それぞれ）。敬意を表す意味の似た語と混同注意"),
        ("industrious", "形", "よく働く、勤勉な",
         ("産業界の", "手際のよい", "口数の多い"),
         "an industrious farmer", "よく働く農家",
         "名 industry には「勤勉」の意味もある。産業に関する似た語と区別"),
        ("considerate", "形", "思いやりのある、気配りができる",
         ("打ち解けにくい", "かなり多くの", "情に流される"),
         "considerate of other people's feelings", "他人の気持ちに思いやりがある",
         "動 consider から。量が多い意味の似た語と取り違えやすい"),
        ("comprehensible", "形", "理解できる、分かりやすい",
         ("回りくどい", "包括的な", "手厳しい"),
         "a comprehensible explanation", "理解できる説明",
         "動 comprehend（理解する）から。全体を覆う意味の似た語と混同注意"),
        ("momentous", "形", "重大な、後々まで影響を残す",
         ("退屈な", "無害な", "つかの間の"),
         "a momentous decision", "重大な決断",
         "moment には「重要さ」の意味がある。短い時間を表す似た語と区別"),
        ("alternate", "形", "交互の、1つおきの",
         ("同時の", "臨時の", "一様の"),
         "alternate periods of rain and sun", "雨と晴れが交互に来る時期",
         "動詞なら「交互に起こる」。米では「代わりの」の意味でも使う"),
        ("virtual", "形", "事実上の、仮想の",
         ("型破りの", "高潔な", "簡素な"),
         "a virtual monopoly", "事実上の独占",
         "副 virtually（ほぼ・事実上）。道徳的に優れた意味の似た語と区別"),
        ("nominal", "形", "名目上の、ごくわずかの",
         ("強制的な", "推薦された", "名の知れた"),
         "the nominal leader of the party", "その党の名目上の指導者",
         "name（名前）から。金額なら「ごくわずかな」"),
        ("apparent", "形", "明白な、見かけ上の",
         ("透明な", "内密の", "偶発的な"),
         "for no apparent reason", "明白な理由もなく",
         "副 apparently は「どうやら〜らしい」と断定を弱める"),
        ("on the contrary", "熟", "それどころか、逆に",
         ("それにしても", "あいにく", "とにかく"),
         "On the contrary, sales rose.", "それどころか、売上は伸びた",
         "相手の否定的な発言を打ち消して「いや、むしろ」と返す"),
        ("for the sake of", "熟", "〜の利益のために、〜を思って",
         ("〜の代わりとして", "〜の後始末として", "〜と引き換えに"),
         "for the sake of the children", "子どもたちの利益を思って",
         "sake＝目的・利益。for one's own sake（自分のために）も同型"),
        ("in the long run", "熟", "長い目で見れば、結局は",
         ("差し当たっては", "折に触れて", "念のために"),
         "pay off in the long run", "長い目で見れば元が取れる",
         "短期では逆でも最終的にはこうなる、という含み"),
        ("at the mercy of", "熟", "〜のなすがままで、〜に翻弄されて",
         ("〜の後ろ盾を得て", "〜の許しを得て", "〜をあてにして"),
         "at the mercy of the weather", "天候のなすがままで",
         "mercy＝慈悲。相手の意のままで抵抗できない状態"),
    ]},
    # ============================== 第19回 ==============================
    {"no": 19, "title": "対応・包含を表す動詞", "items": [
        ("conform", "動", "基準に適合する、慣習に順応する",
         ("独自の道を貫く", "規則の適用を免れる", "前例を新たに作る"),
         "conform to safety standards", "安全基準に適合する",
         "conform to が定型。名 conformity"),
        ("adhere", "動", "方針を忠実に守る、粘着する",
         ("命令を保留にする", "助言を聞き流す", "日程を繰り上げる"),
         "adhere to the policy", "その方針を忠実に守る",
         "adhere to が定型。形 adhesive（粘着性の）"),
        ("coincide", "動", "時期が重なる、意見が一致する",
         ("順番が入れ替わる", "予定が先送りになる", "担当が変わる"),
         "coincide with the holiday", "休暇と時期が重なる",
         "名 coincidence（偶然の一致）"),
        ("correspond", "動", "〜に対応する、文通する",
         ("〜を代弁する", "〜と交代する", "〜を反復する"),
         "correspond to the original", "原本に対応する",
         "correspond to（相当する）と correspond with（文通する）"),
        ("resemble", "動", "〜によく似ている、〜と共通点が多い",
         ("〜と張り合っている", "〜に付き添っている", "〜を見下している"),
         "closely resemble each other", "互いによく似ている",
         "状態動詞なので進行形にしない。名 resemblance"),
        ("distinguish", "動", "〜を区別する、〜を際立たせる",
         ("〜を格付けする", "〜を並べ替える", "〜を混同する"),
         "distinguish right from wrong", "善悪を区別する",
         "distinguish A from B。形 distinguished（著名な）"),
        ("integrate", "動", "〜を融合させる、一つにまとめる",
         ("〜を仲介する", "〜を移管する", "〜を切り離す"),
         "integrate the two systems", "二つの体系を融合させる",
         "integrate A into B。名 integration"),
        ("incorporate", "動", "〜を取り入れる、法人にする",
         ("〜を書き換える", "〜を細分化する", "〜を試作する"),
         "incorporate new ideas", "新しい考えを取り入れる",
         "incorporate A into B。Inc. は法人組織の意"),
        ("encompass", "動", "〜を範囲に含む、〜を取り囲む",
         ("〜を割り振る", "〜を書き出す", "〜を切り詰める"),
         "encompass a wide range", "広い分野を範囲に含む",
         "compass（範囲）を en-（中に）取り込むイメージ"),
        ("comprise", "動", "〜から成る、〜を構成要素とする",
         ("〜と妥協する", "〜を圧縮する", "〜を把握する"),
         "The team comprises ten members.", "そのチームは10人から成る",
         "compromise（妥協する）と綴りが紛らわしい"),
        ("denote", "動", "〜を意味する、〜を表す記号となる",
         ("〜を否定する", "〜を寄付する", "〜を書き留める"),
         "denote a change in tone", "口調の変化を意味する",
         "donate（寄付する）と混同注意"),
        ("exemplify", "動", "〜の好例となる、典型を示す",
         ("〜の前触れとなる", "〜を単純化する", "〜の代役を務める"),
         "exemplify the trend", "その傾向の好例となる",
         "example と同語源。形 exemplary（模範的な）"),
        ("illustrate", "動", "例を挙げて説明する、挿絵を入れる",
         ("要点だけを列挙する", "話を途中で打ち切る", "結論を先送りにする"),
         "illustrate the point with data", "データで論点を説明する",
         "名 illustration。実例や図で分かりやすくする"),
        ("portray", "動", "〜を言葉で描き出す、〜を演じる",
         ("〜を並べて比べる", "〜を細かく分類する", "〜を人前で朗読する"),
         "portray him as a hero", "彼を英雄として描き出す",
         "名 portrait（肖像画）。portray A as B の形"),
        ("characterize", "動", "〜の特徴となる、〜を特徴づける",
         ("〜の欠点を補う", "〜の内訳を示す", "〜の背景を探る"),
         "characterize the era", "その時代の特徴となる",
         "be characterized by ＝〜が特徴だ"),
        ("embody", "動", "〜を具体的に表す、〜を体現する",
         ("〜を言い換える", "〜を頭の中で描く", "〜を抽象化する"),
         "embody the spirit of the age", "時代の精神を具体的に表す",
         "body（体）に em-（中に）。名 embodiment"),
        ("consist of", "熟", "〜から成り立っている、いくつかの部分でできている",
         ("〜の下請けになる", "〜に見合っている", "〜を後回しにする"),
         "consist of three parts", "3つの部分で構成されている",
         "受動態にも進行形にもしない"),
        ("result in", "熟", "〜という結果になる、〜をもたらす",
         ("〜を途中でやめる", "〜の巻き添えになる", "〜の後始末をする"),
         "result in serious damage", "重大な損害という結果になる",
         "in の後ろは結果、from の後ろは原因が来る"),
        ("derive from", "熟", "〜に由来する、〜から生じる",
         ("〜を経由する", "〜に逆らう", "〜を見限る"),
         "derive from Latin", "ラテン語に由来する",
         "derive A from B ＝BからAを引き出す"),
        ("cater to", "熟", "〜の要求に応える、〜向けに用意する",
         ("〜の注文を断る", "〜を厳しく選別する", "〜の不満を無視する"),
         "cater to young readers", "若い読者の要求に応える",
         "英では cater for。料理を提供する意味もある"),
    ]},
    # ============================== 第20回 ==============================
    {"no": 20, "title": "耐える・守る・立て直す", "items": [
        ("undergo", "動", "変化や苦難を経験する、〜を受ける",
         ("制度の改正を強く望む", "試験の日程を早める", "工程を細かく分ける"),
         "undergo major surgery", "大きな手術を経験する",
         "過去形 underwent。好ましくない経験に使うことが多い"),
        ("withstand", "動", "圧力や衝撃に耐える、持ちこたえる",
         ("危険を早めに察知する", "重みで崩れ落ちる", "勢いを増して広がる"),
         "withstand strong winds", "強風の圧力に耐える",
         "with-（〜に対抗して）＋ stand。物が主語になりやすい"),
        ("endure", "動", "苦痛を長く耐え忍ぶ、長く続く",
         ("不満を強く訴える", "治療を先延ばしにする", "回復を待ちわびる"),
         "endure years of hardship", "長年の苦痛に耐え忍ぶ",
         "名 endurance。形 enduring（長続きする）"),
        ("tolerate", "動", "〜を許容する、〜に耐える",
         ("〜を告発する", "〜を扇動する", "〜を撤回する"),
         "tolerate dissent", "異論を許容する",
         "名 tolerance。形 tolerant（寛容な）"),
        ("persist", "動", "粘り強く続ける、存続する",
         ("途中で投げ出す", "勢いよく走り出す", "一時的に途切れる"),
         "persist in asking questions", "粘り強く質問を続ける",
         "persist in doing の形。形 persistent"),
        ("prevail", "動", "最後に打ち勝つ、広く行き渡る",
         ("際どい差で敗れる", "途中で棄権する", "引き分けに終わる"),
         "Justice will prevail over greed.", "正義が最後に打ち勝つ",
         "prevail over ＝〜に打ち勝つ"),
        ("succumb", "動", "誘惑に負けて従う、病に倒れる",
         ("危険を予知する", "病気から回復する", "責任を転嫁する"),
         "succumb to temptation", "誘惑に負けて従う",
         "succumb to が定型。b は発音しない"),
        ("forfeit", "動", "権利を失う、〜を没収される",
         ("罰を免れる", "証言を拒む", "賠償を求める"),
         "forfeit the right to appeal", "上訴する権利を失う",
         "違反の罰として取り上げられる場合に使う"),
        ("preserve", "動", "〜を保存する、そのまま残す",
         ("〜を改装する", "〜を転売する", "〜を廃棄する"),
         "preserve old buildings", "古い建物を保存する",
         "名 preservation。食品の保存にも使う"),
        ("conserve", "動", "〜を節約して使う、〜を保全する",
         ("〜を安く買い替える", "〜を大量に仕入れる", "〜を人に譲り渡す"),
         "conserve water and energy", "水と電力を節約して使う",
         "名 conservation。conservative と同語源"),
        ("safeguard", "動", "〜を保護する、〜を擁護する",
         ("〜を売り込む", "〜を封鎖する", "〜を分配する"),
         "safeguard personal data", "個人の情報を保護する",
         "名詞では「安全策」。safeguard against の形"),
        ("restore", "動", "〜を元の状態に戻す、〜を修復する",
         ("〜を新品と取り替える", "〜を古いまま放置する", "〜を後回しにする"),
         "restore the old church", "古い教会を元の状態に戻す",
         "名 restoration。restore A to B の形"),
        ("revive", "動", "〜を復活させる、生き返る",
         ("〜を打ち切る", "〜を言い直す", "〜を書き換える"),
         "revive the local economy", "地域の経済を復活させる",
         "re-（再び）＋ vive（生きる）。名 revival"),
        ("replenish", "動", "〜を補充する、〜を満たし直す",
         ("〜を撤去する", "〜を値引きする", "〜を混ぜ合わせる"),
         "replenish the supplies", "備蓄を補充する",
         "plenty と同語源。減った分を元まで満たす"),
        ("salvage", "動", "〜を何とか救い出す、〜を回収する",
         ("〜を投げ捨てる", "〜を積み替える", "〜を高値で売り払う"),
         "salvage the project", "その計画を何とか救い出す",
         "難破船から積み荷を引き揚げるのが原義"),
        ("thwart", "動", "〜を阻止する、〜を挫折させる",
         ("〜を後押しする", "〜を言い張る", "〜を先取りする"),
         "thwart the plan", "その計画を阻止する",
         "th の後は w。企てを邪魔して失敗させる"),
        ("hold out", "熟", "持ちこたえる、抵抗し続ける",
         ("後ずさりする", "順番を譲る", "先手を打つ"),
         "hold out for another week", "もう1週間持ちこたえる",
         "hold out hope ＝望みを持ち続ける"),
        ("hang on to", "熟", "〜を手放さずにおく、〜に固執する",
         ("〜を人に押しつける", "〜を担保に入れる", "〜を安値で売る"),
         "hang on to your ticket", "切符を手放さずにおく",
         "口語的。hold on to とほぼ同じ意味"),
        ("ride out", "熟", "困難を乗り切る、嵐が過ぎるのを待つ",
         ("危機を招き寄せる", "重圧に押し潰される", "手順を省略する"),
         "ride out the storm", "嵐という困難を乗り切る",
         "不況や危機を、通り過ぎるまで耐えてやり過ごす"),
        ("come to terms with", "熟", "〜と折り合いをつける、〜を受け入れる",
         ("〜を期限まで延ばす", "〜をあくまで拒む", "〜の条件を吊り上げる"),
         "come to terms with the loss", "喪失と折り合いをつける",
         "terms ＝間柄。つらい事実を受け入れて心の整理をつける"),
    ]},
]
