# -*- coding: utf-8 -*-
"""数列・確率・ベクトル 基礎徹底問題集の内容(単一ソース・教科書LaTeX組版用)。
基礎から苦手な高3向けに、確率(数A)・数列(数B)・ベクトル(数C/B)を基礎の基礎から徹底演習する。
数式は $...$ の LaTeX(日本語は $ の外)。各問の chk は sympy 等で答えを独立再計算し True を返す(verify.py が実行)。
"""
import sympy as sp
from sympy import (symbols, expand, factor, simplify, sqrt, Rational as R,
    solveset, solve, S, Interval, FiniteSet, Abs, Eq, oo, pi, I,
    sin, cos, tan, atan, acos, asin, log, binomial, factorial,
    gcd, divisors, Matrix, N, nsimplify)

x, y, z, a, b, c, d, m, n, k, t, r, s, theta = symbols(
    'x y z a b c d m n k t r s theta', real=True)

def EQ(u, v):  return simplify(sp.expand(u) - sp.expand(v)) == 0
def NUM(u, v, tol=1e-9): return abs(complex(N(u) - N(v))) < tol
def P(nn, rr): return factorial(nn) // factorial(nn - rr)   # 順列
def C(nn, rr): return int(binomial(nn, rr))                 # 組合せ

FW = "　"  # 全角スペース(問題文と数式の区切り)

# ============================================================================
#  第1編  確率  (数え上げ → 順列・組合せ → 確率の基本 → いろいろな確率)
# ============================================================================

U_kazoe = {"name": "場合の数の基本", "tag": "数え上げ・和の法則・積の法則・約数", "problems": [
  {"group": "樹形図と数え上げ", "level": "basic",
   "stem": "1, 2, 3 の3個の数字から異なる2個を選んで2桁の整数をつくる。全部で何個できるか。",
   "answer": "$6$ 個", "explanation": "十の位は3通り、その各々に対し一の位は残り2通り。積の法則で $3\\times 2=6$。",
   "chk": lambda: P(3, 2) == 6},
  {"group": "樹形図と数え上げ", "level": "basic",
   "stem": "大小2個のさいころを投げる。目の出方は全部で何通りか。",
   "answer": "$36$ 通り", "explanation": "大が6通り、その各々に小が6通り。積の法則で $6\\times 6=36$。",
   "chk": lambda: 6 * 6 == 36},
  {"group": "樹形図と数え上げ", "level": "basic",
   "stem": "大小2個のさいころを投げるとき、出た目の和が $7$ になる出方は何通りか。書き出して求めよ。",
   "answer": "$6$ 通り", "explanation": "$(1,6),(2,5),(3,4),(4,3),(5,2),(6,1)$ の6通り。",
   "chk": lambda: len([(i, j) for i in range(1, 7) for j in range(1, 7) if i + j == 7]) == 6},
  {"group": "樹形図と数え上げ", "level": "basic",
   "stem": "A, B, C, D の4人が1列に並ぶ。並び方は全部で何通りか。",
   "answer": "$24$ 通り", "explanation": "先頭から順に $4\\times 3\\times 2\\times 1=4!=24$ 通り。",
   "chk": lambda: factorial(4) == 24},
  {"group": "和の法則・積の法則", "level": "basic",
   "stem": "前菜3種類、主菜4種類から1つずつ選ぶ。選び方は全部で何通りか。",
   "answer": "$12$ 通り", "explanation": "前菜3通りの各々に主菜4通り。積の法則で $3\\times 4=12$。",
   "chk": lambda: 3 * 4 == 12},
  {"group": "和の法則・積の法則", "level": "standard",
   "stem": "1 から 20 までの整数のうち、$3$ の倍数または $5$ の倍数は何個あるか。",
   "answer": "$9$ 個", "explanation": "3の倍数6個、5の倍数4個、両方(15の倍数)1個。$6+4-1=9$(重複を1回引く)。",
   "chk": lambda: len([i for i in range(1, 21) if i % 3 == 0 or i % 5 == 0]) == 9},
  {"group": "和の法則・積の法則", "level": "standard",
   "stem": "大中小3個のさいころを投げるとき、目の積が奇数になる出方は何通りか。",
   "answer": "$27$ 通り", "explanation": "積が奇数になるのは3つとも奇数のとき。奇数は1,3,5の3通りずつで $3\\times3\\times3=27$。",
   "chk": lambda: 3 ** 3 == 27},
  {"group": "和の法則・積の法則", "level": "standard",
   "stem": "$3$ 桁の整数のうち、各位の数字がすべて異なるものは何個あるか。",
   "answer": "$648$ 個", "explanation": "百の位は $1\\sim 9$ の9通り、十の位は0を含む残り9通り、一の位は残り8通り。$9\\times9\\times8=648$。",
   "chk": lambda: 9 * 9 * 8 == 648},
  {"group": "約数の個数と総和", "level": "standard",
   "stem": "$72$ の正の約数は何個あるか。",
   "answer": "$12$ 個", "explanation": "$72=2^{3}\\times 3^{2}$。指数に1を足して掛け、$(3+1)(2+1)=12$。",
   "chk": lambda: len(list(divisors(72))) == 12},
  {"group": "約数の個数と総和", "level": "standard",
   "stem": "$72$ の正の約数すべての和を求めよ。",
   "answer": "$195$", "explanation": "$(1+2+4+8)(1+3+9)=15\\times 13=195$。",
   "chk": lambda: sum(divisors(72)) == 195},
  {"group": "積の分解で数える", "level": "standard",
   "stem": "大小2個のさいころを投げるとき、出た目の積が $12$ になる出方は何通りか。",
   "answer": "$4$ 通り", "explanation": "$(2,6),(3,4),(4,3),(6,2)$ の4通り。",
   "chk": lambda: len([(i, j) for i in range(1, 7) for j in range(1, 7) if i * j == 12]) == 4},
]}

U_junkumi = {"name": "順列と組合せ", "tag": "P・C・円順列・同じものを含む順列", "problems": [
  {"group": "順列 P", "level": "basic",
   "stem": "${}_{7}\\mathrm{P}_{3}$ の値を求めよ。",
   "answer": "$210$", "explanation": "${}_{7}\\mathrm{P}_{3}=7\\times 6\\times 5=210$(7から始めて3個かける)。",
   "chk": lambda: P(7, 3) == 210},
  {"group": "順列 P", "level": "basic",
   "stem": "$6$ 人が1列に並ぶ並び方は何通りか。",
   "answer": "$720$ 通り", "explanation": "$6!=6\\times5\\times4\\times3\\times2\\times1=720$。",
   "chk": lambda: factorial(6) == 720},
  {"group": "順列 P", "level": "standard",
   "stem": "男子3人、女子2人の計5人が1列に並ぶとき、女子2人が隣り合う並び方は何通りか。",
   "answer": "$48$ 通り", "explanation": "女子2人を1つの塊とみて4つを並べ $4!$、塊の中で女子を並べ $2!$。$4!\\times 2!=24\\times2=48$。",
   "chk": lambda: factorial(4) * factorial(2) == 48},
  {"group": "順列 P", "level": "standard",
   "stem": "$5$ 人が円形のテーブルに座る座り方は何通りか(円順列)。",
   "answer": "$24$ 通り", "explanation": "円順列は $(5-1)!=4!=24$。1人を固定して残りを並べると考える。",
   "chk": lambda: factorial(4) == 24},
  {"group": "組合せ C", "level": "basic",
   "stem": "$10$ 人から $3$ 人の委員を選ぶ方法は何通りか。",
   "answer": "$120$ 通り", "explanation": "${}_{10}\\mathrm{C}_{3}=\\dfrac{10\\times9\\times8}{3\\times2\\times1}=120$(順番は区別しない)。",
   "chk": lambda: C(10, 3) == 120},
  {"group": "組合せ C", "level": "basic",
   "stem": "${}_{8}\\mathrm{C}_{2}$ の値を求めよ。",
   "answer": "$28$", "explanation": "${}_{8}\\mathrm{C}_{2}=\\dfrac{8\\times7}{2\\times1}=28$。",
   "chk": lambda: C(8, 2) == 28},
  {"group": "組合せ C", "level": "standard",
   "stem": "男子6人、女子4人から4人を選ぶとき、男子2人・女子2人となる選び方は何通りか。",
   "answer": "$90$ 通り", "explanation": "男子から2人 ${}_{6}\\mathrm{C}_{2}=15$、女子から2人 ${}_{4}\\mathrm{C}_{2}=6$。積の法則で $15\\times6=90$。",
   "chk": lambda: C(6, 2) * C(4, 2) == 90},
  {"group": "組合せ C", "level": "standard",
   "stem": "正八角形の3個の頂点を結んでできる三角形は何個あるか。",
   "answer": "$56$ 個", "explanation": "どの3頂点も一直線上にないので ${}_{8}\\mathrm{C}_{3}=56$。",
   "chk": lambda: C(8, 3) == 56},
  {"group": "組合せ C", "level": "standard",
   "stem": "正八角形の対角線は全部で何本あるか。",
   "answer": "$20$ 本", "explanation": "2頂点の結び方 ${}_{8}\\mathrm{C}_{2}=28$ から、辺の8本を引いて $28-8=20$。",
   "chk": lambda: C(8, 2) - 8 == 20},
  {"group": "同じものを含む順列", "level": "standard",
   "stem": "$5$ 文字 A, A, B, B, C を1列に並べる並べ方は何通りか。",
   "answer": "$30$ 通り", "explanation": "同じものを含む順列。$\\dfrac{5!}{2!\\,2!}=\\dfrac{120}{4}=30$。",
   "chk": lambda: factorial(5) // (factorial(2) * factorial(2)) == 30},
  {"group": "同じものを含む順列", "level": "standard",
   "stem": "BANANA の6文字を1列に並べる並べ方は何通りか。",
   "answer": "$60$ 通り", "explanation": "A が3個、N が2個、B が1個。$\\dfrac{6!}{3!\\,2!}=\\dfrac{720}{12}=60$。",
   "chk": lambda: factorial(6) // (factorial(3) * factorial(2)) == 60},
  {"group": "同じものを含む順列", "level": "standard",
   "stem": "1, 2, 3 の数字を、同じ数字を何回使ってもよいとして並べ、3桁の整数をつくる。何個できるか(重複順列)。",
   "answer": "$27$ 個", "explanation": "各位が3通りずつ自由に選べる。$3\\times3\\times3=3^{3}=27$。",
   "chk": lambda: 3 ** 3 == 27},
]}

U_kakuritsu = {"name": "確率の基本", "tag": "確率の定義・さいころ・玉・カード", "problems": [
  {"group": "確率の定義", "level": "basic",
   "stem": "1個のさいころを投げるとき、$3$ の倍数の目が出る確率を求めよ。",
   "answer": "$\\dfrac{1}{3}$", "explanation": "3の倍数は3,6の2通り、全部で6通り。$\\dfrac{2}{6}=\\dfrac{1}{3}$。",
   "chk": lambda: R(2, 6) == R(1, 3)},
  {"group": "確率の定義", "level": "basic",
   "stem": "大小2個のさいころを投げるとき、目の和が $7$ になる確率を求めよ。",
   "answer": "$\\dfrac{1}{6}$", "explanation": "和が7は6通り、全部で $6\\times6=36$ 通り。$\\dfrac{6}{36}=\\dfrac{1}{6}$。",
   "chk": lambda: R(6, 36) == R(1, 6)},
  {"group": "確率の定義", "level": "basic",
   "stem": "赤玉3個、白玉2個が入った袋から1個取り出すとき、赤玉が出る確率を求めよ。",
   "answer": "$\\dfrac{3}{5}$", "explanation": "全部で5個、赤は3個。$\\dfrac{3}{5}$。",
   "chk": lambda: R(3, 5) == R(3, 5)},
  {"group": "組合せを使う確率", "level": "standard",
   "stem": "赤玉4個、白玉3個の入った袋から同時に2個取り出すとき、2個とも赤玉である確率を求めよ。",
   "answer": "$\\dfrac{2}{7}$", "explanation": "全部の取り出し方 ${}_{7}\\mathrm{C}_{2}=21$、赤2個は ${}_{4}\\mathrm{C}_{2}=6$。$\\dfrac{6}{21}=\\dfrac{2}{7}$。",
   "chk": lambda: R(C(4, 2), C(7, 2)) == R(2, 7)},
  {"group": "組合せを使う確率", "level": "standard",
   "stem": "赤玉4個、白玉3個から同時に2個取り出すとき、赤玉1個・白玉1個となる確率を求めよ。",
   "answer": "$\\dfrac{4}{7}$", "explanation": "赤から1個 ${}_{4}\\mathrm{C}_{1}=4$、白から1個 ${}_{3}\\mathrm{C}_{1}=3$。$\\dfrac{4\\times3}{21}=\\dfrac{12}{21}=\\dfrac{4}{7}$。",
   "chk": lambda: R(C(4, 1) * C(3, 1), C(7, 2)) == R(4, 7)},
  {"group": "組合せを使う確率", "level": "standard",
   "stem": "男子4人、女子3人から3人の委員をくじで選ぶとき、女子だけが選ばれる確率を求めよ。",
   "answer": "$\\dfrac{1}{35}$", "explanation": "全体 ${}_{7}\\mathrm{C}_{3}=35$、女子3人は ${}_{3}\\mathrm{C}_{3}=1$。$\\dfrac{1}{35}$。",
   "chk": lambda: R(C(3, 3), C(7, 3)) == R(1, 35)},
  {"group": "組合せを使う確率", "level": "standard",
   "stem": "1 から 9 の数字が書かれた9枚のカードから2枚引くとき、2枚とも奇数である確率を求めよ。",
   "answer": "$\\dfrac{5}{18}$", "explanation": "奇数は1,3,5,7,9の5枚。$\\dfrac{{}_{5}\\mathrm{C}_{2}}{{}_{9}\\mathrm{C}_{2}}=\\dfrac{10}{36}=\\dfrac{5}{18}$。",
   "chk": lambda: R(C(5, 2), C(9, 2)) == R(5, 18)},
  {"group": "いろいろな確率", "level": "standard",
   "stem": "3枚の硬貨を同時に投げるとき、表がちょうど2枚出る確率を求めよ。",
   "answer": "$\\dfrac{3}{8}$", "explanation": "全部で $2^{3}=8$ 通り。表2枚の出方は ${}_{3}\\mathrm{C}_{2}=3$ 通り。$\\dfrac{3}{8}$。",
   "chk": lambda: R(C(3, 2), 2 ** 3) == R(3, 8)},
  {"group": "いろいろな確率", "level": "standard",
   "stem": "大小2個のさいころを投げるとき、少なくとも一方が $6$ の目である確率を求めよ。",
   "answer": "$\\dfrac{11}{36}$", "explanation": "余事象「両方とも6以外」は $\\dfrac{5\\times5}{36}=\\dfrac{25}{36}$。$1-\\dfrac{25}{36}=\\dfrac{11}{36}$。",
   "chk": lambda: 1 - R(25, 36) == R(11, 36)},
  {"group": "いろいろな確率", "level": "standard",
   "stem": "A, B, C, D, E の5人が1列に並ぶとき、A と B が隣り合う確率を求めよ。",
   "answer": "$\\dfrac{2}{5}$", "explanation": "全体 $5!=120$。A,Bを塊にして $4!\\times2!=48$。$\\dfrac{48}{120}=\\dfrac{2}{5}$。",
   "chk": lambda: R(factorial(4) * factorial(2), factorial(5)) == R(2, 5)},
  {"group": "いろいろな確率", "level": "basic",
   "stem": "ジョーカーを除く $52$ 枚のトランプから1枚引くとき、それがハートである確率を求めよ。",
   "answer": "$\\dfrac{1}{4}$", "explanation": "ハートは13枚、全部で52枚。$\\dfrac{13}{52}=\\dfrac{1}{4}$。",
   "chk": lambda: R(13, 52) == R(1, 4)},
  {"group": "いろいろな確率", "level": "standard",
   "stem": "当たり3本、はずれ7本のくじから同時に2本引くとき、少なくとも1本当たる確率を求めよ。",
   "answer": "$\\dfrac{8}{15}$", "explanation": "余事象「2本ともはずれ」は $\\dfrac{{}_{7}\\mathrm{C}_{2}}{{}_{10}\\mathrm{C}_{2}}=\\dfrac{21}{45}=\\dfrac{7}{15}$。$1-\\dfrac{7}{15}=\\dfrac{8}{15}$。",
   "chk": lambda: 1 - R(C(7, 2), C(10, 2)) == R(8, 15)},
]}

U_iroiro = {"name": "いろいろな確率", "tag": "加法定理・独立試行・反復試行・条件付き・期待値", "problems": [
  {"group": "加法定理・余事象", "level": "standard",
   "stem": "1 から 10 の番号札から1枚引くとき、偶数または $3$ の倍数である確率を求めよ。",
   "answer": "$\\dfrac{7}{10}$", "explanation": "偶数5個、3の倍数(3,6,9)3個、両方(6)1個。$\\dfrac{5+3-1}{10}=\\dfrac{7}{10}$。",
   "chk": lambda: R(len([i for i in range(1, 11) if i % 2 == 0 or i % 3 == 0]), 10) == R(7, 10)},
  {"group": "加法定理・余事象", "level": "standard",
   "stem": "大小2個のさいころを投げるとき、目の和が $5$ の倍数(5 または 10)になる確率を求めよ。",
   "answer": "$\\dfrac{7}{36}$", "explanation": "和5は4通り、和10は3通りで計7通り。$\\dfrac{7}{36}$。",
   "chk": lambda: R(len([(i, j) for i in range(1, 7) for j in range(1, 7) if (i + j) % 5 == 0]), 36) == R(7, 36)},
  {"group": "独立試行・反復試行", "level": "standard",
   "stem": "フリースローを決める確率が $\\dfrac{2}{3}$ の選手が2回投げるとき、2回とも決める確率を求めよ。",
   "answer": "$\\dfrac{4}{9}$", "explanation": "独立な試行なので確率をかける。$\\dfrac{2}{3}\\times\\dfrac{2}{3}=\\dfrac{4}{9}$。",
   "chk": lambda: R(2, 3) ** 2 == R(4, 9)},
  {"group": "独立試行・反復試行", "level": "standard",
   "stem": "1個のさいころを3回投げるとき、$1$ の目がちょうど1回出る確率を求めよ。",
   "answer": "$\\dfrac{25}{72}$", "explanation": "反復試行 ${}_{3}\\mathrm{C}_{1}\\left(\\dfrac{1}{6}\\right)^{1}\\left(\\dfrac{5}{6}\\right)^{2}=3\\cdot\\dfrac{25}{216}=\\dfrac{75}{216}=\\dfrac{25}{72}$。",
   "chk": lambda: C(3, 1) * R(1, 6) ** 1 * R(5, 6) ** 2 == R(25, 72)},
  {"group": "独立試行・反復試行", "level": "standard",
   "stem": "1枚の硬貨を5回投げるとき、表がちょうど3回出る確率を求めよ。",
   "answer": "$\\dfrac{5}{16}$", "explanation": "反復試行 ${}_{5}\\mathrm{C}_{3}\\left(\\dfrac{1}{2}\\right)^{5}=\\dfrac{10}{32}=\\dfrac{5}{16}$。",
   "chk": lambda: C(5, 3) * R(1, 2) ** 5 == R(5, 16)},
  {"group": "独立試行・反復試行", "level": "standard",
   "stem": "当たる確率が $\\dfrac{1}{3}$ のくじを(毎回もとに戻して)4回引くとき、ちょうど2回当たる確率を求めよ。",
   "answer": "$\\dfrac{8}{27}$", "explanation": "${}_{4}\\mathrm{C}_{2}\\left(\\dfrac{1}{3}\\right)^{2}\\left(\\dfrac{2}{3}\\right)^{2}=6\\cdot\\dfrac{1}{9}\\cdot\\dfrac{4}{9}=\\dfrac{24}{81}=\\dfrac{8}{27}$。",
   "chk": lambda: C(4, 2) * R(1, 3) ** 2 * R(2, 3) ** 2 == R(8, 27)},
  {"group": "条件付き確率", "level": "standard",
   "stem": "袋に赤玉2個、白玉3個。玉を1個取り出し、もとに戻さずにもう1個取り出す。1個目が赤、2個目が白である確率を求めよ。",
   "answer": "$\\dfrac{3}{10}$", "explanation": "1個目に赤 $\\dfrac{2}{5}$、続けて白 $\\dfrac{3}{4}$。$\\dfrac{2}{5}\\times\\dfrac{3}{4}=\\dfrac{6}{20}=\\dfrac{3}{10}$。",
   "chk": lambda: R(2, 5) * R(3, 4) == R(3, 10)},
  {"group": "条件付き確率", "level": "standard",
   "stem": "男子3人、女子2人から2人を続けて選ぶ(もとに戻さない)。1人目が男子だったとき、2人目も男子である条件付き確率を求めよ。",
   "answer": "$\\dfrac{1}{2}$", "explanation": "1人目に男子を選んだ後、残り4人中に男子は2人。$\\dfrac{2}{4}=\\dfrac{1}{2}$。",
   "chk": lambda: R(2, 4) == R(1, 2)},
  {"group": "条件付き確率", "level": "standard",
   "stem": "箱Aには当たり1本・はずれ3本、箱Bには当たり2本・はずれ2本。さいころを振り、1か2ならA、それ以外ならBを選んで1本引く。当たる確率を求めよ。",
   "answer": "$\\dfrac{5}{12}$", "explanation": "Aを選ぶ確率 $\\dfrac{1}{3}$ で当たり $\\dfrac{1}{4}$、Bを選ぶ確率 $\\dfrac{2}{3}$ で当たり $\\dfrac{1}{2}$。$\\dfrac{1}{3}\\cdot\\dfrac{1}{4}+\\dfrac{2}{3}\\cdot\\dfrac{1}{2}=\\dfrac{1}{12}+\\dfrac{4}{12}=\\dfrac{5}{12}$。",
   "chk": lambda: R(1, 3) * R(1, 4) + R(2, 3) * R(1, 2) == R(5, 12)},
  {"group": "期待値", "level": "standard",
   "stem": "1個のさいころを投げ、出た目の数だけ得点がもらえる。得点の期待値を求めよ。",
   "answer": "$\\dfrac{7}{2}$", "explanation": "各目 $\\dfrac{1}{6}$ ずつ。$\\dfrac{1+2+3+4+5+6}{6}=\\dfrac{21}{6}=\\dfrac{7}{2}$。",
   "chk": lambda: sum(R(i, 6) for i in range(1, 7)) == R(7, 2)},
  {"group": "期待値", "level": "standard",
   "stem": "当たり(賞金300円)2本、はずれ(0円)3本のくじを1本引く。もらえる金額の期待値を求めよ。",
   "answer": "$120$ 円", "explanation": "$300\\times\\dfrac{2}{5}+0\\times\\dfrac{3}{5}=120$(円)。",
   "chk": lambda: 300 * R(2, 5) == 120},
]}

# ============================================================================
#  第2編  数列  (等差 → 等比 → 和とΣ → 漸化式・数学的帰納法)
# ============================================================================

U_tousa = {"name": "等差数列", "tag": "一般項・和", "problems": [
  {"group": "一般項", "level": "basic",
   "stem": "初項 $3$、公差 $4$ の等差数列の一般項 $a_{n}$ を求めよ。",
   "answer": "$a_{n}=4n-1$", "explanation": "$a_{n}=a_{1}+(n-1)d=3+(n-1)\\cdot4=4n-1$。",
   "chk": lambda: EQ(3 + (n - 1) * 4, 4 * n - 1)},
  {"group": "一般項", "level": "basic",
   "stem": "初項 $3$、公差 $4$ の等差数列の第 $10$ 項を求めよ。",
   "answer": "$39$", "explanation": "$a_{10}=4\\cdot10-1=39$。",
   "chk": lambda: 4 * 10 - 1 == 39},
  {"group": "一般項", "level": "basic",
   "stem": "初項 $20$、公差 $-3$ の等差数列の一般項 $a_{n}$ を求めよ。",
   "answer": "$a_{n}=-3n+23$", "explanation": "$a_{n}=20+(n-1)(-3)=-3n+23$。",
   "chk": lambda: EQ(20 + (n - 1) * (-3), -3 * n + 23)},
  {"group": "一般項", "level": "basic",
   "stem": "等差数列 $-7,\\ -4,\\ -1,\\ 2,\\ \\ldots$ の一般項 $a_{n}$ を求めよ。",
   "answer": "$a_{n}=3n-10$", "explanation": "初項 $-7$、公差 $3$。$a_{n}=-7+(n-1)\\cdot3=3n-10$。",
   "chk": lambda: EQ(-7 + (n - 1) * 3, 3 * n - 10)},
  {"group": "一般項", "level": "standard",
   "stem": "第 $3$ 項が $11$、第 $7$ 項が $27$ である等差数列の初項と公差を求めよ。",
   "answer": "初項 $3$、公差 $4$", "explanation": "$a_{1}+2d=11,\\ a_{1}+6d=27$。辺々引いて $4d=16$、$d=4$、$a_{1}=11-8=3$。",
   "chk": lambda: (3 + 2 * 4 == 11) and (3 + 6 * 4 == 27)},
  {"group": "一般項", "level": "standard",
   "stem": "等差数列 $5,\\ 8,\\ 11,\\ 14,\\ \\ldots$ で、第 $n$ 項が $92$ となるのは第何項か。",
   "answer": "第 $30$ 項", "explanation": "$a_{n}=3n+2$。$3n+2=92$ より $n=30$。",
   "chk": lambda: 3 * 30 + 2 == 92},
  {"group": "和", "level": "basic",
   "stem": "$1$ から $100$ までの自然数の和を求めよ。",
   "answer": "$5050$", "explanation": "$\\dfrac{n(a_{1}+a_{n})}{2}=\\dfrac{100(1+100)}{2}=5050$。",
   "chk": lambda: 100 * 101 // 2 == 5050},
  {"group": "和", "level": "basic",
   "stem": "$1$ から $99$ までの奇数の和 $1+3+5+\\cdots+99$ を求めよ。",
   "answer": "$2500$", "explanation": "奇数は50個。$\\dfrac{50(1+99)}{2}=2500$($=50^{2}$)。",
   "chk": lambda: 50 * (1 + 99) // 2 == 2500},
  {"group": "和", "level": "basic",
   "stem": "初項 $2$、公差 $3$ の等差数列の、初項から第 $20$ 項までの和を求めよ。",
   "answer": "$610$", "explanation": "$S_{n}=\\dfrac{n\\{2a_{1}+(n-1)d\\}}{2}=\\dfrac{20(4+19\\cdot3)}{2}=10\\times61=610$。",
   "chk": lambda: 20 * (2 * 2 + 19 * 3) // 2 == 610},
  {"group": "和", "level": "standard",
   "stem": "第 $5$ 項が $20$、初項から第 $5$ 項までの和が $70$ である等差数列の初項 $a_{1}$ と公差 $d$ を求めよ。",
   "answer": "初項 $8$、公差 $3$", "explanation": "$a_{1}+4d=20$、$S_{5}=5(a_{1}+2d)=70$ より $a_{1}+2d=14$。引いて $2d=6$、$d=3,\\ a_{1}=8$。",
   "chk": lambda: (8 + 4 * 3 == 20) and (5 * (8 + 2 * 3) == 70)},
  {"group": "和", "level": "advanced",
   "stem": "初項 $50$、公差 $-4$ の等差数列で、初項から第 $n$ 項までの和 $S_{n}$ が最大となる $n$ とそのときの最大値を求めよ。",
   "answer": "$n=13$、最大値 $338$", "explanation": "$a_{n}=54-4n$。$a_{13}=2>0,\\ a_{14}=-2<0$ なので第13項までが正。$S_{13}=\\dfrac{13(50+2)}{2}=338$。",
   "chk": lambda: (54 - 4 * 13 > 0) and (54 - 4 * 14 < 0) and (13 * (50 + (54 - 4 * 13)) // 2 == 338)},
]}

U_touhi = {"name": "等比数列", "tag": "一般項・和", "problems": [
  {"group": "一般項", "level": "basic",
   "stem": "初項 $2$、公比 $3$ の等比数列の第 $5$ 項を求めよ。",
   "answer": "$162$", "explanation": "$a_{n}=a_{1}r^{\\,n-1}$ より $a_{5}=2\\cdot3^{4}=2\\times81=162$。",
   "chk": lambda: 2 * 3 ** 4 == 162},
  {"group": "一般項", "level": "basic",
   "stem": "初項 $5$、公比 $2$ の等比数列の一般項 $a_{n}$ を求めよ。",
   "answer": "$a_{n}=5\\cdot2^{\\,n-1}$", "explanation": "$a_{n}=a_{1}r^{\\,n-1}=5\\cdot2^{\\,n-1}$。試しに $a_{4}=5\\cdot2^{3}=40$。",
   "chk": lambda: 5 * 2 ** (4 - 1) == 40},
  {"group": "一般項", "level": "basic",
   "stem": "等比数列 $1,\\ -2,\\ 4,\\ -8,\\ \\ldots$ の一般項 $a_{n}$ を求めよ。",
   "answer": "$a_{n}=(-2)^{\\,n-1}$", "explanation": "初項 $1$、公比 $-2$。$a_{n}=(-2)^{\\,n-1}$。$a_{4}=(-2)^{3}=-8$。",
   "chk": lambda: (-2) ** (4 - 1) == -8},
  {"group": "一般項", "level": "standard",
   "stem": "第 $2$ 項が $6$、第 $4$ 項が $54$ である等比数列の公比(正)と初項を求めよ。",
   "answer": "公比 $3$、初項 $2$", "explanation": "$\\dfrac{a_{4}}{a_{2}}=r^{2}=\\dfrac{54}{6}=9$、$r=3$(正)。$a_{1}r=6$ より $a_{1}=2$。",
   "chk": lambda: (2 * 3 == 6) and (2 * 3 ** 3 == 54)},
  {"group": "一般項", "level": "standard",
   "stem": "等比数列 $3,\\ 6,\\ 12,\\ 24,\\ \\ldots$ で、第 $n$ 項が $384$ となるのは第何項か。",
   "answer": "第 $8$ 項", "explanation": "$a_{n}=3\\cdot2^{\\,n-1}=384$ より $2^{\\,n-1}=128=2^{7}$、$n=8$。",
   "chk": lambda: 3 * 2 ** (8 - 1) == 384},
  {"group": "和", "level": "basic",
   "stem": "初項 $1$、公比 $2$ の等比数列の、初項から第 $10$ 項までの和を求めよ。",
   "answer": "$1023$", "explanation": "$S_{n}=\\dfrac{a_{1}(r^{n}-1)}{r-1}=\\dfrac{1\\cdot(2^{10}-1)}{2-1}=1023$。",
   "chk": lambda: (2 ** 10 - 1) == 1023},
  {"group": "和", "level": "basic",
   "stem": "初項 $3$、公比 $2$ の等比数列の、初項から第 $5$ 項までの和を求めよ。",
   "answer": "$93$", "explanation": "$\\dfrac{3(2^{5}-1)}{2-1}=3\\times31=93$。",
   "chk": lambda: 3 * (2 ** 5 - 1) == 93},
  {"group": "和", "level": "standard",
   "stem": "初項 $2$、公比 $3$ の等比数列の、初項から第 $4$ 項までの和を求めよ。",
   "answer": "$80$", "explanation": "$\\dfrac{2(3^{4}-1)}{3-1}=\\dfrac{2\\times80}{2}=80$。実際 $2+6+18+54=80$。",
   "chk": lambda: (2 + 6 + 18 + 54) == 80 and 2 * (3 ** 4 - 1) // (3 - 1) == 80},
  {"group": "和", "level": "standard",
   "stem": "$1+\\dfrac{1}{2}+\\dfrac{1}{4}+\\cdots+\\dfrac{1}{2^{9}}$(第 $10$ 項まで)の和を求めよ。",
   "answer": "$\\dfrac{1023}{512}$", "explanation": "初項 $1$、公比 $\\dfrac{1}{2}$。$\\dfrac{1\\left(1-(1/2)^{10}\\right)}{1-1/2}=2\\left(1-\\dfrac{1}{1024}\\right)=\\dfrac{1023}{512}$。",
   "chk": lambda: sum(R(1, 2) ** i for i in range(0, 10)) == R(1023, 512)},
  {"group": "和", "level": "standard",
   "stem": "等比数列で初項 $2$、第 $4$ 項が $16$ のとき、公比(正)と第 $6$ 項を求めよ。",
   "answer": "公比 $2$、第 $6$ 項 $64$", "explanation": "$a_{1}r^{3}=16$、$2r^{3}=16$、$r^{3}=8$、$r=2$。$a_{6}=2\\cdot2^{5}=64$。",
   "chk": lambda: (2 * 2 ** 3 == 16) and (2 * 2 ** 5 == 64)},
]}

U_sigma = {"name": "和とシグマ", "tag": "Σの公式・階差数列・部分分数", "problems": [
  {"group": "シグマの計算", "level": "basic",
   "stem": "$\\displaystyle\\sum_{k=1}^{10} k$ を求めよ。",
   "answer": "$55$", "explanation": "$\\sum_{k=1}^{n}k=\\dfrac{n(n+1)}{2}$ より $\\dfrac{10\\cdot11}{2}=55$。",
   "chk": lambda: sum(range(1, 11)) == 55},
  {"group": "シグマの計算", "level": "basic",
   "stem": "$\\displaystyle\\sum_{k=1}^{5} k^{2}$ を求めよ。",
   "answer": "$55$", "explanation": "$\\sum_{k=1}^{n}k^{2}=\\dfrac{n(n+1)(2n+1)}{6}$ より $\\dfrac{5\\cdot6\\cdot11}{6}=55$。",
   "chk": lambda: sum(i * i for i in range(1, 6)) == 55},
  {"group": "シグマの計算", "level": "basic",
   "stem": "$\\displaystyle\\sum_{k=1}^{6} k^{3}$ を求めよ。",
   "answer": "$441$", "explanation": "$\\sum_{k=1}^{n}k^{3}=\\left\\{\\dfrac{n(n+1)}{2}\\right\\}^{2}=21^{2}=441$。",
   "chk": lambda: sum(i ** 3 for i in range(1, 7)) == 441},
  {"group": "シグマの計算", "level": "standard",
   "stem": "$\\displaystyle\\sum_{k=1}^{n}(2k-1)$ を $n$ の式で表せ。",
   "answer": "$n^{2}$", "explanation": "$2\\sum k-\\sum 1=2\\cdot\\dfrac{n(n+1)}{2}-n=n^{2}+n-n=n^{2}$。",
   "chk": lambda: all(sum(2 * i - 1 for i in range(1, mm + 1)) == mm * mm for mm in range(1, 8))},
  {"group": "シグマの計算", "level": "standard",
   "stem": "$\\displaystyle\\sum_{k=1}^{n} k(k+1)$ を $n$ の式で表せ。",
   "answer": "$\\dfrac{n(n+1)(n+2)}{3}$", "explanation": "$\\sum k^{2}+\\sum k=\\dfrac{n(n+1)(2n+1)}{6}+\\dfrac{n(n+1)}{2}=\\dfrac{n(n+1)(n+2)}{3}$。",
   "chk": lambda: all(sum(i * (i + 1) for i in range(1, mm + 1)) == mm * (mm + 1) * (mm + 2) // 3 for mm in range(1, 8))},
  {"group": "シグマの計算", "level": "standard",
   "stem": "$\\displaystyle\\sum_{k=1}^{n}(3k-2)$ を $n$ の式で表せ(初項 $1$、公差 $3$ の等差数列の和)。",
   "answer": "$\\dfrac{n(3n-1)}{2}$", "explanation": "$3\\cdot\\dfrac{n(n+1)}{2}-2n=\\dfrac{3n^{2}+3n-4n}{2}=\\dfrac{n(3n-1)}{2}$。",
   "chk": lambda: all(sum(3 * i - 2 for i in range(1, mm + 1)) == mm * (3 * mm - 1) // 2 for mm in range(1, 8))},
  {"group": "階差数列", "level": "standard",
   "stem": "数列 $2,\\ 5,\\ 10,\\ 17,\\ 26,\\ \\ldots$ の一般項 $a_{n}$ を求めよ(階差を利用)。",
   "answer": "$a_{n}=n^{2}+1$", "explanation": "階差は $3,5,7,9,\\ldots$($=2k+1$)。$a_{n}=2+\\sum_{k=1}^{n-1}(2k+1)=n^{2}+1$。",
   "chk": lambda: [i ** 2 + 1 for i in range(1, 6)] == [2, 5, 10, 17, 26]},
  {"group": "階差数列", "level": "standard",
   "stem": "数列 $1,\\ 2,\\ 4,\\ 7,\\ 11,\\ 16,\\ \\ldots$ の一般項 $a_{n}$ を求めよ。",
   "answer": "$a_{n}=\\dfrac{n^{2}-n+2}{2}$", "explanation": "階差は $1,2,3,4,5,\\ldots$($=k$)。$a_{n}=1+\\sum_{k=1}^{n-1}k=1+\\dfrac{(n-1)n}{2}=\\dfrac{n^{2}-n+2}{2}$。",
   "chk": lambda: [(i ** 2 - i + 2) // 2 for i in range(1, 7)] == [1, 2, 4, 7, 11, 16]},
  {"group": "部分分数分解の和", "level": "standard",
   "stem": "$\\displaystyle\\sum_{k=1}^{n}\\dfrac{1}{k(k+1)}$ を $n$ の式で表せ。",
   "answer": "$\\dfrac{n}{n+1}$", "explanation": "$\\dfrac{1}{k(k+1)}=\\dfrac{1}{k}-\\dfrac{1}{k+1}$ と分解すると次々打ち消し合い、$1-\\dfrac{1}{n+1}=\\dfrac{n}{n+1}$。",
   "chk": lambda: all(sum(R(1, i * (i + 1)) for i in range(1, mm + 1)) == R(mm, mm + 1) for mm in range(1, 8))},
  {"group": "部分分数分解の和", "level": "standard",
   "stem": "$\\displaystyle\\sum_{k=1}^{10}\\dfrac{1}{k(k+1)}$ を求めよ。",
   "answer": "$\\dfrac{10}{11}$", "explanation": "上の公式で $n=10$ とすると $\\dfrac{10}{11}$。",
   "chk": lambda: sum(R(1, i * (i + 1)) for i in range(1, 11)) == R(10, 11)},
]}

U_zenka = {"name": "漸化式と数学的帰納法", "tag": "漸化式・S_nとの関係・帰納法", "problems": [
  {"group": "漸化式の基本", "level": "basic",
   "stem": "$a_{1}=1,\\ a_{n+1}=a_{n}+3$ で定まる数列の一般項 $a_{n}$ を求めよ。",
   "answer": "$a_{n}=3n-2$", "explanation": "「前の項に $3$ を足す」= 公差 $3$ の等差数列。$a_{n}=1+(n-1)\\cdot3=3n-2$。",
   "chk": lambda: [3 * i - 2 for i in range(1, 6)] == [1, 4, 7, 10, 13]},
  {"group": "漸化式の基本", "level": "basic",
   "stem": "$a_{1}=2,\\ a_{n+1}=3a_{n}$ で定まる数列の一般項 $a_{n}$ を求めよ。",
   "answer": "$a_{n}=2\\cdot3^{\\,n-1}$", "explanation": "「前の項を $3$ 倍」= 公比 $3$ の等比数列。$a_{n}=2\\cdot3^{\\,n-1}$。",
   "chk": lambda: [2 * 3 ** (i - 1) for i in range(1, 5)] == [2, 6, 18, 54]},
  {"group": "漸化式の基本", "level": "basic",
   "stem": "$a_{1}=5,\\ a_{n+1}=a_{n}-2$ で定まる数列の第 $10$ 項を求めよ。",
   "answer": "$-13$", "explanation": "公差 $-2$ の等差数列。$a_{n}=5-2(n-1)=7-2n$。$a_{10}=7-20=-13$。",
   "chk": lambda: 7 - 2 * 10 == -13},
  {"group": "特性方程式型・階差型", "level": "standard",
   "stem": "$a_{1}=1,\\ a_{n+1}=2a_{n}+1$ で定まる数列の一般項 $a_{n}$ を求めよ。",
   "answer": "$a_{n}=2^{n}-1$", "explanation": "両辺に $1$ を足すと $a_{n+1}+1=2(a_{n}+1)$。$\\{a_{n}+1\\}$ は初項 $2$、公比 $2$ の等比。$a_{n}+1=2^{n}$、$a_{n}=2^{n}-1$。",
   "chk": lambda: [2 ** i - 1 for i in range(1, 6)] == [1, 3, 7, 15, 31]},
  {"group": "特性方程式型・階差型", "level": "standard",
   "stem": "$a_{1}=3,\\ a_{n+1}=2a_{n}-1$ で定まる数列の一般項 $a_{n}$ を求めよ。",
   "answer": "$a_{n}=2^{n}+1$", "explanation": "両辺から $1$ を引くと $a_{n+1}-1=2(a_{n}-1)$。$\\{a_{n}-1\\}$ は初項 $2$、公比 $2$。$a_{n}-1=2^{n}$、$a_{n}=2^{n}+1$。",
   "chk": lambda: [2 ** i + 1 for i in range(1, 5)] == [3, 5, 9, 17]},
  {"group": "特性方程式型・階差型", "level": "standard",
   "stem": "$a_{1}=1,\\ a_{n+1}=a_{n}+2n$ で定まる数列の一般項 $a_{n}$ を求めよ(階差型)。",
   "answer": "$a_{n}=n^{2}-n+1$", "explanation": "階差が $2n$。$a_{n}=1+\\sum_{k=1}^{n-1}2k=1+(n-1)n=n^{2}-n+1$。",
   "chk": lambda: [i ** 2 - i + 1 for i in range(1, 6)] == [1, 3, 7, 13, 21]},
  {"group": "和 $S_{n}$ と一般項", "level": "standard",
   "stem": "数列の初項から第 $n$ 項までの和が $S_{n}=n^{2}+2n$ であるとき、一般項 $a_{n}$ を求めよ。",
   "answer": "$a_{n}=2n+1$", "explanation": "$a_{1}=S_{1}=3$。$n\\geqq2$ で $a_{n}=S_{n}-S_{n-1}=(n^{2}+2n)-\\{(n-1)^{2}+2(n-1)\\}=2n+1$。$n=1$ でも成立。",
   "chk": lambda: all(((i * i + 2 * i) - ((i - 1) ** 2 + 2 * (i - 1))) == 2 * i + 1 for i in range(1, 6))},
  {"group": "和 $S_{n}$ と一般項", "level": "standard",
   "stem": "数列の初項から第 $n$ 項までの和が $S_{n}=2^{n}-1$ であるとき、一般項 $a_{n}$ を求めよ。",
   "answer": "$a_{n}=2^{\\,n-1}$", "explanation": "$a_{1}=S_{1}=1$。$n\\geqq2$ で $a_{n}=S_{n}-S_{n-1}=(2^{n}-1)-(2^{\\,n-1}-1)=2^{\\,n-1}$。$n=1$ でも成立。",
   "chk": lambda: all(((2 ** i - 1) - (2 ** (i - 1) - 1)) == 2 ** (i - 1) for i in range(1, 6))},
  {"group": "数学的帰納法", "level": "standard",
   "stem": "数学的帰納法を用いて、すべての自然数 $n$ について $1+2+3+\\cdots+n=\\dfrac{n(n+1)}{2}$ が成り立つことを証明せよ。",
   "answer": "(証明:解説参照)",
   "explanation": "(i) $n=1$ のとき、左辺 $=1$、右辺 $=\\dfrac{1\\cdot2}{2}=1$ で成立。(ii) $n=k$ で成立と仮定すると $1+\\cdots+k=\\dfrac{k(k+1)}{2}$。両辺に $k+1$ を加えると、左辺 $=1+\\cdots+k+(k+1)=\\dfrac{k(k+1)}{2}+(k+1)=\\dfrac{(k+1)(k+2)}{2}$ となり $n=k+1$ でも成立。(i)(ii) よりすべての自然数 $n$ で成り立つ。",
   "chk": lambda: all(sum(range(1, mm + 1)) == mm * (mm + 1) // 2 for mm in range(1, 9))},
  {"group": "数学的帰納法", "level": "advanced",
   "stem": "数学的帰納法を用いて、すべての自然数 $n$ について $1^{2}+2^{2}+\\cdots+n^{2}=\\dfrac{n(n+1)(2n+1)}{6}$ が成り立つことを証明せよ。",
   "answer": "(証明:解説参照)",
   "explanation": "(i) $n=1$ で左辺 $=1$、右辺 $=\\dfrac{1\\cdot2\\cdot3}{6}=1$。(ii) $n=k$ で成立と仮定し両辺に $(k+1)^{2}$ を加えると、右辺 $=\\dfrac{k(k+1)(2k+1)}{6}+(k+1)^{2}=\\dfrac{(k+1)(k+2)(2k+3)}{6}$ となり $n=k+1$ でも成立。よってすべての自然数 $n$ で成り立つ。",
   "chk": lambda: all(sum(i * i for i in range(1, mm + 1)) == mm * (mm + 1) * (2 * mm + 1) // 6 for mm in range(1, 9))},
]}

# ============================================================================
#  第3編  ベクトル  (平面の基本 → 内積 → 位置ベクトルと図形 → 空間ベクトル)
# ============================================================================

U_vbasic = {"name": "平面ベクトルの基本", "tag": "和・差・実数倍・成分・大きさ", "problems": [
  {"group": "ベクトルの演算", "level": "basic",
   "stem": "$\\vec{a}=(2,\\,3),\\ \\vec{b}=(-1,\\,4)$ のとき、$\\vec{a}+\\vec{b}$ を成分で表せ。",
   "answer": "$(1,\\,7)$", "explanation": "成分どうしを足す。$(2+(-1),\\ 3+4)=(1,\\,7)$。",
   "chk": lambda: Matrix([2, 3]) + Matrix([-1, 4]) == Matrix([1, 7])},
  {"group": "ベクトルの演算", "level": "basic",
   "stem": "$\\vec{a}=(2,\\,3),\\ \\vec{b}=(-1,\\,4)$ のとき、$\\vec{a}-\\vec{b}$ を成分で表せ。",
   "answer": "$(3,\\,-1)$", "explanation": "成分どうしを引く。$(2-(-1),\\ 3-4)=(3,\\,-1)$。",
   "chk": lambda: Matrix([2, 3]) - Matrix([-1, 4]) == Matrix([3, -1])},
  {"group": "ベクトルの演算", "level": "basic",
   "stem": "$\\vec{a}=(2,\\,-1)$ のとき、$3\\vec{a}$ を成分で表せ。",
   "answer": "$(6,\\,-3)$", "explanation": "各成分を3倍。$(3\\cdot2,\\ 3\\cdot(-1))=(6,\\,-3)$。",
   "chk": lambda: 3 * Matrix([2, -1]) == Matrix([6, -3])},
  {"group": "ベクトルの演算", "level": "standard",
   "stem": "$\\vec{a}=(4,\\,-2),\\ \\vec{b}=(1,\\,3)$ のとき、$2\\vec{a}-3\\vec{b}$ を成分で表せ。",
   "answer": "$(5,\\,-13)$", "explanation": "$2\\vec{a}=(8,-4)$、$3\\vec{b}=(3,9)$。差は $(8-3,\\ -4-9)=(5,\\,-13)$。",
   "chk": lambda: 2 * Matrix([4, -2]) - 3 * Matrix([1, 3]) == Matrix([5, -13])},
  {"group": "大きさ", "level": "basic",
   "stem": "$\\vec{a}=(3,\\,4)$ の大きさ $|\\vec{a}|$ を求めよ。",
   "answer": "$5$", "explanation": "$|\\vec{a}|=\\sqrt{3^{2}+4^{2}}=\\sqrt{25}=5$。",
   "chk": lambda: sqrt(3 ** 2 + 4 ** 2) == 5},
  {"group": "大きさ", "level": "basic",
   "stem": "$\\vec{a}=(1,\\,-2)$ の大きさ $|\\vec{a}|$ を求めよ。",
   "answer": "$\\sqrt{5}$", "explanation": "$|\\vec{a}|=\\sqrt{1^{2}+(-2)^{2}}=\\sqrt{5}$。",
   "chk": lambda: sqrt(1 ** 2 + (-2) ** 2) == sqrt(5)},
  {"group": "大きさ", "level": "standard",
   "stem": "2点 $\\mathrm{A}(1,\\,2),\\ \\mathrm{B}(4,\\,6)$ について、$\\overrightarrow{\\mathrm{AB}}$ の成分と大きさ $|\\overrightarrow{\\mathrm{AB}}|$ を求めよ。",
   "answer": "$\\overrightarrow{\\mathrm{AB}}=(3,\\,4),\\ |\\overrightarrow{\\mathrm{AB}}|=5$", "explanation": "$\\overrightarrow{\\mathrm{AB}}=(4-1,\\ 6-2)=(3,4)$。大きさ $\\sqrt{3^{2}+4^{2}}=5$。",
   "chk": lambda: (Matrix([4, 6]) - Matrix([1, 2]) == Matrix([3, 4])) and (sqrt(3 ** 2 + 4 ** 2) == 5)},
  {"group": "大きさ", "level": "standard",
   "stem": "$\\vec{a}=(x,\\,3)$ の大きさが $5$ となるような正の数 $x$ を求めよ。",
   "answer": "$x=4$", "explanation": "$x^{2}+3^{2}=5^{2}$ より $x^{2}=16$、$x>0$ で $x=4$。",
   "chk": lambda: 4 ** 2 + 3 ** 2 == 25},
  {"group": "ベクトルの分解・平行", "level": "standard",
   "stem": "$\\vec{a}=(2,\\,1),\\ \\vec{b}=(1,\\,-1)$ のとき、$\\vec{c}=(4,\\,-1)$ を $\\vec{c}=s\\vec{a}+t\\vec{b}$ の形で表せ。",
   "answer": "$s=1,\\ t=2$", "explanation": "$2s+t=4,\\ s-t=-1$。辺々足して $3s=3$、$s=1,\\ t=2$。",
   "chk": lambda: 1 * Matrix([2, 1]) + 2 * Matrix([1, -1]) == Matrix([4, -1])},
  {"group": "ベクトルの分解・平行", "level": "standard",
   "stem": "$\\vec{a}=(2,\\,3),\\ \\vec{b}=(4,\\,k)$ が平行であるとき、$k$ の値を求めよ。",
   "answer": "$k=6$", "explanation": "平行条件は $2\\cdot k-3\\cdot4=0$。$2k=12$、$k=6$。",
   "chk": lambda: 2 * 6 - 3 * 4 == 0},
]}

U_naiseki = {"name": "ベクトルの内積", "tag": "定義・成分・なす角・垂直と平行", "problems": [
  {"group": "内積の計算", "level": "basic",
   "stem": "$\\vec{a}=(2,\\,3),\\ \\vec{b}=(4,\\,-1)$ の内積 $\\vec{a}\\cdot\\vec{b}$ を求めよ。",
   "answer": "$5$", "explanation": "成分の内積は $x$ 成分どうし・$y$ 成分どうしの積の和。$2\\cdot4+3\\cdot(-1)=8-3=5$。",
   "chk": lambda: Matrix([2, 3]).dot(Matrix([4, -1])) == 5},
  {"group": "内積の計算", "level": "basic",
   "stem": "$|\\vec{a}|=3,\\ |\\vec{b}|=4$ で、$\\vec{a}$ と $\\vec{b}$ のなす角が $60^{\\circ}$ のとき、$\\vec{a}\\cdot\\vec{b}$ を求めよ。",
   "answer": "$6$", "explanation": "$\\vec{a}\\cdot\\vec{b}=|\\vec{a}||\\vec{b}|\\cos\\theta=3\\cdot4\\cdot\\cos60^{\\circ}=12\\cdot\\dfrac{1}{2}=6$。",
   "chk": lambda: 3 * 4 * R(1, 2) == 6},
  {"group": "内積の計算", "level": "basic",
   "stem": "$\\vec{a}=(1,\\,2),\\ \\vec{b}=(3,\\,-1)$ の内積 $\\vec{a}\\cdot\\vec{b}$ を求めよ。",
   "answer": "$1$", "explanation": "$1\\cdot3+2\\cdot(-1)=3-2=1$。",
   "chk": lambda: Matrix([1, 2]).dot(Matrix([3, -1])) == 1},
  {"group": "なす角", "level": "standard",
   "stem": "$\\vec{a}=(1,\\,2),\\ \\vec{b}=(3,\\,1)$ のなす角 $\\theta$ を求めよ。",
   "answer": "$\\theta=45^{\\circ}$", "explanation": "$\\cos\\theta=\\dfrac{\\vec{a}\\cdot\\vec{b}}{|\\vec{a}||\\vec{b}|}=\\dfrac{5}{\\sqrt{5}\\sqrt{10}}=\\dfrac{5}{5\\sqrt{2}}=\\dfrac{1}{\\sqrt{2}}$。よって $\\theta=45^{\\circ}$。",
   "chk": lambda: (lambda A, B: simplify(A.dot(B) / (sqrt(A.dot(A)) * sqrt(B.dot(B))) - 1 / sqrt(2)) == 0)(Matrix([1, 2]), Matrix([3, 1]))},
  {"group": "なす角", "level": "standard",
   "stem": "$\\vec{a}=(1,\\,\\sqrt{3}),\\ \\vec{b}=(\\sqrt{3},\\,1)$ のなす角 $\\theta$ を求めよ。",
   "answer": "$\\theta=30^{\\circ}$", "explanation": "$\\vec{a}\\cdot\\vec{b}=\\sqrt{3}+\\sqrt{3}=2\\sqrt{3}$、$|\\vec{a}|=|\\vec{b}|=2$。$\\cos\\theta=\\dfrac{2\\sqrt{3}}{4}=\\dfrac{\\sqrt{3}}{2}$、$\\theta=30^{\\circ}$。",
   "chk": lambda: (lambda A, B: simplify(A.dot(B) / (sqrt(A.dot(A)) * sqrt(B.dot(B))) - sqrt(3) / 2) == 0)(Matrix([1, sqrt(3)]), Matrix([sqrt(3), 1]))},
  {"group": "なす角", "level": "standard",
   "stem": "$\\vec{a}=(1,\\,0),\\ \\vec{b}=(-1,\\,1)$ のなす角 $\\theta$ を求めよ。",
   "answer": "$\\theta=135^{\\circ}$", "explanation": "$\\vec{a}\\cdot\\vec{b}=-1$、$|\\vec{a}|=1,\\ |\\vec{b}|=\\sqrt{2}$。$\\cos\\theta=\\dfrac{-1}{\\sqrt{2}}$、$\\theta=135^{\\circ}$。",
   "chk": lambda: (lambda A, B: simplify(A.dot(B) / (sqrt(A.dot(A)) * sqrt(B.dot(B))) + 1 / sqrt(2)) == 0)(Matrix([1, 0]), Matrix([-1, 1]))},
  {"group": "垂直・平行", "level": "basic",
   "stem": "$\\vec{a}=(3,\\,2),\\ \\vec{b}=(4,\\,k)$ が垂直であるとき、$k$ の値を求めよ。",
   "answer": "$k=-6$", "explanation": "垂直 $\\Longleftrightarrow$ 内積 $0$。$3\\cdot4+2\\cdot k=0$、$12+2k=0$、$k=-6$。",
   "chk": lambda: 3 * 4 + 2 * (-6) == 0},
  {"group": "垂直・平行", "level": "standard",
   "stem": "$\\vec{a}=(2,\\,-1)$ に垂直な単位ベクトルを求めよ。",
   "answer": "$\\pm\\left(\\dfrac{\\sqrt{5}}{5},\\ \\dfrac{2\\sqrt{5}}{5}\\right)$", "explanation": "$\\vec{a}$ に垂直なベクトルの1つは $(1,2)$($2\\cdot1+(-1)\\cdot2=0$)。大きさ $\\sqrt{5}$ で割って $\\pm\\dfrac{1}{\\sqrt{5}}(1,2)$。",
   "chk": lambda: (2 * 1 + (-1) * 2 == 0) and (1 ** 2 + 2 ** 2 == 5)},
  {"group": "内積と大きさ", "level": "standard",
   "stem": "$\\vec{a}+\\vec{b}=(5,\\,1),\\ \\vec{a}-\\vec{b}=(1,\\,3)$ のとき、内積 $\\vec{a}\\cdot\\vec{b}$ を求めよ。",
   "answer": "$4$", "explanation": "足して $2\\vec{a}=(6,4)$、$\\vec{a}=(3,2)$。引いて $2\\vec{b}=(4,-2)$、$\\vec{b}=(2,-1)$。$\\vec{a}\\cdot\\vec{b}=6-2=4$。",
   "chk": lambda: Matrix([3, 2]).dot(Matrix([2, -1])) == 4},
  {"group": "内積と大きさ", "level": "standard",
   "stem": "$|\\vec{a}|=2,\\ |\\vec{b}|=3,\\ \\vec{a}\\cdot\\vec{b}=-1$ のとき、$|\\vec{a}+\\vec{b}|$ を求めよ。",
   "answer": "$\\sqrt{11}$", "explanation": "$|\\vec{a}+\\vec{b}|^{2}=|\\vec{a}|^{2}+2\\vec{a}\\cdot\\vec{b}+|\\vec{b}|^{2}=4+2(-1)+9=11$。よって $\\sqrt{11}$。",
   "chk": lambda: sqrt(4 + 2 * (-1) + 9) == sqrt(11)},
]}

U_ichi = {"name": "位置ベクトルと図形", "tag": "内分点・外分点・重心・共線条件", "problems": [
  {"group": "内分点・外分点・中点", "level": "basic",
   "stem": "2点 $\\mathrm{A}(1,\\,2),\\ \\mathrm{B}(7,\\,5)$ を結ぶ線分 AB を $2:1$ に内分する点 P の座標を求めよ。",
   "answer": "$(5,\\,4)$", "explanation": "$m:n$ の内分点は $\\dfrac{n\\mathrm{A}+m\\mathrm{B}}{m+n}$。$\\dfrac{1\\cdot(1,2)+2\\cdot(7,5)}{3}=\\dfrac{(15,12)}{3}=(5,4)$。",
   "chk": lambda: ((1 * 1 + 2 * 7) // 3, (1 * 2 + 2 * 5) // 3) == (5, 4)},
  {"group": "内分点・外分点・中点", "level": "basic",
   "stem": "2点 $\\mathrm{A}(2,\\,1),\\ \\mathrm{B}(8,\\,4)$ の中点 M の座標を求めよ。",
   "answer": "$\\left(5,\\ \\dfrac{5}{2}\\right)$", "explanation": "中点は $\\left(\\dfrac{2+8}{2},\\ \\dfrac{1+4}{2}\\right)=\\left(5,\\ \\dfrac{5}{2}\\right)$。",
   "chk": lambda: (R(2 + 8, 2) == 5) and (R(1 + 4, 2) == R(5, 2))},
  {"group": "内分点・外分点・中点", "level": "standard",
   "stem": "2点 $\\mathrm{A}(1,\\,2),\\ \\mathrm{B}(7,\\,5)$ を結ぶ線分 AB を $2:1$ に外分する点 Q の座標を求めよ。",
   "answer": "$(13,\\,8)$", "explanation": "$m:n$ の外分点は $\\dfrac{-n\\mathrm{A}+m\\mathrm{B}}{m-n}$。$\\dfrac{-(1,2)+2(7,5)}{2-1}=(-1+14,\\ -2+10)=(13,8)$。",
   "chk": lambda: (-1 * 1 + 2 * 7, -1 * 2 + 2 * 5) == (13, 8)},
  {"group": "内分点・外分点・中点", "level": "standard",
   "stem": "$\\overrightarrow{\\mathrm{OA}}=\\vec{a},\\ \\overrightarrow{\\mathrm{OB}}=\\vec{b}$ のとき、線分 AB を $3:2$ に内分する点 P の位置ベクトル $\\overrightarrow{\\mathrm{OP}}$ を $\\vec{a},\\vec{b}$ で表せ。",
   "answer": "$\\overrightarrow{\\mathrm{OP}}=\\dfrac{2\\vec{a}+3\\vec{b}}{5}$", "explanation": "$m:n$ の内分は $\\dfrac{n\\vec{a}+m\\vec{b}}{m+n}=\\dfrac{2\\vec{a}+3\\vec{b}}{5}$。",
   "chk": lambda: Matrix([1, 0]) + R(3, 5) * (Matrix([0, 1]) - Matrix([1, 0])) == (2 * Matrix([1, 0]) + 3 * Matrix([0, 1])) / 5},
  {"group": "重心", "level": "basic",
   "stem": "三角形 ABC の頂点が $\\mathrm{A}(1,\\,1),\\ \\mathrm{B}(5,\\,2),\\ \\mathrm{C}(3,\\,6)$ のとき、重心 G の座標を求めよ。",
   "answer": "$(3,\\,3)$", "explanation": "重心は3頂点の平均。$\\left(\\dfrac{1+5+3}{3},\\ \\dfrac{1+2+6}{3}\\right)=(3,3)$。",
   "chk": lambda: ((1 + 5 + 3) // 3, (1 + 2 + 6) // 3) == (3, 3)},
  {"group": "重心", "level": "standard",
   "stem": "三角形 ABC の頂点の位置ベクトルを $\\vec{a},\\vec{b},\\vec{c}$ とするとき、重心 G の位置ベクトル $\\overrightarrow{\\mathrm{OG}}$ を求めよ。",
   "answer": "$\\overrightarrow{\\mathrm{OG}}=\\dfrac{\\vec{a}+\\vec{b}+\\vec{c}}{3}$", "explanation": "重心は3頂点の位置ベクトルの平均。$\\overrightarrow{\\mathrm{OG}}=\\dfrac{\\vec{a}+\\vec{b}+\\vec{c}}{3}$。",
   "chk": lambda: (Matrix([1, 1]) + Matrix([5, 2]) + Matrix([3, 6])) / 3 == Matrix([3, 3])},
  {"group": "共線条件・一次独立", "level": "standard",
   "stem": "3点 $\\mathrm{A}(1,\\,2),\\ \\mathrm{B}(4,\\,3),\\ \\mathrm{C}(10,\\,5)$ が一直線上にあることを示せ。",
   "answer": "$\\overrightarrow{\\mathrm{AC}}=3\\overrightarrow{\\mathrm{AB}}$ より共線",
   "explanation": "$\\overrightarrow{\\mathrm{AB}}=(3,1)$、$\\overrightarrow{\\mathrm{AC}}=(9,3)=3(3,1)=3\\overrightarrow{\\mathrm{AB}}$。同じ点 A から出て平行なので3点は一直線上にある。",
   "chk": lambda: (Matrix([10, 5]) - Matrix([1, 2])) == 3 * (Matrix([4, 3]) - Matrix([1, 2]))},
  {"group": "共線条件・一次独立", "level": "standard",
   "stem": "$\\vec{a},\\vec{b}$ は $\\vec{0}$ でなく平行でない(一次独立)とする。$s\\vec{a}+t\\vec{b}=2\\vec{a}-3\\vec{b}$ が成り立つとき、$s,t$ の値を求めよ。",
   "answer": "$s=2,\\ t=-3$", "explanation": "一次独立なベクトルでは係数を比較してよい。$s=2,\\ t=-3$。",
   "chk": lambda: (2, -3) == (2, -3)},
  {"group": "共線条件・一次独立", "level": "standard",
   "stem": "平行四辺形 ABCD で $\\overrightarrow{\\mathrm{AB}}=\\vec{b},\\ \\overrightarrow{\\mathrm{AD}}=\\vec{d}$ とする。対角線の交点を M とするとき、$\\overrightarrow{\\mathrm{AM}}$ を $\\vec{b},\\vec{d}$ で表せ。",
   "answer": "$\\overrightarrow{\\mathrm{AM}}=\\dfrac{1}{2}\\vec{b}+\\dfrac{1}{2}\\vec{d}$", "explanation": "M は対角線 AC の中点。$\\overrightarrow{\\mathrm{AC}}=\\vec{b}+\\vec{d}$ なので $\\overrightarrow{\\mathrm{AM}}=\\dfrac{1}{2}(\\vec{b}+\\vec{d})$。",
   "chk": lambda: (Matrix([2, 0]) + Matrix([0, 2])) / 2 == Matrix([1, 1])},
]}

U_kukan = {"name": "空間ベクトル", "tag": "成分・大きさ・距離・内積", "problems": [
  {"group": "空間の点とベクトル", "level": "basic",
   "stem": "空間の2点 $\\mathrm{A}(1,\\,2,\\,3),\\ \\mathrm{B}(4,\\,6,\\,3)$ について、$\\overrightarrow{\\mathrm{AB}}$ を成分で表せ。",
   "answer": "$(3,\\,4,\\,0)$", "explanation": "$\\overrightarrow{\\mathrm{AB}}=(4-1,\\ 6-2,\\ 3-3)=(3,4,0)$。",
   "chk": lambda: Matrix([4, 6, 3]) - Matrix([1, 2, 3]) == Matrix([3, 4, 0])},
  {"group": "空間の点とベクトル", "level": "basic",
   "stem": "$\\vec{a}=(2,\\,-1,\\,2)$ の大きさ $|\\vec{a}|$ を求めよ。",
   "answer": "$3$", "explanation": "$|\\vec{a}|=\\sqrt{2^{2}+(-1)^{2}+2^{2}}=\\sqrt{9}=3$。",
   "chk": lambda: sqrt(2 ** 2 + (-1) ** 2 + 2 ** 2) == 3},
  {"group": "空間の点とベクトル", "level": "basic",
   "stem": "2点 $\\mathrm{A}(1,\\,0,\\,2),\\ \\mathrm{B}(3,\\,4,\\,6)$ 間の距離 AB を求めよ。",
   "answer": "$6$", "explanation": "$\\mathrm{AB}=\\sqrt{(3-1)^{2}+(4-0)^{2}+(6-2)^{2}}=\\sqrt{4+16+16}=\\sqrt{36}=6$。",
   "chk": lambda: sqrt((3 - 1) ** 2 + (4 - 0) ** 2 + (6 - 2) ** 2) == 6},
  {"group": "空間ベクトルの演算・内積", "level": "basic",
   "stem": "$\\vec{a}=(1,\\,2,\\,-1),\\ \\vec{b}=(3,\\,-1,\\,2)$ の内積 $\\vec{a}\\cdot\\vec{b}$ を求めよ。",
   "answer": "$-1$", "explanation": "$1\\cdot3+2\\cdot(-1)+(-1)\\cdot2=3-2-2=-1$。",
   "chk": lambda: Matrix([1, 2, -1]).dot(Matrix([3, -1, 2])) == -1},
  {"group": "空間ベクトルの演算・内積", "level": "basic",
   "stem": "$\\vec{a}=(2,\\,1,\\,-2),\\ \\vec{b}=(1,\\,0,\\,3)$ のとき、$\\vec{a}+2\\vec{b}$ を成分で表せ。",
   "answer": "$(4,\\,1,\\,4)$", "explanation": "$2\\vec{b}=(2,0,6)$。$\\vec{a}+2\\vec{b}=(2+2,\\ 1+0,\\ -2+6)=(4,1,4)$。",
   "chk": lambda: Matrix([2, 1, -2]) + 2 * Matrix([1, 0, 3]) == Matrix([4, 1, 4])},
  {"group": "空間ベクトルの演算・内積", "level": "standard",
   "stem": "$\\vec{a}=(1,\\,1,\\,0),\\ \\vec{b}=(1,\\,0,\\,1)$ のなす角 $\\theta$ を求めよ。",
   "answer": "$\\theta=60^{\\circ}$", "explanation": "$\\vec{a}\\cdot\\vec{b}=1$、$|\\vec{a}|=|\\vec{b}|=\\sqrt{2}$。$\\cos\\theta=\\dfrac{1}{2}$、$\\theta=60^{\\circ}$。",
   "chk": lambda: (lambda A, B: simplify(A.dot(B) / (sqrt(A.dot(A)) * sqrt(B.dot(B))) - R(1, 2)) == 0)(Matrix([1, 1, 0]), Matrix([1, 0, 1]))},
  {"group": "空間ベクトルの演算・内積", "level": "standard",
   "stem": "$\\vec{a}=(1,\\,2,\\,2)$ と $\\vec{b}=(2,\\,k,\\,1)$ が垂直であるとき、$k$ の値を求めよ。",
   "answer": "$k=-2$", "explanation": "内積 $0$。$1\\cdot2+2\\cdot k+2\\cdot1=0$、$2k+4=0$、$k=-2$。",
   "chk": lambda: 1 * 2 + 2 * (-2) + 2 * 1 == 0},
  {"group": "空間ベクトルの演算・内積", "level": "standard",
   "stem": "$\\vec{a}=(2,\\,-2,\\,1)$ と同じ向きの単位ベクトルを求めよ。",
   "answer": "$\\left(\\dfrac{2}{3},\\ -\\dfrac{2}{3},\\ \\dfrac{1}{3}\\right)$", "explanation": "$|\\vec{a}|=\\sqrt{4+4+1}=3$。$\\dfrac{1}{3}\\vec{a}=\\left(\\dfrac{2}{3},-\\dfrac{2}{3},\\dfrac{1}{3}\\right)$。",
   "chk": lambda: (R(2, 3) ** 2 + R(-2, 3) ** 2 + R(1, 3) ** 2) == 1},
  {"group": "座標空間の図形", "level": "standard",
   "stem": "3点 $\\mathrm{A}(1,\\,0,\\,0),\\ \\mathrm{B}(0,\\,1,\\,0),\\ \\mathrm{C}(0,\\,0,\\,1)$ を頂点とする三角形の重心 G の座標を求めよ。",
   "answer": "$\\left(\\dfrac{1}{3},\\ \\dfrac{1}{3},\\ \\dfrac{1}{3}\\right)$", "explanation": "重心は3頂点の平均。各座標 $\\dfrac{1+0+0}{3}=\\dfrac{1}{3}$。",
   "chk": lambda: (Matrix([1, 0, 0]) + Matrix([0, 1, 0]) + Matrix([0, 0, 1])) / 3 == Matrix([R(1, 3), R(1, 3), R(1, 3)])},
  {"group": "座標空間の図形", "level": "standard",
   "stem": "$\\vec{a}=(1,\\,2,\\,2),\\ \\vec{b}=(2,\\,-1,\\,2)$ のとき、$|\\vec{a}+\\vec{b}|$ を求めよ。",
   "answer": "$\\sqrt{26}$", "explanation": "$\\vec{a}+\\vec{b}=(3,1,4)$。$|\\vec{a}+\\vec{b}|=\\sqrt{3^{2}+1^{2}+4^{2}}=\\sqrt{26}$。",
   "chk": lambda: sqrt(3 ** 2 + 1 ** 2 + 4 ** 2) == sqrt(26)},
]}

# ---------------------------------------------------------------------------
PARTS = [
  {"area": "第1編　確率", "sub": "場合の数から確率の考え方まで、基礎の基礎を徹底する",
   "units": [U_kazoe, U_junkumi, U_kakuritsu, U_iroiro]},
  {"area": "第2編　数列", "sub": "等差・等比からΣ・漸化式まで、公式を使いこなす",
   "units": [U_tousa, U_touhi, U_sigma, U_zenka]},
  {"area": "第3編　ベクトル", "sub": "成分・大きさ・内積から図形への応用まで積み上げる",
   "units": [U_vbasic, U_naiseki, U_ichi, U_kukan]},
]

# verify.py / build_html は UNITS を参照する。PARTS を平坦化して両対応にする。
UNITS = [u for p in PARTS for u in p["units"]]
