# -*- coding: utf-8 -*-
"""数学I·A 弱点発見トレーニング の【塾長用】弱点診断マップ。
★生徒には見せない(どの問題が何を測るかを知られると診断精度が落ちる)。
MAP のキーは「単元コード-問題番号」(印刷版の番号と同一・接頭辞 A 必須)。
head は content_ia_jaku とのドリフト検知用(先頭40字)。

★このファイルは自動生成。手で編集しない → `python3 gen_diagnosis_ia_jaku.py`
"""
from _ia_jaku_lib import SKILLS, PREREQ   # noqa: F401  (analyze 側が参照する)

LEVEL_W = {'basic': 1.5, 'standard': 1.0, 'advanced': 0.6}   # 基礎ミスほど重い
ROLE_W = {'primary': 1.0, 'sub': 0.4}

UNITS_INFO = [{'code': 'A01', 'name': '展開と因数分解', 'count': 7},
 {'code': 'A02', 'name': '実数・平方根・式の値', 'count': 7},
 {'code': 'A03', 'name': '1次不等式と絶対値', 'count': 6},
 {'code': 'A04', 'name': '集合と要素の個数', 'count': 6},
 {'code': 'A05', 'name': '命題と条件・対偶・背理法', 'count': 8},
 {'code': 'A06', 'name': '2次関数のグラフ', 'count': 7},
 {'code': 'A07', 'name': '2次関数の最大・最小', 'count': 7},
 {'code': 'A08', 'name': '2次方程式と判別式', 'count': 7},
 {'code': 'A09', 'name': '2次不等式と解の配置', 'count': 6},
 {'code': 'A10', 'name': '三角比の基本と相互関係', 'count': 7},
 {'code': 'A11', 'name': '正弦定理・余弦定理', 'count': 7},
 {'code': 'A12', 'name': '三角形の面積と空間図形', 'count': 7},
 {'code': 'A13', 'name': '代表値・四分位数・標準偏差', 'count': 7},
 {'code': 'A14', 'name': '相関係数と仮説検定の考え方', 'count': 5},
 {'code': 'A15', 'name': '場合の数（順列・組合せ）', 'count': 7},
 {'code': 'A16', 'name': '確率の計算', 'count': 10},
 {'code': 'A17', 'name': '図形の性質', 'count': 9},
 {'code': 'A18', 'name': '整数の性質（数学と人間の活動）', 'count': 9}]

MAP = {'A01-1': {'skill': 'SK1',
           'sub': [],
           'level': 'basic',
           'group': '展開の公式（形を見て当てはめる）',
           'head': '$(2a-5b)^{2}$ を展開せよ。'},
 'A01-2': {'skill': 'SK1',
           'sub': [],
           'level': 'basic',
           'group': '展開の公式（形を見て当てはめる）',
           'head': '$(x+2)(x-2)(x^{2}+4)$ を展開せよ。'},
 'A01-3': {'skill': 'SK2',
           'sub': [],
           'level': 'basic',
           'group': 'たすきがけの因数分解',
           'head': '$x^{2}+2x-24$ を因数分解せよ。'},
 'A01-4': {'skill': 'SK2',
           'sub': [],
           'level': 'standard',
           'group': 'たすきがけの因数分解',
           'head': '$6x^{2}-x-12$ を因数分解せよ。'},
 'A01-5': {'skill': 'SK2',
           'sub': ['SK1'],
           'level': 'standard',
           'group': '置き換えて因数分解',
           'head': '$(x^{2}+3x)^{2}-2(x^{2}+3x)-8$ を因数分解せよ。'},
 'A01-6': {'skill': 'SK2',
           'sub': ['SK1'],
           'level': 'standard',
           'group': '置き換えて因数分解',
           'head': '$x^{2}-y^{2}+4y-4$ を因数分解せよ。'},
 'A01-7': {'skill': 'SK2',
           'sub': ['SK1'],
           'level': 'advanced',
           'group': '2文字の2次式（たすきがけを2回）',
           'head': '$x^{2}+3xy+2y^{2}+2x+3y+1$ を因数分解せよ。'},
 'A02-1': {'skill': 'SK4',
           'sub': ['SK6'],
           'level': 'basic',
           'group': '根号のはずし方',
           'head': '$\\sqrt{(\\sqrt{3}-2)^{2}}+\\sqrt{(\\sqrt{3}'},
 'A02-2': {'skill': 'SK4',
           'sub': ['SK6'],
           'level': 'basic',
           'group': '根号のはずし方',
           'head': '$\\sqrt{(\\sqrt{5}-3)^{2}}+\\sqrt{(2-\\sqrt{'},
 'A02-3': {'skill': 'SK4',
           'sub': ['SK1'],
           'level': 'basic',
           'group': '分母の有理化',
           'head': '$\\dfrac{4}{3+\\sqrt{5}}-\\dfrac{4}{3-\\sqrt'},
 'A02-4': {'skill': 'SK4',
           'sub': ['SK1'],
           'level': 'standard',
           'group': '分母の有理化',
           'head': '$\\dfrac{\\sqrt{7}-\\sqrt{3}}{\\sqrt{7}+\\sqr'},
 'A02-5': {'skill': 'SK3',
           'sub': ['SK4', 'SK1'],
           'level': 'standard',
           'group': '対称式で値を求める',
           'head': '$x=\\dfrac{1}{\\sqrt{6}-\\sqrt{5}}$、$y=\\dfr'},
 'A02-6': {'skill': 'SK5',
           'sub': ['SK4'],
           'level': 'standard',
           'group': '二重根号と整数部分・小数部分',
           'head': '$\\sqrt{9+4\\sqrt{5}}$ の二重根号をはずして簡単にせよ。'},
 'A02-7': {'skill': 'SK5',
           'sub': ['SK4', 'SK3'],
           'level': 'advanced',
           'group': '二重根号と整数部分・小数部分',
           'head': '$x=\\sqrt{11+6\\sqrt{2}}$ とする。二重根号をはずして $x'},
 'A03-1': {'skill': 'SK7',
           'sub': [],
           'level': 'basic',
           'group': '1次不等式を解く',
           'head': '不等式 $4x+7 \\gt 6x+1$ を解け。'},
 'A03-2': {'skill': 'SK7',
           'sub': [],
           'level': 'standard',
           'group': '1次不等式を解く',
           'head': '不等式 $\\dfrac{x-2}{3} \\geqq \\dfrac{2x+1}{4'},
 'A03-3': {'skill': 'SK7',
           'sub': [],
           'level': 'standard',
           'group': '連立不等式と文字定数',
           'head': '連立不等式 $4x+3 \\gt x-6$ かつ $5-2x \\geqq x-4$'},
 'A03-4': {'skill': 'SK7',
           'sub': [],
           'level': 'standard',
           'group': '連立不等式と文字定数',
           'head': '$x$ についての連立不等式 $3x-2 \\gt x+4$ かつ $2x+1 \\'},
 'A03-5': {'skill': 'SK6',
           'sub': ['SK7'],
           'level': 'basic',
           'group': '絶対値を含む方程式・不等式',
           'head': '次を解け。<br>(1) 方程式 $|x-2|=6$<br>(2) 不等式 $|'},
 'A03-6': {'skill': 'SK6',
           'sub': ['SK7'],
           'level': 'advanced',
           'group': '絶対値を含む方程式・不等式',
           'head': '不等式 $|x-1|+|x-3| \\leqq 6$ を解け。'},
 'A04-1': {'skill': 'ST1',
           'sub': [],
           'level': 'basic',
           'group': '集合の演算（共通部分・和集合・補集合）',
           'head': '全体集合を $U=\\{1,2,3,\\ldots,20\\}$ とし、$A$ を $'},
 'A04-2': {'skill': 'ST1',
           'sub': [],
           'level': 'standard',
           'group': '集合の演算（共通部分・和集合・補集合）',
           'head': '全体集合を $U=\\{1,2,3,\\ldots,12\\}$ とし、$A=\\{2,'},
 'A04-3': {'skill': 'ST1',
           'sub': [],
           'level': 'basic',
           'group': '部分集合の個数',
           'head': '$A=\\{1,2,3,4,5\\}$ の部分集合は全部で何個あるか。また、そのうち'},
 'A04-4': {'skill': 'ST1',
           'sub': [],
           'level': 'standard',
           'group': '部分集合の個数',
           'head': '$B=\\{1,2,3,4,5,6,7\\}$ の部分集合のうち、$1$ を含むもの'},
 'A04-5': {'skill': 'ST2',
           'sub': ['ST1'],
           'level': 'standard',
           'group': '要素の個数を数える',
           'head': '$1$ から $250$ までの整数のうち、$4$ の倍数または $6$ の倍数'},
 'A04-6': {'skill': 'ST2',
           'sub': ['ST1'],
           'level': 'advanced',
           'group': '要素の個数を数える',
           'head': 'ある高校の生徒 $180$ 人に、通学で電車・バス・自転車を使うかどうかを調べた'},
 'A05-1': {'skill': 'ST3',
           'sub': [],
           'level': 'basic',
           'group': '命題の真偽と反例',
           'head': '次の命題の真偽を答えよ。偽であるものは反例を1つあげよ。<br>(1) 実数 $'},
 'A05-2': {'skill': 'ST3',
           'sub': ['QF1'],
           'level': 'basic',
           'group': '命題の真偽と反例',
           'head': '次の命題の真偽を答えよ。偽であるものは反例を1つあげよ。<br>(1) 実数 $'},
 'A05-3': {'skill': 'ST4',
           'sub': ['ST3'],
           'level': 'basic',
           'group': '必要条件・十分条件',
           'head': '実数 $x$ についての条件 $p:\\ x^{2}+x-6=0$、$q:\\ x='},
 'A05-4': {'skill': 'ST4',
           'sub': ['ST1'],
           'level': 'standard',
           'group': '必要条件・十分条件',
           'head': '実数 $x,\\ y$ について、次の条件 $p,\\ q$ を考える。$p$ は '},
 'A05-5': {'skill': 'ST5',
           'sub': ['ST3'],
           'level': 'standard',
           'group': '逆・裏・対偶と条件の否定',
           'head': '実数 $x$ についての命題「$x^{2}-3x+2=0$ ならば $x=1$」'},
 'A05-6': {'skill': 'ST5',
           'sub': ['ST1', 'SK7'],
           'level': 'standard',
           'group': '逆・裏・対偶と条件の否定',
           'head': '実数 $x,\\ y$ についての命題「$x+y\\gt 2$ ならば、$x\\gt '},
 'A05-7': {'skill': 'ST6',
           'sub': [],
           'level': 'advanced',
           'group': '背理法による証明',
           'head': '$a,\\ b$ を有理数とする。$\\sqrt{2}$ が無理数であることを用いて'},
 'A05-8': {'skill': 'ST6',
           'sub': ['ST5', 'IN5'],
           'level': 'standard',
           'group': '背理法による証明',
           'head': '$n$ を整数とする。次の問いに答えよ。<br>(1) 「$n^{2}$ が $'},
 'A06-1': {'skill': 'QF1',
           'sub': [],
           'level': 'basic',
           'group': '平方完成して頂点と軸を読む',
           'head': '2次関数 $y=2x^{2}-12x+11$ を $y=a(x-p)^{2}+q'},
 'A06-2': {'skill': 'QF1',
           'sub': [],
           'level': 'basic',
           'group': '平方完成して頂点と軸を読む',
           'head': '2次関数 $y=-2x^{2}+6x+1$ のグラフの頂点の座標と軸を求めよ。'},
 'A06-3': {'skill': 'QF1',
           'sub': [],
           'level': 'standard',
           'group': '平方完成して頂点と軸を読む',
           'head': '2次関数 $y=\\dfrac{1}{2}x^{2}+3x+1$ のグラフの頂点の'},
 'A06-4': {'skill': 'QF2',
           'sub': ['QF1'],
           'level': 'basic',
           'group': 'グラフの移動',
           'head': '放物線 $y=x^{2}+4x+1$（図はそのグラフ）を、$x$ 軸方向に $3'},
 'A06-5': {'skill': 'QF2',
           'sub': [],
           'level': 'standard',
           'group': 'グラフの移動',
           'head': '放物線 $y=x^{2}-2x-2$（図はそのグラフ）を、次のそれぞれに関して対'},
 'A06-6': {'skill': 'QF1',
           'sub': ['QF2'],
           'level': 'standard',
           'group': '条件から放物線を決める',
           'head': 'グラフの頂点が点 $(-1,\\ 4)$ で、点 $(1,\\ -8)$ を通る2次'},
 'A06-7': {'skill': 'QF1',
           'sub': [],
           'level': 'advanced',
           'group': '条件から放物線を決める',
           'head': 'グラフが3点 $(-1,\\ 6)$、$(1,\\ 0)$、$(2,\\ 3)$ を通'},
 'A07-1': {'skill': 'QF3',
           'sub': ['QF1'],
           'level': 'basic',
           'group': '定義域が決まっているときの最大・最小',
           'head': '2次関数 $y=x^{2}-6x+4$ の $0\\leqq x\\leqq 5$ '},
 'A07-2': {'skill': 'QF3',
           'sub': ['QF1'],
           'level': 'basic',
           'group': '定義域が決まっているときの最大・最小',
           'head': '2次関数 $y=-2x^{2}+8x-5$ の $3\\leqq x\\leqq 5'},
 'A07-3': {'skill': 'QF3',
           'sub': ['QF1'],
           'level': 'standard',
           'group': '定義域が決まっているときの最大・最小',
           'head': '2次関数 $y=2x^{2}-5x+1$ の $0\\leqq x\\leqq 2$'},
 'A07-4': {'skill': 'QF4',
           'sub': ['QF1'],
           'level': 'standard',
           'group': '軸や定義域に文字を含むとき',
           'head': '$a$ を定数とする。2次関数 $y=x^{2}-4ax+1$ の $0\\leq'},
 'A07-5': {'skill': 'QF4',
           'sub': ['QF1'],
           'level': 'advanced',
           'group': '軸や定義域に文字を含むとき',
           'head': '$a$ を定数とする。2次関数 $f(x)=x^{2}-2x+4$ の $a\\l'},
 'A07-6': {'skill': 'QF3',
           'sub': ['QF1'],
           'level': 'standard',
           'group': '置きかえて2次関数にする',
           'head': '$-1\\leqq x\\leqq 3$ のとき、$y=(x^{2}-2x)^{2}'},
 'A07-7': {'skill': 'QF3',
           'sub': ['QF1', 'SK7'],
           'level': 'standard',
           'group': '文章題（面積を最大にする）',
           'head': '長さ $20$ m の柵（さく）を使い、まっすぐな壁を1辺として利用して、図のよ'},
 'A08-1': {'skill': 'QF6',
           'sub': ['SK2'],
           'level': 'basic',
           'group': '2次方程式を解く（因数分解・解の公式）',
           'head': '2次方程式 $3x^{2}-11x+6=0$ を解け。'},
 'A08-2': {'skill': 'QF6',
           'sub': ['SK4'],
           'level': 'basic',
           'group': '2次方程式を解く（因数分解・解の公式）',
           'head': '2次方程式 $x^{2}-6x+2=0$ を解け。'},
 'A08-3': {'skill': 'QF6',
           'sub': ['SK4'],
           'level': 'standard',
           'group': '2次方程式を解く（因数分解・解の公式）',
           'head': '2次方程式 $3x^{2}-4x-2=0$ を解け。'},
 'A08-4': {'skill': 'QF5',
           'sub': ['QF6'],
           'level': 'basic',
           'group': '実数解の個数と共有点',
           'head': '次の2次方程式の実数解の個数を、それぞれ求めよ。<br>(1) $3x^{2}-'},
 'A08-5': {'skill': 'QF5',
           'sub': ['QF7'],
           'level': 'standard',
           'group': '実数解の個数と共有点',
           'head': '2次関数 $y=x^{2}-(k+1)x+k+9$ のグラフが $x$ 軸と共有'},
 'A08-6': {'skill': 'QF5',
           'sub': ['QF6'],
           'level': 'standard',
           'group': '判別式から定数を決める',
           'head': '2次方程式 $x^{2}+(k-3)x+k=0$ が重解をもつように定数 $k$'},
 'A08-7': {'skill': 'QF5',
           'sub': ['QF6'],
           'level': 'advanced',
           'group': '判別式から定数を決める',
           'head': '放物線 $y=x^{2}+3x+2$（図はそのグラフ）と直線 $y=x+k$ が'},
 'A09-1': {'skill': 'QF7',
           'sub': ['SK2'],
           'level': 'basic',
           'group': '2次不等式を解く',
           'head': '2次不等式 $2x^{2}-5x-3\\gt 0$ を解け。'},
 'A09-2': {'skill': 'QF7',
           'sub': ['SK2'],
           'level': 'basic',
           'group': '2次不等式を解く',
           'head': '2次不等式 $-x^{2}+6x-5\\geqq 0$ を解け。'},
 'A09-3': {'skill': 'QF7',
           'sub': ['QF5'],
           'level': 'standard',
           'group': '2次不等式を解く',
           'head': '次の2次不等式を解け。<br>(1) $9x^{2}-6x+1\\gt 0$\u3000(2'},
 'A09-4': {'skill': 'QF7',
           'sub': ['SK7', 'SK2'],
           'level': 'standard',
           'group': '連立2次不等式',
           'head': '連立不等式 $x^{2}-2x-15\\lt 0$ かつ $x^{2}-4x\\ge'},
 'A09-5': {'skill': 'QF8',
           'sub': ['QF5', 'QF7'],
           'level': 'standard',
           'group': '2次方程式の解の位置',
           'head': '2次方程式 $x^{2}-2(m-2)x+m+4=0$ が異なる2つの実数解をも'},
 'A09-6': {'skill': 'QF8',
           'sub': ['QF5', 'QF7'],
           'level': 'advanced',
           'group': '2次方程式の解の位置',
           'head': '2次方程式 $x^{2}-2(m-1)x+m+5=0$ について、次の条件を満た'},
 'A10-1': {'skill': 'TR1',
           'sub': [],
           'level': 'basic',
           'group': '直角三角形と三角定規の角',
           'head': '下の図のように、$\\angle\\mathrm{B}=90^\\circ$、$\\ma'},
 'A10-2': {'skill': 'TR1',
           'sub': [],
           'level': 'basic',
           'group': '直角三角形と三角定規の角',
           'head': '次の式の値をそれぞれ求めよ。<br>(1) $\\tan 30^\\circ\\tan'},
 'A10-3': {'skill': 'TR2',
           'sub': ['TR1'],
           'level': 'basic',
           'group': '1つの値から残りの2つを求める',
           'head': '鋭角 $\\theta$ が $\\cos\\theta=\\dfrac{8}{17}$'},
 'A10-4': {'skill': 'TR2',
           'sub': [],
           'level': 'standard',
           'group': '1つの値から残りの2つを求める',
           'head': '$0^\\circ\\leqq\\theta\\leqq 180^\\circ$ とする。'},
 'A10-5': {'skill': 'TR3',
           'sub': ['TR2'],
           'level': 'standard',
           'group': '余角と補角の言いかえ',
           'head': '$\\sin^{2}20^\\circ+\\sin^{2}70^\\circ+\\cos '},
 'A10-6': {'skill': 'TR2',
           'sub': ['SK3'],
           'level': 'standard',
           'group': '式の値（相互関係を使う）',
           'head': '$0^\\circ\\leqq\\theta\\leqq 180^\\circ$ とする。'},
 'A10-7': {'skill': 'TR2',
           'sub': ['TR1'],
           'level': 'advanced',
           'group': '式の値（相互関係を使う）',
           'head': '$0^\\circ\\leqq\\theta\\leqq 180^\\circ$ とする。'},
 'A11-1': {'skill': 'TR4',
           'sub': ['TR1'],
           'level': 'basic',
           'group': '角と向かい合う辺が分かっているとき',
           'head': '右の図の $\\triangle\\mathrm{ABC}$ で、$\\angle\\m'},
 'A11-2': {'skill': 'TR7',
           'sub': ['TR4', 'TR3'],
           'level': 'basic',
           'group': '角と向かい合う辺が分かっているとき',
           'head': '$\\triangle\\mathrm{ABC}$ で $\\angle\\mathrm'},
 'A11-3': {'skill': 'TR5',
           'sub': ['TR1'],
           'level': 'basic',
           'group': '2辺と挟む角から残りの辺',
           'head': '右の図の $\\triangle\\mathrm{ABC}$ で、$\\mathrm{'},
 'A11-4': {'skill': 'TR5',
           'sub': ['TR3'],
           'level': 'standard',
           'group': '2辺と挟む角から残りの辺',
           'head': '$\\triangle\\mathrm{ABC}$ で $\\mathrm{AB}=3'},
 'A11-5': {'skill': 'TR5',
           'sub': ['TR1'],
           'level': 'standard',
           'group': '3辺がわかっているとき',
           'head': '$\\triangle\\mathrm{ABC}$ で $\\mathrm{BC}=5'},
 'A11-6': {'skill': 'TR7',
           'sub': ['TR5', 'TR4'],
           'level': 'standard',
           'group': '3辺がわかっているとき',
           'head': '右の図の $\\triangle\\mathrm{ABC}$ で、$\\mathrm{'},
 'A11-7': {'skill': 'TR5',
           'sub': ['QF6'],
           'level': 'advanced',
           'group': '与えられた角が挟む角でないとき',
           'head': '$\\triangle\\mathrm{ABC}$ で $\\angle\\mathrm'},
 'A12-1': {'skill': 'TR6',
           'sub': ['TR3'],
           'level': 'basic',
           'group': '2辺とはさむ角で面積をとらえる',
           'head': '$\\triangle\\mathrm{ABC}$ において $\\mathrm{AB'},
 'A12-2': {'skill': 'TR6',
           'sub': ['TR3'],
           'level': 'standard',
           'group': '2辺とはさむ角で面積をとらえる',
           'head': '$\\triangle\\mathrm{ABC}$ において $\\mathrm{AB'},
 'A12-3': {'skill': 'TR6',
           'sub': ['TR5'],
           'level': 'basic',
           'group': '3辺だけが分かっているとき',
           'head': '3辺の長さが $4$、$13$、$15$ である三角形の面積 $S$ を求めよ。'},
 'A12-4': {'skill': 'TR7',
           'sub': ['TR6', 'TR4'],
           'level': 'standard',
           'group': '3辺だけが分かっているとき',
           'head': '3辺の長さが $\\mathrm{BC}=14$、$\\mathrm{CA}=13$'},
 'A12-5': {'skill': 'TR6',
           'sub': ['TR5'],
           'level': 'standard',
           'group': '三角形に切り分けて考える（四角形・空間）',
           'head': '右の図の四角形 $\\mathrm{ABCD}$ において、$\\mathrm{AB'},
 'A12-6': {'skill': 'TR8',
           'sub': ['TR5', 'TR6'],
           'level': 'advanced',
           'group': '三角形に切り分けて考える（四角形・空間）',
           'head': '右の図の直方体 $\\mathrm{ABCD}$-$\\mathrm{EFGH}$ '},
 'A12-7': {'skill': 'TR8',
           'sub': ['TR5', 'TR6'],
           'level': 'advanced',
           'group': '三角形に切り分けて考える（四角形・空間）',
           'head': '右の図のように、1辺の長さが $6$ の正四面体 $\\mathrm{ABCD}$'},
 'A13-1': {'skill': 'DA1',
           'sub': [],
           'level': 'basic',
           'group': '代表値を読み分ける',
           'head': '次の $9$ 個のデータは、ある生徒の小テスト（$15$ 点満点）$9$ 回分の'},
 'A13-2': {'skill': 'DA1',
           'sub': ['DA2'],
           'level': 'standard',
           'group': '代表値を読み分ける',
           'head': 'ある店の1日の来客数を $7$ 日間記録すると、次のようになった。<br>$21'},
 'A13-3': {'skill': 'DA2',
           'sub': ['DA1'],
           'level': 'basic',
           'group': '四分位数と箱ひげ図',
           'head': '次の $10$ 個のデータについて、範囲、$Q_{1}$、$Q_{2}$（中央値'},
 'A13-4': {'skill': 'DA2',
           'sub': ['DA1'],
           'level': 'standard',
           'group': '四分位数と箱ひげ図',
           'head': 'ある高校の1クラス $30$ 人が受けた小テスト（$10$ 点満点・得点は整数）'},
 'A13-5': {'skill': 'DA3',
           'sub': ['DA1'],
           'level': 'standard',
           'group': '散らばりの大きさをはかる',
           'head': '次の $6$ 個のデータについて、平均値・分散・標準偏差を求めよ。<br>$3,'},
 'A13-6': {'skill': 'DA5',
           'sub': ['DA3'],
           'level': 'standard',
           'group': '散らばりの大きさをはかる',
           'head': '$5$ 人の生徒について、ある作業でのミスの回数 $x$ は次のとおりであった。'},
 'A13-7': {'skill': 'DA5',
           'sub': ['DA3'],
           'level': 'advanced',
           'group': '散らばりの大きさをはかる',
           'head': 'あるロボット掃除機を $6$ 日間使い、1日の稼働時間 $x$（分）を記録すると'},
 'A14-1': {'skill': 'DA4',
           'sub': ['DA3'],
           'level': 'basic',
           'group': '散布図から相関を読み取る',
           'head': 'ある高校の生徒 $8$ 人について、1日のスマートフォンの使用時間 $x$（時間'},
 'A14-2': {'skill': 'DA4',
           'sub': ['DA3'],
           'level': 'basic',
           'group': '共分散と相関係数を計算する',
           'head': 'ある店で $5$ 日間、最高気温 $x$（度）と、かき氷の売れた杯数 $y$（杯'},
 'A14-3': {'skill': 'DA4',
           'sub': ['DA3'],
           'level': 'standard',
           'group': '共分散と相関係数を計算する',
           'head': '$5$ 人の生徒に $10$ 点満点の小テストを $2$ 回行い、$1$ 回目の'},
 'A14-4': {'skill': 'DA6',
           'sub': [],
           'level': 'standard',
           'group': '主張に反する仮定をおいて確かめる',
           'head': 'あるコインについて「表が出やすいのではないか」と考え、実際に $20$ 回投げた'},
 'A14-5': {'skill': 'DA6',
           'sub': [],
           'level': 'advanced',
           'group': '主張に反する仮定をおいて確かめる',
           'head': 'あるバスケットボール部員のフリースローの成功率は、これまで $50\\%$ であっ'},
 'A15-1': {'skill': 'CP1',
           'sub': [],
           'level': 'basic',
           'group': '数え方の土台（つなげるか、分けるか）',
           'head': 'あるカフェのメニューは、飲み物が $5$ 種類、ケーキが $4$ 種類、サンドイ'},
 'A15-2': {'skill': 'CP3',
           'sub': ['CP1', 'CP2'],
           'level': 'basic',
           'group': '数え方の土台（つなげるか、分けるか）',
           'head': '$0,\\ 1,\\ 2,\\ 3,\\ 4,\\ 5$ の $6$ 個の数字を使って $'},
 'A15-3': {'skill': 'CP2',
           'sub': ['CP1'],
           'level': 'standard',
           'group': '並べ方を数える（1列・円）',
           'head': '男子 $3$ 人、女子 $4$ 人の計 $7$ 人が $1$ 列に並ぶ。<br>'},
 'A15-4': {'skill': 'CP3',
           'sub': ['CP2'],
           'level': 'standard',
           'group': '並べ方を数える（1列・円）',
           'head': '大人 $2$ 人と子ども $4$ 人の計 $6$ 人が円形のテーブルに座る。大人'},
 'A15-5': {'skill': 'CP3',
           'sub': ['CP4'],
           'level': 'standard',
           'group': '並べ方を数える（1列・円）',
           'head': '英単語 SUCCESS の $7$ 文字をすべて使って $1$ 列に並べかえる。'},
 'A15-6': {'skill': 'CP4',
           'sub': ['CP2'],
           'level': 'basic',
           'group': '選び方・分け方を数える',
           'head': '$12$ 人の部員がいる。<br>(1) この中から代表 $3$ 人を選ぶ選び方'},
 'A15-7': {'skill': 'CP4',
           'sub': ['CP3'],
           'level': 'advanced',
           'group': '選び方・分け方を数える',
           'head': '$9$ 人を $3$ 人ずつ $3$ つの組に分ける。<br>(1) $\\mat'},
 'A16-1': {'skill': 'CP5',
           'sub': ['CP4'],
           'level': 'basic',
           'group': '確率の定義（場合の数の比として出す）',
           'head': '$1$ から $12$ までの番号が1つずつ書かれた $12$ 枚のカードから、'},
 'A16-2': {'skill': 'CP5',
           'sub': ['CP4'],
           'level': 'basic',
           'group': '確率の定義（場合の数の比として出す）',
           'head': '白玉 $5$ 個、青玉 $3$ 個が入った袋から、同時に $3$ 個取り出す。青'},
 'A16-3': {'skill': 'CP6',
           'sub': ['CP5'],
           'level': 'basic',
           'group': '余事象と和事象',
           'head': '$1$ から $40$ までの番号が1つずつ書かれた $40$ 枚の番号札から '},
 'A16-4': {'skill': 'CP6',
           'sub': ['CP4'],
           'level': 'standard',
           'group': '余事象と和事象',
           'head': '当たりくじ $4$ 本を含む $12$ 本のくじがある。この中から同時に $3$'},
 'A16-5': {'skill': 'CP7',
           'sub': ['CP4'],
           'level': 'standard',
           'group': 'くり返す試行（独立試行・反復試行）',
           'head': '毎回当たる確率が $\\dfrac{2}{5}$ のくじがある。引いたくじはそのつ'},
 'A16-6': {'skill': 'CP7',
           'sub': ['CP6'],
           'level': 'standard',
           'group': 'くり返す試行（独立試行・反復試行）',
           'head': '$1$ 回買うごとに確率 $\\dfrac{1}{4}$ で当たりが出る商品がある'},
 'A16-7': {'skill': 'CP8',
           'sub': ['CP5'],
           'level': 'standard',
           'group': '条件つき確率と期待値',
           'head': '緑玉 $4$ 個、黄玉 $5$ 個が入った袋から、玉を $1$ 個取り出し、もと'},
 'A16-8': {'skill': 'CP8',
           'sub': ['CP1'],
           'level': 'advanced',
           'group': '条件つき確率と期待値',
           'head': 'ある工場では、作った製品の $4\\%$ が不良品である。この工場の検査機は、不良'},
 'A16-9': {'skill': 'CP9',
           'sub': ['CP5'],
           'level': 'standard',
           'group': '条件つき確率と期待値',
           'head': '$2$ 個のさいころを同時に投げ、出た目の和が $10$ 以上なら $300$ '},
 'A16-10': {'skill': 'CP9',
            'sub': ['CP4'],
            'level': 'advanced',
            'group': '条件つき確率と期待値',
            'head': '$1$ から $6$ までの番号が1つずつ書かれた $6$ 枚のカードから同時に'},
 'A17-1': {'skill': 'GE1',
           'sub': [],
           'level': 'basic',
           'group': '角の二等分線と線分の比',
           'head': '$\\triangle\\mathrm{ABC}$ で $\\mathrm{AB}=1'},
 'A17-2': {'skill': 'GE1',
           'sub': [],
           'level': 'standard',
           'group': '角の二等分線と線分の比',
           'head': '$\\triangle\\mathrm{ABC}$ において $\\mathrm{AB'},
 'A17-3': {'skill': 'GE2',
           'sub': [],
           'level': 'basic',
           'group': '三角形の五心（重心・外心・内心）',
           'head': '$\\triangle\\mathrm{ABC}$ の重心を $\\mathrm{G}'},
 'A17-4': {'skill': 'GE2',
           'sub': ['GE4'],
           'level': 'standard',
           'group': '三角形の五心（重心・外心・内心）',
           'head': '鋭角三角形 $\\mathrm{ABC}$ の外心を $\\mathrm{O}$、内'},
 'A17-5': {'skill': 'GE3',
           'sub': [],
           'level': 'advanced',
           'group': 'チェバとメネラウスの使い分け',
           'head': '$\\triangle\\mathrm{ABC}$ の辺 $\\mathrm{BC}$'},
 'A17-6': {'skill': 'GE3',
           'sub': [],
           'level': 'advanced',
           'group': 'チェバとメネラウスの使い分け',
           'head': '$\\triangle\\mathrm{ABC}$ の辺 $\\mathrm{BC}$'},
 'A17-7': {'skill': 'GE4',
           'sub': ['GE2'],
           'level': 'basic',
           'group': '円周角・方べきの定理',
           'head': '円 $\\mathrm{O}$ の周上に3点 $\\mathrm{A}$、$\\mat'},
 'A17-8': {'skill': 'GE5',
           'sub': [],
           'level': 'standard',
           'group': '円周角・方べきの定理',
           'head': '中心 $\\mathrm{O}$ の円の外部に点 $\\mathrm{P}$ があり'},
 'A17-9': {'skill': 'GE5',
           'sub': [],
           'level': 'standard',
           'group': '円周角・方べきの定理',
           'head': '円 $\\mathrm{O}$ の外部の点 $\\mathrm{P}$ から円に接線'},
 'A18-1': {'skill': 'IN1',
           'sub': [],
           'level': 'basic',
           'group': '素因数分解して約数を数える',
           'head': '$1080$ を素因数分解し、正の約数の個数と、正の約数の総和を求めよ。'},
 'A18-2': {'skill': 'IN1',
           'sub': [],
           'level': 'standard',
           'group': '素因数分解して約数を数える',
           'head': '正の約数がちょうど $10$ 個であるような自然数のうち、最小のものを求めよ。'},
 'A18-3': {'skill': 'IN3',
           'sub': ['IN2'],
           'level': 'basic',
           'group': '互除法と最大公約数・最小公倍数',
           'head': '互除法を使って $1517$ と $2091$ の最大公約数を求めよ。割り算の式'},
 'A18-4': {'skill': 'IN2',
           'sub': ['IN1'],
           'level': 'standard',
           'group': '互除法と最大公約数・最小公倍数',
           'head': '$2$ つの正の整数 $a$, $b$（$a \\lt b$）がある。$a$ と '},
 'A18-5': {'skill': 'IN4',
           'sub': ['IN3'],
           'level': 'standard',
           'group': '1次不定方程式',
           'head': '$13x+8y=1$ を満たす整数 $x$, $y$ の組をすべて求めよ。ただし'},
 'A18-6': {'skill': 'IN4',
           'sub': ['IN2'],
           'level': 'advanced',
           'group': '1次不定方程式',
           'head': '$1$ 個 $60$ 円のあめと $1$ 個 $84$ 円のチョコレートを、どち'},
 'A18-7': {'skill': 'IN5',
           'sub': [],
           'level': 'standard',
           'group': '余りによる分類とn進法',
           'head': '$n$ を整数とする。$n^{2}$ を $5$ で割った余りとしてありえる値を'},
 'A18-8': {'skill': 'IN6',
           'sub': ['IN5'],
           'level': 'basic',
           'group': '余りによる分類とn進法',
           'head': '$10$ 進法で表された $46$ を $2$ 進法で表せ。また、$5$ 進法で'},
 'A18-9': {'skill': 'IN6',
           'sub': [],
           'level': 'standard',
           'group': '余りによる分類とn進法',
           'head': '$4$ 進法で表された $1203_{(4)}$ を $10$ 進法で表せ。また'}}
