# -*- coding: utf-8 -*-
"""数列・確率・ベクトル 基礎徹底問題集 の【塾長用】弱点診断マップ。
★生徒には見せない(どの問題が何を測るかを知られると診断精度が落ちる)。
MAP のキーは「単元番号-問題番号」(印刷版の番号と同一)。head は content_kiso とのドリフト検知用(先頭40字)。
問題を増減・並替・改稿したら必ず再生成すること(analyze_kiso が不一致を検知して止まる)。"""

SKILLS = {'KZ1': '書き出して数える',
 'KZ2': '積の法則',
 'KZ3': '和の法則・重複の処理',
 'KZ4': '約数の個数と総和',
 'JK1': '順列P・階乗',
 'JK2': '条件つき順列(隣り合う・円順列)',
 'JK3': '組合せC',
 'JK4': '組合せの応用(選抜・図形)',
 'JK5': '同じものを含む順列・重複順列',
 'P1': '確率の定義(数え上げて割る)',
 'P2': 'P・Cを使う確率',
 'P3': '余事象(「少なくとも」)',
 'P4': '和事象・加法定理',
 'P5': '独立試行・反復試行',
 'P6': '乗法定理・条件付き確率',
 'P7': '期待値',
 'S1': '等差数列の一般項',
 'S2': '等差数列の決定(連立)',
 'S3': '等差数列の和',
 'S4': '等差数列の和の最大',
 'T1': '等比数列の一般項',
 'T2': '等比数列の決定',
 'T3': '等比数列の和',
 'G1': 'Σの公式(k, k², k³)',
 'G2': 'Σの式計算',
 'G3': '階差数列',
 'G4': '部分分数分解の和',
 'Z1': '漸化式(等差型・等比型)',
 'Z2': '漸化式(特性方程式型・階差型)',
 'Z3': 'SnとAnの関係',
 'Z4': '数学的帰納法',
 'V1': 'ベクトルの成分計算',
 'V2': 'ベクトルの大きさ',
 'V3': 'ベクトルの分解・平行条件',
 'W1': '内積の計算',
 'W2': 'なす角',
 'W3': '垂直条件',
 'W4': '内積と大きさの関係',
 'X1': '内分点・外分点・中点',
 'X2': '重心',
 'X3': '共線条件・一次独立',
 'Y1': '空間ベクトルの成分・大きさ',
 'Y2': '空間ベクトルの内積・なす角',
 'Y3': '空間の図形への応用'}

PREREQ = {'JK1': ['KZ2'],
 'JK2': ['JK1'],
 'JK3': ['JK1'],
 'JK4': ['JK3'],
 'JK5': ['JK1'],
 'P1': ['KZ1'],
 'P2': ['P1', 'JK3'],
 'P3': ['P2'],
 'P4': ['P1', 'KZ3'],
 'P5': ['P2'],
 'P6': ['P1'],
 'P7': ['P1'],
 'S2': ['S1'],
 'S3': ['S1'],
 'S4': ['S3'],
 'T2': ['T1'],
 'T3': ['T1'],
 'G2': ['G1'],
 'G3': ['G2'],
 'G4': ['G1'],
 'Z1': ['S1', 'T1'],
 'Z2': ['Z1', 'T1', 'G3'],
 'Z3': ['S3'],
 'Z4': ['G1'],
 'V2': ['V1'],
 'V3': ['V1'],
 'W1': ['V1'],
 'W2': ['W1', 'V2'],
 'W3': ['W1'],
 'W4': ['W1', 'V2'],
 'X1': ['V1'],
 'X2': ['X1'],
 'X3': ['V3', 'X1'],
 'Y1': ['V1', 'V2'],
 'Y2': ['W1', 'W2'],
 'Y3': ['Y1', 'X1']}

UNITS_INFO = [{'idx': 1, 'name': '場合の数の基本', 'count': 11},
 {'idx': 2, 'name': '順列と組合せ', 'count': 12},
 {'idx': 3, 'name': '確率の基本', 'count': 12},
 {'idx': 4, 'name': 'いろいろな確率', 'count': 11},
 {'idx': 5, 'name': '等差数列', 'count': 11},
 {'idx': 6, 'name': '等比数列', 'count': 10},
 {'idx': 7, 'name': '和とシグマ', 'count': 10},
 {'idx': 8, 'name': '漸化式と数学的帰納法', 'count': 10},
 {'idx': 9, 'name': '平面ベクトルの基本', 'count': 10},
 {'idx': 10, 'name': 'ベクトルの内積', 'count': 10},
 {'idx': 11, 'name': '位置ベクトルと図形', 'count': 9},
 {'idx': 12, 'name': '空間ベクトル', 'count': 10}]

MAP = {'1-1': {'skill': 'KZ2',
         'sub': [],
         'level': 'basic',
         'group': '樹形図と数え上げ',
         'head': '1, 2, 3 の3個の数字から異なる2個を選んで2桁の整数をつくる。全部で何個'},
 '1-2': {'skill': 'KZ2',
         'sub': [],
         'level': 'basic',
         'group': '樹形図と数え上げ',
         'head': '大小2個のさいころを投げる。目の出方は全部で何通りか。'},
 '1-3': {'skill': 'KZ1',
         'sub': [],
         'level': 'basic',
         'group': '樹形図と数え上げ',
         'head': '大小2個のさいころを投げるとき、出た目の和が $7$ になる出方は何通りか。書き'},
 '1-4': {'skill': 'JK1',
         'sub': [],
         'level': 'basic',
         'group': '樹形図と数え上げ',
         'head': 'A, B, C, D の4人が1列に並ぶ。並び方は全部で何通りか。'},
 '1-5': {'skill': 'KZ2',
         'sub': [],
         'level': 'basic',
         'group': '和の法則・積の法則',
         'head': '前菜3種類、主菜4種類から1つずつ選ぶ。選び方は全部で何通りか。'},
 '1-6': {'skill': 'KZ3',
         'sub': [],
         'level': 'standard',
         'group': '和の法則・積の法則',
         'head': '1 から 20 までの整数のうち、$3$ の倍数または $5$ の倍数は何個ある'},
 '1-7': {'skill': 'KZ2',
         'sub': [],
         'level': 'standard',
         'group': '和の法則・積の法則',
         'head': '大中小3個のさいころを投げるとき、目の積が奇数になる出方は何通りか。'},
 '1-8': {'skill': 'KZ2',
         'sub': ['JK1'],
         'level': 'standard',
         'group': '和の法則・積の法則',
         'head': '$3$ 桁の整数のうち、各位の数字がすべて異なるものは何個あるか。'},
 '1-9': {'skill': 'KZ4', 'sub': [], 'level': 'standard', 'group': '約数の個数と総和', 'head': '$72$ の正の約数は何個あるか。'},
 '1-10': {'skill': 'KZ4',
          'sub': [],
          'level': 'standard',
          'group': '約数の個数と総和',
          'head': '$72$ の正の約数すべての和を求めよ。'},
 '1-11': {'skill': 'KZ1',
          'sub': [],
          'level': 'standard',
          'group': '積の分解で数える',
          'head': '大小2個のさいころを投げるとき、出た目の積が $12$ になる出方は何通りか。'},
 '2-1': {'skill': 'JK1',
         'sub': [],
         'level': 'basic',
         'group': '順列 P',
         'head': '${}_{7}\\mathrm{P}_{3}$ の値を求めよ。'},
 '2-2': {'skill': 'JK1', 'sub': [], 'level': 'basic', 'group': '順列 P', 'head': '$6$ 人が1列に並ぶ並び方は何通りか。'},
 '2-3': {'skill': 'JK2',
         'sub': [],
         'level': 'standard',
         'group': '順列 P',
         'head': '男子3人、女子2人の計5人が1列に並ぶとき、女子2人が隣り合う並び方は何通りか。'},
 '2-4': {'skill': 'JK2',
         'sub': [],
         'level': 'standard',
         'group': '順列 P',
         'head': '$5$ 人が円形のテーブルに座る座り方は何通りか(円順列)。'},
 '2-5': {'skill': 'JK3',
         'sub': [],
         'level': 'basic',
         'group': '組合せ C',
         'head': '$10$ 人から $3$ 人の委員を選ぶ方法は何通りか。'},
 '2-6': {'skill': 'JK3',
         'sub': [],
         'level': 'basic',
         'group': '組合せ C',
         'head': '${}_{8}\\mathrm{C}_{2}$ の値を求めよ。'},
 '2-7': {'skill': 'JK4',
         'sub': ['KZ2'],
         'level': 'standard',
         'group': '組合せ C',
         'head': '男子6人、女子4人から4人を選ぶとき、男子2人・女子2人となる選び方は何通りか。'},
 '2-8': {'skill': 'JK4',
         'sub': [],
         'level': 'standard',
         'group': '組合せ C',
         'head': '正八角形の3個の頂点を結んでできる三角形は何個あるか。'},
 '2-9': {'skill': 'JK4', 'sub': [], 'level': 'standard', 'group': '組合せ C', 'head': '正八角形の対角線は全部で何本あるか。'},
 '2-10': {'skill': 'JK5',
          'sub': [],
          'level': 'standard',
          'group': '同じものを含む順列',
          'head': '$5$ 文字 A, A, B, B, C を1列に並べる並べ方は何通りか。'},
 '2-11': {'skill': 'JK5',
          'sub': [],
          'level': 'standard',
          'group': '同じものを含む順列',
          'head': 'BANANA の6文字を1列に並べる並べ方は何通りか。'},
 '2-12': {'skill': 'JK5',
          'sub': ['KZ2'],
          'level': 'standard',
          'group': '同じものを含む順列',
          'head': '1, 2, 3 の数字を、同じ数字を何回使ってもよいとして並べ、3桁の整数をつく'},
 '3-1': {'skill': 'P1',
         'sub': [],
         'level': 'basic',
         'group': '確率の定義',
         'head': '1個のさいころを投げるとき、$3$ の倍数の目が出る確率を求めよ。'},
 '3-2': {'skill': 'P1',
         'sub': ['KZ1'],
         'level': 'basic',
         'group': '確率の定義',
         'head': '大小2個のさいころを投げるとき、目の和が $7$ になる確率を求めよ。'},
 '3-3': {'skill': 'P1',
         'sub': [],
         'level': 'basic',
         'group': '確率の定義',
         'head': '赤玉3個、白玉2個が入った袋から1個取り出すとき、赤玉が出る確率を求めよ。'},
 '3-4': {'skill': 'P2',
         'sub': [],
         'level': 'standard',
         'group': '組合せを使う確率',
         'head': '赤玉4個、白玉3個の入った袋から同時に2個取り出すとき、2個とも赤玉である確率を'},
 '3-5': {'skill': 'P2',
         'sub': [],
         'level': 'standard',
         'group': '組合せを使う確率',
         'head': '赤玉4個、白玉3個から同時に2個取り出すとき、赤玉1個・白玉1個となる確率を求め'},
 '3-6': {'skill': 'P2',
         'sub': [],
         'level': 'standard',
         'group': '組合せを使う確率',
         'head': '男子4人、女子3人から3人の委員をくじで選ぶとき、女子だけが選ばれる確率を求めよ'},
 '3-7': {'skill': 'P2',
         'sub': [],
         'level': 'standard',
         'group': '組合せを使う確率',
         'head': '1 から 9 の数字が書かれた9枚のカードから2枚引くとき、2枚とも奇数である確'},
 '3-8': {'skill': 'P2',
         'sub': ['KZ2'],
         'level': 'standard',
         'group': 'いろいろな確率',
         'head': '3枚の硬貨を同時に投げるとき、表がちょうど2枚出る確率を求めよ。'},
 '3-9': {'skill': 'P3',
         'sub': [],
         'level': 'standard',
         'group': 'いろいろな確率',
         'head': '大小2個のさいころを投げるとき、少なくとも一方が $6$ の目である確率を求めよ'},
 '3-10': {'skill': 'P2',
          'sub': ['JK2'],
          'level': 'standard',
          'group': 'いろいろな確率',
          'head': 'A, B, C, D, E の5人が1列に並ぶとき、A と B が隣り合う確率を'},
 '3-11': {'skill': 'P1',
          'sub': [],
          'level': 'basic',
          'group': 'いろいろな確率',
          'head': 'ジョーカーを除く $52$ 枚のトランプから1枚引くとき、それがハートである確率'},
 '3-12': {'skill': 'P3',
          'sub': ['P2'],
          'level': 'standard',
          'group': 'いろいろな確率',
          'head': '当たり3本、はずれ7本のくじから同時に2本引くとき、少なくとも1本当たる確率を求'},
 '4-1': {'skill': 'P4',
         'sub': ['KZ3'],
         'level': 'standard',
         'group': '加法定理・余事象',
         'head': '1 から 10 の番号札から1枚引くとき、偶数または $3$ の倍数である確率を'},
 '4-2': {'skill': 'P4',
         'sub': ['KZ1'],
         'level': 'standard',
         'group': '加法定理・余事象',
         'head': '大小2個のさいころを投げるとき、目の和が $5$ の倍数(5 または 10)にな'},
 '4-3': {'skill': 'P5',
         'sub': [],
         'level': 'standard',
         'group': '独立試行・反復試行',
         'head': 'フリースローを決める確率が $\\dfrac{2}{3}$ の選手が2回投げるとき'},
 '4-4': {'skill': 'P5',
         'sub': [],
         'level': 'standard',
         'group': '独立試行・反復試行',
         'head': '1個のさいころを3回投げるとき、$1$ の目がちょうど1回出る確率を求めよ。'},
 '4-5': {'skill': 'P5',
         'sub': [],
         'level': 'standard',
         'group': '独立試行・反復試行',
         'head': '1枚の硬貨を5回投げるとき、表がちょうど3回出る確率を求めよ。'},
 '4-6': {'skill': 'P5',
         'sub': [],
         'level': 'standard',
         'group': '独立試行・反復試行',
         'head': '当たる確率が $\\dfrac{1}{3}$ のくじを(毎回もとに戻して)4回引く'},
 '4-7': {'skill': 'P6',
         'sub': [],
         'level': 'standard',
         'group': '条件付き確率',
         'head': '袋に赤玉2個、白玉3個。玉を1個取り出し、もとに戻さずにもう1個取り出す。1個目'},
 '4-8': {'skill': 'P6',
         'sub': [],
         'level': 'standard',
         'group': '条件付き確率',
         'head': '男子3人、女子2人から2人を続けて選ぶ(もとに戻さない)。1人目が男子だったとき'},
 '4-9': {'skill': 'P6',
         'sub': ['P4'],
         'level': 'standard',
         'group': '条件付き確率',
         'head': '箱Aには当たり1本・はずれ3本、箱Bには当たり2本・はずれ2本。さいころを振り、'},
 '4-10': {'skill': 'P7',
          'sub': [],
          'level': 'standard',
          'group': '期待値',
          'head': '1個のさいころを投げ、出た目の数だけ得点がもらえる。得点の期待値を求めよ。'},
 '4-11': {'skill': 'P7',
          'sub': [],
          'level': 'standard',
          'group': '期待値',
          'head': '当たり(賞金300円)2本、はずれ(0円)3本のくじを1本引く。もらえる金額の期'},
 '5-1': {'skill': 'S1',
         'sub': [],
         'level': 'basic',
         'group': '一般項',
         'head': '初項 $3$、公差 $4$ の等差数列の一般項 $a_{n}$ を求めよ。'},
 '5-2': {'skill': 'S1',
         'sub': [],
         'level': 'basic',
         'group': '一般項',
         'head': '初項 $3$、公差 $4$ の等差数列の第 $10$ 項を求めよ。'},
 '5-3': {'skill': 'S1',
         'sub': [],
         'level': 'basic',
         'group': '一般項',
         'head': '初項 $20$、公差 $-3$ の等差数列の一般項 $a_{n}$ を求めよ。'},
 '5-4': {'skill': 'S1',
         'sub': [],
         'level': 'basic',
         'group': '一般項',
         'head': '等差数列 $-7,\\ -4,\\ -1,\\ 2,\\ \\ldots$ の一般項 $a'},
 '5-5': {'skill': 'S2',
         'sub': [],
         'level': 'standard',
         'group': '一般項',
         'head': '第 $3$ 項が $11$、第 $7$ 項が $27$ である等差数列の初項と公'},
 '5-6': {'skill': 'S1',
         'sub': [],
         'level': 'standard',
         'group': '一般項',
         'head': '等差数列 $5,\\ 8,\\ 11,\\ 14,\\ \\ldots$ で、第 $n$ '},
 '5-7': {'skill': 'S3', 'sub': [], 'level': 'basic', 'group': '和', 'head': '$1$ から $100$ までの自然数の和を求めよ。'},
 '5-8': {'skill': 'S3',
         'sub': [],
         'level': 'basic',
         'group': '和',
         'head': '$1$ から $99$ までの奇数の和 $1+3+5+\\cdots+99$ を求'},
 '5-9': {'skill': 'S3',
         'sub': [],
         'level': 'basic',
         'group': '和',
         'head': '初項 $2$、公差 $3$ の等差数列の、初項から第 $20$ 項までの和を求め'},
 '5-10': {'skill': 'S3',
          'sub': ['S2'],
          'level': 'standard',
          'group': '和',
          'head': '第 $5$ 項が $20$、初項から第 $5$ 項までの和が $70$ である等'},
 '5-11': {'skill': 'S4',
          'sub': ['S1', 'S3'],
          'level': 'advanced',
          'group': '和',
          'head': '初項 $50$、公差 $-4$ の等差数列で、初項から第 $n$ 項までの和 $'},
 '6-1': {'skill': 'T1',
         'sub': [],
         'level': 'basic',
         'group': '一般項',
         'head': '初項 $2$、公比 $3$ の等比数列の第 $5$ 項を求めよ。'},
 '6-2': {'skill': 'T1',
         'sub': [],
         'level': 'basic',
         'group': '一般項',
         'head': '初項 $5$、公比 $2$ の等比数列の一般項 $a_{n}$ を求めよ。'},
 '6-3': {'skill': 'T1',
         'sub': [],
         'level': 'basic',
         'group': '一般項',
         'head': '等比数列 $1,\\ -2,\\ 4,\\ -8,\\ \\ldots$ の一般項 $a_'},
 '6-4': {'skill': 'T2',
         'sub': [],
         'level': 'standard',
         'group': '一般項',
         'head': '第 $2$ 項が $6$、第 $4$ 項が $54$ である等比数列の公比(正)'},
 '6-5': {'skill': 'T1',
         'sub': [],
         'level': 'standard',
         'group': '一般項',
         'head': '等比数列 $3,\\ 6,\\ 12,\\ 24,\\ \\ldots$ で、第 $n$ '},
 '6-6': {'skill': 'T3',
         'sub': [],
         'level': 'basic',
         'group': '和',
         'head': '初項 $1$、公比 $2$ の等比数列の、初項から第 $10$ 項までの和を求め'},
 '6-7': {'skill': 'T3',
         'sub': [],
         'level': 'basic',
         'group': '和',
         'head': '初項 $3$、公比 $2$ の等比数列の、初項から第 $5$ 項までの和を求めよ'},
 '6-8': {'skill': 'T3',
         'sub': [],
         'level': 'standard',
         'group': '和',
         'head': '初項 $2$、公比 $3$ の等比数列の、初項から第 $4$ 項までの和を求めよ'},
 '6-9': {'skill': 'T3',
         'sub': [],
         'level': 'standard',
         'group': '和',
         'head': '$1+\\dfrac{1}{2}+\\dfrac{1}{4}+\\cdots+\\dfr'},
 '6-10': {'skill': 'T2',
          'sub': ['T1'],
          'level': 'standard',
          'group': '和',
          'head': '等比数列で初項 $2$、第 $4$ 項が $16$ のとき、公比(正)と第 $6'},
 '7-1': {'skill': 'G1',
         'sub': [],
         'level': 'basic',
         'group': 'シグマの計算',
         'head': '$\\displaystyle\\sum_{k=1}^{10} k$ を求めよ。'},
 '7-2': {'skill': 'G1',
         'sub': [],
         'level': 'basic',
         'group': 'シグマの計算',
         'head': '$\\displaystyle\\sum_{k=1}^{5} k^{2}$ を求めよ'},
 '7-3': {'skill': 'G1',
         'sub': [],
         'level': 'basic',
         'group': 'シグマの計算',
         'head': '$\\displaystyle\\sum_{k=1}^{6} k^{3}$ を求めよ'},
 '7-4': {'skill': 'G2',
         'sub': ['G1'],
         'level': 'standard',
         'group': 'シグマの計算',
         'head': '$\\displaystyle\\sum_{k=1}^{n}(2k-1)$ を $n'},
 '7-5': {'skill': 'G2',
         'sub': ['G1'],
         'level': 'standard',
         'group': 'シグマの計算',
         'head': '$\\displaystyle\\sum_{k=1}^{n} k(k+1)$ を $'},
 '7-6': {'skill': 'G2',
         'sub': ['G1'],
         'level': 'standard',
         'group': 'シグマの計算',
         'head': '$\\displaystyle\\sum_{k=1}^{n}(3k-2)$ を $n'},
 '7-7': {'skill': 'G3',
         'sub': ['G2'],
         'level': 'standard',
         'group': '階差数列',
         'head': '数列 $2,\\ 5,\\ 10,\\ 17,\\ 26,\\ \\ldots$ の一般項 '},
 '7-8': {'skill': 'G3',
         'sub': ['G2'],
         'level': 'standard',
         'group': '階差数列',
         'head': '数列 $1,\\ 2,\\ 4,\\ 7,\\ 11,\\ 16,\\ \\ldots$ の一'},
 '7-9': {'skill': 'G4',
         'sub': [],
         'level': 'standard',
         'group': '部分分数分解の和',
         'head': '$\\displaystyle\\sum_{k=1}^{n}\\dfrac{1}{k('},
 '7-10': {'skill': 'G4',
          'sub': [],
          'level': 'standard',
          'group': '部分分数分解の和',
          'head': '$\\displaystyle\\sum_{k=1}^{10}\\dfrac{1}{k'},
 '8-1': {'skill': 'Z1',
         'sub': ['S1'],
         'level': 'basic',
         'group': '漸化式の基本',
         'head': '$a_{1}=1,\\ a_{n+1}=a_{n}+3$ で定まる数列の一般項 $'},
 '8-2': {'skill': 'Z1',
         'sub': ['T1'],
         'level': 'basic',
         'group': '漸化式の基本',
         'head': '$a_{1}=2,\\ a_{n+1}=3a_{n}$ で定まる数列の一般項 $a'},
 '8-3': {'skill': 'Z1',
         'sub': ['S1'],
         'level': 'basic',
         'group': '漸化式の基本',
         'head': '$a_{1}=5,\\ a_{n+1}=a_{n}-2$ で定まる数列の第 $10'},
 '8-4': {'skill': 'Z2',
         'sub': ['T1'],
         'level': 'standard',
         'group': '特性方程式型・階差型',
         'head': '$a_{1}=1,\\ a_{n+1}=2a_{n}+1$ で定まる数列の一般項 '},
 '8-5': {'skill': 'Z2',
         'sub': ['T1'],
         'level': 'standard',
         'group': '特性方程式型・階差型',
         'head': '$a_{1}=3,\\ a_{n+1}=2a_{n}-1$ で定まる数列の一般項 '},
 '8-6': {'skill': 'Z2',
         'sub': ['G3'],
         'level': 'standard',
         'group': '特性方程式型・階差型',
         'head': '$a_{1}=1,\\ a_{n+1}=a_{n}+2n$ で定まる数列の一般項 '},
 '8-7': {'skill': 'Z3',
         'sub': [],
         'level': 'standard',
         'group': '和 $S_{n}$ と一般項',
         'head': '数列の初項から第 $n$ 項までの和が $S_{n}=n^{2}+2n$ である'},
 '8-8': {'skill': 'Z3',
         'sub': ['T1'],
         'level': 'standard',
         'group': '和 $S_{n}$ と一般項',
         'head': '数列の初項から第 $n$ 項までの和が $S_{n}=2^{n}-1$ であると'},
 '8-9': {'skill': 'Z4',
         'sub': [],
         'level': 'standard',
         'group': '数学的帰納法',
         'head': '数学的帰納法を用いて、すべての自然数 $n$ について $1+2+3+\\cdot'},
 '8-10': {'skill': 'Z4',
          'sub': [],
          'level': 'advanced',
          'group': '数学的帰納法',
          'head': '数学的帰納法を用いて、すべての自然数 $n$ について $1^{2}+2^{2}'},
 '9-1': {'skill': 'V1',
         'sub': [],
         'level': 'basic',
         'group': 'ベクトルの演算',
         'head': '$\\vec{a}=(2,\\,3),\\ \\vec{b}=(-1,\\,4)$ のとき'},
 '9-2': {'skill': 'V1',
         'sub': [],
         'level': 'basic',
         'group': 'ベクトルの演算',
         'head': '$\\vec{a}=(2,\\,3),\\ \\vec{b}=(-1,\\,4)$ のとき'},
 '9-3': {'skill': 'V1',
         'sub': [],
         'level': 'basic',
         'group': 'ベクトルの演算',
         'head': '$\\vec{a}=(2,\\,-1)$ のとき、$3\\vec{a}$ を成分で表せ'},
 '9-4': {'skill': 'V1',
         'sub': [],
         'level': 'standard',
         'group': 'ベクトルの演算',
         'head': '$\\vec{a}=(4,\\,-2),\\ \\vec{b}=(1,\\,3)$ のとき'},
 '9-5': {'skill': 'V2',
         'sub': [],
         'level': 'basic',
         'group': '大きさ',
         'head': '$\\vec{a}=(3,\\,4)$ の大きさ $|\\vec{a}|$ を求めよ。'},
 '9-6': {'skill': 'V2',
         'sub': [],
         'level': 'basic',
         'group': '大きさ',
         'head': '$\\vec{a}=(1,\\,-2)$ の大きさ $|\\vec{a}|$ を求めよ'},
 '9-7': {'skill': 'V2',
         'sub': ['V1'],
         'level': 'standard',
         'group': '大きさ',
         'head': '2点 $\\mathrm{A}(1,\\,2),\\ \\mathrm{B}(4,\\,6'},
 '9-8': {'skill': 'V2',
         'sub': [],
         'level': 'standard',
         'group': '大きさ',
         'head': '$\\vec{a}=(x,\\,3)$ の大きさが $5$ となるような正の数 $x'},
 '9-9': {'skill': 'V3',
         'sub': [],
         'level': 'standard',
         'group': 'ベクトルの分解・平行',
         'head': '$\\vec{a}=(2,\\,1),\\ \\vec{b}=(1,\\,-1)$ のとき'},
 '9-10': {'skill': 'V3',
          'sub': [],
          'level': 'standard',
          'group': 'ベクトルの分解・平行',
          'head': '$\\vec{a}=(2,\\,3),\\ \\vec{b}=(4,\\,k)$ が平行で'},
 '10-1': {'skill': 'W1',
          'sub': [],
          'level': 'basic',
          'group': '内積の計算',
          'head': '$\\vec{a}=(2,\\,3),\\ \\vec{b}=(4,\\,-1)$ の内積'},
 '10-2': {'skill': 'W1',
          'sub': [],
          'level': 'basic',
          'group': '内積の計算',
          'head': '$|\\vec{a}|=3,\\ |\\vec{b}|=4$ で、$\\vec{a}$ '},
 '10-3': {'skill': 'W1',
          'sub': [],
          'level': 'basic',
          'group': '内積の計算',
          'head': '$\\vec{a}=(1,\\,2),\\ \\vec{b}=(3,\\,-1)$ の内積'},
 '10-4': {'skill': 'W2',
          'sub': ['W1', 'V2'],
          'level': 'standard',
          'group': 'なす角',
          'head': '$\\vec{a}=(1,\\,2),\\ \\vec{b}=(3,\\,1)$ のなす角'},
 '10-5': {'skill': 'W2',
          'sub': [],
          'level': 'standard',
          'group': 'なす角',
          'head': '$\\vec{a}=(1,\\,\\sqrt{3}),\\ \\vec{b}=(\\sqrt'},
 '10-6': {'skill': 'W2',
          'sub': [],
          'level': 'standard',
          'group': 'なす角',
          'head': '$\\vec{a}=(1,\\,0),\\ \\vec{b}=(-1,\\,1)$ のなす'},
 '10-7': {'skill': 'W3',
          'sub': [],
          'level': 'basic',
          'group': '垂直・平行',
          'head': '$\\vec{a}=(3,\\,2),\\ \\vec{b}=(4,\\,k)$ が垂直で'},
 '10-8': {'skill': 'W3',
          'sub': ['V2'],
          'level': 'standard',
          'group': '垂直・平行',
          'head': '$\\vec{a}=(2,\\,-1)$ に垂直な単位ベクトルを求めよ。'},
 '10-9': {'skill': 'W1',
          'sub': ['V1'],
          'level': 'standard',
          'group': '内積と大きさ',
          'head': '$\\vec{a}+\\vec{b}=(5,\\,1),\\ \\vec{a}-\\vec{'},
 '10-10': {'skill': 'W4',
           'sub': ['V2'],
           'level': 'standard',
           'group': '内積と大きさ',
           'head': '$|\\vec{a}|=2,\\ |\\vec{b}|=3,\\ \\vec{a}\\cdo'},
 '11-1': {'skill': 'X1',
          'sub': [],
          'level': 'basic',
          'group': '内分点・外分点・中点',
          'head': '2点 $\\mathrm{A}(1,\\,2),\\ \\mathrm{B}(7,\\,5'},
 '11-2': {'skill': 'X1',
          'sub': [],
          'level': 'basic',
          'group': '内分点・外分点・中点',
          'head': '2点 $\\mathrm{A}(2,\\,1),\\ \\mathrm{B}(8,\\,4'},
 '11-3': {'skill': 'X1',
          'sub': [],
          'level': 'standard',
          'group': '内分点・外分点・中点',
          'head': '2点 $\\mathrm{A}(1,\\,2),\\ \\mathrm{B}(7,\\,5'},
 '11-4': {'skill': 'X1',
          'sub': [],
          'level': 'standard',
          'group': '内分点・外分点・中点',
          'head': '$\\overrightarrow{\\mathrm{OA}}=\\vec{a},\\ '},
 '11-5': {'skill': 'X2',
          'sub': [],
          'level': 'basic',
          'group': '重心',
          'head': '三角形 ABC の頂点が $\\mathrm{A}(1,\\,1),\\ \\mathr'},
 '11-6': {'skill': 'X2',
          'sub': [],
          'level': 'standard',
          'group': '重心',
          'head': '三角形 ABC の頂点の位置ベクトルを $\\vec{a},\\vec{b},\\ve'},
 '11-7': {'skill': 'X3',
          'sub': [],
          'level': 'standard',
          'group': '共線条件・一次独立',
          'head': '3点 $\\mathrm{A}(1,\\,2),\\ \\mathrm{B}(4,\\,3'},
 '11-8': {'skill': 'X3',
          'sub': [],
          'level': 'standard',
          'group': '共線条件・一次独立',
          'head': '$\\vec{a},\\vec{b}$ は $\\vec{0}$ でなく平行でない(一'},
 '11-9': {'skill': 'X1',
          'sub': ['V3'],
          'level': 'standard',
          'group': '共線条件・一次独立',
          'head': '平行四辺形 ABCD で $\\overrightarrow{\\mathrm{AB'},
 '12-1': {'skill': 'Y1',
          'sub': ['V1'],
          'level': 'basic',
          'group': '空間の点とベクトル',
          'head': '空間の2点 $\\mathrm{A}(1,\\,2,\\,3),\\ \\mathrm{B'},
 '12-2': {'skill': 'Y1',
          'sub': ['V2'],
          'level': 'basic',
          'group': '空間の点とベクトル',
          'head': '$\\vec{a}=(2,\\,-1,\\,2)$ の大きさ $|\\vec{a}|$ '},
 '12-3': {'skill': 'Y1',
          'sub': [],
          'level': 'basic',
          'group': '空間の点とベクトル',
          'head': '2点 $\\mathrm{A}(1,\\,0,\\,2),\\ \\mathrm{B}(3'},
 '12-4': {'skill': 'Y2',
          'sub': ['W1'],
          'level': 'basic',
          'group': '空間ベクトルの演算・内積',
          'head': '$\\vec{a}=(1,\\,2,\\,-1),\\ \\vec{b}=(3,\\,-1,'},
 '12-5': {'skill': 'Y1',
          'sub': ['V1'],
          'level': 'basic',
          'group': '空間ベクトルの演算・内積',
          'head': '$\\vec{a}=(2,\\,1,\\,-2),\\ \\vec{b}=(1,\\,0,\\'},
 '12-6': {'skill': 'Y2',
          'sub': ['W2'],
          'level': 'standard',
          'group': '空間ベクトルの演算・内積',
          'head': '$\\vec{a}=(1,\\,1,\\,0),\\ \\vec{b}=(1,\\,0,\\,'},
 '12-7': {'skill': 'Y2',
          'sub': ['W3'],
          'level': 'standard',
          'group': '空間ベクトルの演算・内積',
          'head': '$\\vec{a}=(1,\\,2,\\,2)$ と $\\vec{b}=(2,\\,k,'},
 '12-8': {'skill': 'Y1',
          'sub': ['V2'],
          'level': 'standard',
          'group': '空間ベクトルの演算・内積',
          'head': '$\\vec{a}=(2,\\,-2,\\,1)$ と同じ向きの単位ベクトルを求めよ。'},
 '12-9': {'skill': 'Y3',
          'sub': ['X2'],
          'level': 'standard',
          'group': '座標空間の図形',
          'head': '3点 $\\mathrm{A}(1,\\,0,\\,0),\\ \\mathrm{B}(0'},
 '12-10': {'skill': 'Y1',
           'sub': ['V2'],
           'level': 'standard',
           'group': '座標空間の図形',
           'head': '$\\vec{a}=(1,\\,2,\\,2),\\ \\vec{b}=(2,\\,-1,\\'}}

LEVEL_W = {'basic': 1.5, 'standard': 1.0, 'advanced': 0.6}  # 基礎ミスほど重い
ROLE_W = {'primary': 1.0, 'sub': 0.4}
