# -*- coding: utf-8 -*-
"""第2集(弱点集中トレーニング)の診断マップ。単元13〜27・104問。
スキルコード体系は diagnosis_kiso.py(第1集)と共通。analyze_kiso.py が両方を読む。
★生徒には見せない。"""

UNITS_INFO = [{'idx': 13, 'name': '場合の数と確率の土台', 'count': 5},
 {'idx': 14, 'name': '独立試行と反復試行', 'count': 12},
 {'idx': 15, 'name': '乗法定理と条件付き確率', 'count': 8},
 {'idx': 16, 'name': '期待値', 'count': 5},
 {'idx': 17, 'name': '漸化式の型を見分ける', 'count': 4},
 {'idx': 18, 'name': '特性方程式型の漸化式', 'count': 9},
 {'idx': 19, 'name': '階差型の漸化式', 'count': 6},
 {'idx': 20, 'name': '和 $S_n$ と一般項 $a_n$', 'count': 5},
 {'idx': 21, 'name': '数学的帰納法', 'count': 3},
 {'idx': 22, 'name': '漸化式の総仕上げ（型の仕分け）', 'count': 6},
 {'idx': 23, 'name': 'Σの計算', 'count': 10},
 {'idx': 24, 'name': '等差・等比の和', 'count': 10},
 {'idx': 25, 'name': '共線条件と一次独立', 'count': 8},
 {'idx': 26, 'name': '内積の総仕上げ', 'count': 9},
 {'idx': 27, 'name': '空間ベクトル', 'count': 4}]

MAP = {'13-1': {'skill': 'KZ2',
          'sub': [],
          'level': 'basic',
          'group': '積の法則（続けて選ぶ→掛ける）',
          'head': 'シャツ $5$ 種類、ズボン $3$ 種類の中から1つずつ選ぶ。選び方は全部で何'},
 '13-2': {'skill': 'KZ2',
          'sub': ['JK1'],
          'level': 'basic',
          'group': '積の法則（続けて選ぶ→掛ける）',
          'head': '$1,\\ 2,\\ 3,\\ 4,\\ 5$ の5個の数字から異なる2個を選んで2桁の'},
 '13-3': {'skill': 'KZ3',
          'sub': [],
          'level': 'standard',
          'group': '「または」の個数（足して、重なりを引く）',
          'head': '$1$ から $30$ までの整数のうち、$4$ の倍数または $6$ の倍数は'},
 '13-4': {'skill': 'KZ3',
          'sub': [],
          'level': 'standard',
          'group': '「または」の個数（足して、重なりを引く）',
          'head': '$1$ から $50$ までの整数のうち、$2$ の倍数または $5$ の倍数は'},
 '13-5': {'skill': 'P1',
          'sub': ['KZ2'],
          'level': 'basic',
          'group': '確率の定義（数え上げて割る）',
          'head': 'ジョーカーを除く $52$ 枚のトランプから1枚引くとき、それが絵札（J, Q,'},
 '14-1': {'skill': 'P5',
          'sub': [],
          'level': 'basic',
          'group': '独立試行（掛ける）',
          'head': '1個のさいころを2回投げるとき、2回とも偶数の目が出る確率を求めよ。'},
 '14-2': {'skill': 'P5',
          'sub': [],
          'level': 'basic',
          'group': '独立試行（掛ける）',
          'head': '袋Aから当たりを引く確率は $\\dfrac{2}{5}$、袋Bから当たりを引く確'},
 '14-3': {'skill': 'P5',
          'sub': [],
          'level': 'basic',
          'group': '独立試行（掛ける）',
          'head': '1個のさいころを3回投げるとき、3回とも $5$ 以上の目が出る確率を求めよ。'},
 '14-4': {'skill': 'P5',
          'sub': [],
          'level': 'standard',
          'group': '独立試行（掛ける）',
          'head': '命中率 $\\dfrac{3}{4}$ の射手が3回撃つとき、3回とも命中する確率'},
 '14-5': {'skill': 'P5',
          'sub': ['JK3'],
          'level': 'basic',
          'group': '反復試行（ちょうど k 回）',
          'head': '1枚の硬貨を4回投げるとき、表がちょうど $3$ 回出る確率を求めよ。'},
 '14-6': {'skill': 'P5',
          'sub': ['JK3'],
          'level': 'basic',
          'group': '反復試行（ちょうど k 回）',
          'head': '1個のさいころを3回投げるとき、$1$ の目がちょうど $2$ 回出る確率を求め'},
 '14-7': {'skill': 'P5',
          'sub': ['JK3'],
          'level': 'standard',
          'group': '反復試行（ちょうど k 回）',
          'head': '1枚の硬貨を6回投げるとき、表がちょうど $4$ 回出る確率を求めよ。'},
 '14-8': {'skill': 'P5',
          'sub': ['JK3'],
          'level': 'standard',
          'group': '反復試行（ちょうど k 回）',
          'head': '1個のさいころを4回投げるとき、$6$ の目がちょうど $1$ 回出る確率を求め'},
 '14-9': {'skill': 'P5',
          'sub': ['JK3'],
          'level': 'standard',
          'group': '反復試行（ちょうど k 回）',
          'head': '1個のさいころを5回投げるとき、$3$ の倍数の目がちょうど $2$ 回出る確率'},
 '14-10': {'skill': 'P5',
           'sub': ['JK3'],
           'level': 'standard',
           'group': '反復試行（ちょうど k 回）',
           'head': '打率 $\\dfrac{3}{10}$ の打者が $4$ 打席立つとき、ちょうど '},
 '14-11': {'skill': 'P3',
           'sub': ['P5'],
           'level': 'standard',
           'group': '「少なくとも1回」＝余事象',
           'head': '1枚の硬貨を3回投げるとき、少なくとも1回は表が出る確率を求めよ。'},
 '14-12': {'skill': 'P3',
           'sub': ['P5'],
           'level': 'standard',
           'group': '「少なくとも1回」＝余事象',
           'head': '1個のさいころを4回投げるとき、少なくとも1回は $6$ の目が出る確率を求めよ'},
 '15-1': {'skill': 'P6',
          'sub': [],
          'level': 'basic',
          'group': '戻さずに続けて取り出す',
          'head': '赤玉4個、白玉2個が入った袋から、玉を1個取り出し、もとに戻さずにもう1個取り出'},
 '15-2': {'skill': 'P6',
          'sub': [],
          'level': 'basic',
          'group': '戻さずに続けて取り出す',
          'head': '赤玉4個、白玉3個の袋から、戻さずに続けて2個取り出す。1個目が赤玉、2個目が白'},
 '15-3': {'skill': 'P6',
          'sub': ['P4'],
          'level': 'standard',
          'group': '戻さずに続けて取り出す',
          'head': '赤玉4個、白玉3個の袋から、戻さずに続けて2個取り出す。赤玉と白玉が1個ずつ出る'},
 '15-4': {'skill': 'P6',
          'sub': ['P2'],
          'level': 'standard',
          'group': '戻さずに続けて取り出す',
          'head': '当たり2本、はずれ6本のくじから、戻さずに続けて2本引く。2本とも当たる確率を求'},
 '15-5': {'skill': 'P6',
          'sub': [],
          'level': 'standard',
          'group': '条件付き確率',
          'head': '赤玉3個、白玉4個の袋から、戻さずに続けて2個取り出す。1個目が白玉だったとき、'},
 '15-6': {'skill': 'P6',
          'sub': ['P4'],
          'level': 'standard',
          'group': '条件付き確率',
          'head': '箱Aには当たり3本・はずれ2本、箱Bには当たり1本・はずれ4本が入っている。硬貨'},
 '15-7': {'skill': 'P6',
          'sub': ['P4'],
          'level': 'advanced',
          'group': '条件付き確率',
          'head': '上の問題（箱A: 当たり3・はずれ2／箱B: 当たり1・はずれ4、硬貨で箱を選ぶ'},
 '15-8': {'skill': 'P6',
          'sub': ['P4'],
          'level': 'advanced',
          'group': '条件付き確率',
          'head': 'ある製品は工場Aで $60\\%$、工場Bで $40\\%$ 作られている。不良品の'},
 '16-1': {'skill': 'P7',
          'sub': ['P1'],
          'level': 'basic',
          'group': '期待値の基本',
          'head': '1枚の硬貨を2回投げるとき、表が出る回数の期待値を求めよ。'},
 '16-2': {'skill': 'P7',
          'sub': [],
          'level': 'basic',
          'group': '期待値の基本',
          'head': '1個のさいころを投げ、出た目の $2$ 倍の点数がもらえる。得点の期待値を求めよ'},
 '16-3': {'skill': 'P7',
          'sub': [],
          'level': 'basic',
          'group': '期待値の基本',
          'head': '当たり(賞金 $500$ 円)1本、はずれ(0円)4本のくじを1本引く。もらえる'},
 '16-4': {'skill': 'P7',
          'sub': [],
          'level': 'standard',
          'group': '期待値の基本',
          'head': '10本のくじの中に、1等(賞金 $1000$ 円)が1本、2等(賞金 $500$'},
 '16-5': {'skill': 'P7',
          'sub': ['P2'],
          'level': 'advanced',
          'group': '期待値の基本',
          'head': '赤玉2個、白玉3個の袋から同時に2個取り出す。取り出した赤玉の個数の期待値を求め'},
 '17-1': {'skill': 'Z1',
          'sub': ['S1'],
          'level': 'basic',
          'group': '等差型・等比型',
          'head': '$a_{1}=2,\\ a_{n+1}=a_{n}+5$ で定まる数列の一般項 $'},
 '17-2': {'skill': 'Z1',
          'sub': ['T1'],
          'level': 'basic',
          'group': '等差型・等比型',
          'head': '$a_{1}=3,\\ a_{n+1}=2a_{n}$ で定まる数列の一般項 $a'},
 '17-3': {'skill': 'Z1',
          'sub': ['S1'],
          'level': 'basic',
          'group': '等差型・等比型',
          'head': '$a_{1}=10,\\ a_{n+1}=a_{n}-4$ で定まる数列の第 $8'},
 '17-4': {'skill': 'Z1',
          'sub': ['T1'],
          'level': 'standard',
          'group': '等差型・等比型',
          'head': '$a_{1}=\\dfrac{1}{2},\\ a_{n+1}=3a_{n}$ で定'},
 '18-1': {'skill': 'Z2',
          'sub': ['T1'],
          'level': 'basic',
          'group': 'まず手順をなぞる（穴埋め）',
          'head': '$a_{1}=1,\\ a_{n+1}=2a_{n}+3$ の一般項を求める次の過'},
 '18-2': {'skill': 'Z2',
          'sub': ['T1'],
          'level': 'standard',
          'group': '特性方程式型（基本）',
          'head': '$a_{1}=1,\\ a_{n+1}=3a_{n}+2$ で定まる数列の一般項 '},
 '18-3': {'skill': 'Z2',
          'sub': ['T1'],
          'level': 'standard',
          'group': '特性方程式型（基本）',
          'head': '$a_{1}=2,\\ a_{n+1}=2a_{n}+3$ で定まる数列の一般項 '},
 '18-4': {'skill': 'Z2',
          'sub': ['T1'],
          'level': 'standard',
          'group': '特性方程式型（基本）',
          'head': '$a_{1}=4,\\ a_{n+1}=3a_{n}-4$ で定まる数列の一般項 '},
 '18-5': {'skill': 'Z2',
          'sub': ['T1'],
          'level': 'standard',
          'group': '特性方程式型（基本）',
          'head': '$a_{1}=2,\\ a_{n+1}=4a_{n}+3$ で定まる数列の一般項 '},
 '18-6': {'skill': 'Z2',
          'sub': ['T1'],
          'level': 'standard',
          'group': '特性方程式型（応用）',
          'head': '$a_{1}=5,\\ a_{n+1}=2a_{n}-3$ で定まる数列の一般項 '},
 '18-7': {'skill': 'Z2',
          'sub': ['T1'],
          'level': 'standard',
          'group': '特性方程式型（応用）',
          'head': '$a_{1}=0,\\ a_{n+1}=2a_{n}+1$ で定まる数列の一般項 '},
 '18-8': {'skill': 'Z2',
          'sub': ['T1'],
          'level': 'standard',
          'group': '特性方程式型（応用）',
          'head': '$a_{1}=2,\\ a_{n+1}=5a_{n}-4$ で定まる数列の一般項 '},
 '18-9': {'skill': 'Z2',
          'sub': ['T1'],
          'level': 'advanced',
          'group': '特性方程式型（応用）',
          'head': '$a_{1}=3,\\ a_{n+1}=\\dfrac{1}{2}a_{n}+1$ '},
 '19-1': {'skill': 'G3',
          'sub': [],
          'level': 'basic',
          'group': 'まず階差をとる練習',
          'head': '数列 $1,\\ 2,\\ 4,\\ 7,\\ 11,\\ 16,\\ \\ldots$ につ'},
 '19-2': {'skill': 'Z2',
          'sub': ['G3'],
          'level': 'standard',
          'group': '階差型',
          'head': '$a_{1}=1,\\ a_{n+1}=a_{n}+3n$ で定まる数列の一般項 '},
 '19-3': {'skill': 'Z2',
          'sub': ['G3'],
          'level': 'standard',
          'group': '階差型',
          'head': '$a_{1}=2,\\ a_{n+1}=a_{n}+2n+1$ で定まる数列の一般'},
 '19-4': {'skill': 'G3',
          'sub': ['Z2'],
          'level': 'standard',
          'group': '階差型',
          'head': '数列 $1,\\ 3,\\ 7,\\ 13,\\ 21,\\ \\ldots$ の一般項 $'},
 '19-5': {'skill': 'Z2',
          'sub': ['G3'],
          'level': 'standard',
          'group': '階差型',
          'head': '$a_{1}=3,\\ a_{n+1}=a_{n}+4n-1$ で定まる数列の一般'},
 '19-6': {'skill': 'G3',
          'sub': ['Z2'],
          'level': 'standard',
          'group': '階差型',
          'head': '数列 $2,\\ 3,\\ 6,\\ 11,\\ 18,\\ \\ldots$ の一般項 $'},
 '20-1': {'skill': 'Z3',
          'sub': [],
          'level': 'basic',
          'group': 'まず具体的な項で確かめる',
          'head': '数列の初項から第 $n$ 項までの和が $S_{n}=n^{2}$ であるとき、'},
 '20-2': {'skill': 'Z3',
          'sub': [],
          'level': 'standard',
          'group': '$S_n$ から $a_n$ を作る',
          'head': '数列の初項から第 $n$ 項までの和が $S_{n}=n^{2}+3n$ である'},
 '20-3': {'skill': 'Z3',
          'sub': [],
          'level': 'standard',
          'group': '$S_n$ から $a_n$ を作る',
          'head': '数列の初項から第 $n$ 項までの和が $S_{n}=2n^{2}-n$ である'},
 '20-4': {'skill': 'Z3',
          'sub': ['T1'],
          'level': 'standard',
          'group': '$S_n$ から $a_n$ を作る',
          'head': '数列の初項から第 $n$ 項までの和が $S_{n}=3^{n}-1$ であると'},
 '20-5': {'skill': 'Z3',
          'sub': [],
          'level': 'advanced',
          'group': '$S_n$ から $a_n$ を作る',
          'head': '数列の初項から第 $n$ 項までの和が $S_{n}=n^{2}+2$ であると'},
 '21-1': {'skill': 'Z4',
          'sub': ['G1'],
          'level': 'basic',
          'group': '帰納法の型を覚える',
          'head': '次は「すべての自然数 $n$ について $1+3+5+\\cdots+(2n-1)'},
 '21-2': {'skill': 'Z4',
          'sub': [],
          'level': 'standard',
          'group': '帰納法で証明する',
          'head': '数学的帰納法を用いて、すべての自然数 $n$ について $1\\cdot 2+2\\'},
 '21-3': {'skill': 'Z4',
          'sub': [],
          'level': 'advanced',
          'group': '帰納法で証明する',
          'head': '数学的帰納法を用いて、すべての自然数 $n$ について $2^{n}\\geqq '},
 '22-1': {'skill': 'Z3',
          'sub': [],
          'level': 'standard',
          'group': '型を当ててから解く',
          'head': '初項から第 $n$ 項までの和が $S_{n}=2n^{2}+n$ である。① '},
 '22-2': {'skill': 'Z1',
          'sub': ['S1'],
          'level': 'basic',
          'group': '型を当ててから解く',
          'head': '$a_{1}=7,\\ a_{n+1}=a_{n}+5$ である。① 型の名前を書'},
 '22-3': {'skill': 'Z2',
          'sub': ['T1'],
          'level': 'standard',
          'group': '型を当ててから解く',
          'head': '$a_{1}=3,\\ a_{n+1}=3a_{n}-4$ である。① 型の名前を'},
 '22-4': {'skill': 'Z1',
          'sub': ['T1'],
          'level': 'basic',
          'group': '型を当ててから解く',
          'head': '$a_{1}=2,\\ a_{n+1}=4a_{n}$ である。① 型の名前を書き'},
 '22-5': {'skill': 'Z2',
          'sub': ['G3'],
          'level': 'standard',
          'group': '型を当ててから解く',
          'head': '$a_{1}=1,\\ a_{n+1}=a_{n}+4n$ である。① 型の名前を'},
 '22-6': {'skill': 'Z2',
          'sub': ['T1'],
          'level': 'advanced',
          'group': '型を当ててから解く',
          'head': '$a_{1}=1,\\ a_{n+1}=\\dfrac{1}{3}a_{n}+2$ '},
 '23-1': {'skill': 'G1',
          'sub': [],
          'level': 'basic',
          'group': 'Σの公式（そのまま代入）',
          'head': '$\\displaystyle\\sum_{k=1}^{15} k$ を求めよ。'},
 '23-2': {'skill': 'G1',
          'sub': [],
          'level': 'basic',
          'group': 'Σの公式（そのまま代入）',
          'head': '$\\displaystyle\\sum_{k=1}^{8} k^{2}$ を求めよ'},
 '23-3': {'skill': 'G1',
          'sub': [],
          'level': 'basic',
          'group': 'Σの公式（そのまま代入）',
          'head': '$\\displaystyle\\sum_{k=1}^{5} k^{3}$ を求めよ'},
 '23-4': {'skill': 'G1',
          'sub': [],
          'level': 'basic',
          'group': 'Σの公式（そのまま代入）',
          'head': '$\\displaystyle\\sum_{k=1}^{n} 3$ を $n$ の式'},
 '23-5': {'skill': 'G2',
          'sub': ['G1'],
          'level': 'standard',
          'group': 'Σの式計算（バラす）',
          'head': '$\\displaystyle\\sum_{k=1}^{n}(4k+1)$ を $n'},
 '23-6': {'skill': 'G2',
          'sub': ['G1'],
          'level': 'standard',
          'group': 'Σの式計算（バラす）',
          'head': '$\\displaystyle\\sum_{k=1}^{n}(2k-3)$ を $n'},
 '23-7': {'skill': 'G2',
          'sub': ['G1'],
          'level': 'standard',
          'group': 'Σの式計算（バラす）',
          'head': '$\\displaystyle\\sum_{k=1}^{n} k(k+2)$ を $'},
 '23-8': {'skill': 'G2',
          'sub': ['G1'],
          'level': 'standard',
          'group': 'Σの式計算（バラす）',
          'head': '$\\displaystyle\\sum_{k=1}^{n} (k^{2}-k)$ '},
 '23-9': {'skill': 'G4',
          'sub': [],
          'level': 'advanced',
          'group': '部分分数分解',
          'head': '$\\displaystyle\\sum_{k=1}^{n}\\dfrac{1}{(k'},
 '23-10': {'skill': 'G4',
           'sub': [],
           'level': 'standard',
           'group': '部分分数分解',
           'head': '$\\displaystyle\\sum_{k=1}^{20}\\dfrac{1}{k'},
 '24-1': {'skill': 'S2',
          'sub': ['S1'],
          'level': 'standard',
          'group': '等差数列を決定する（連立）',
          'head': '第 $4$ 項が $14$、第 $9$ 項が $34$ である等差数列の初項と公'},
 '24-2': {'skill': 'S2',
          'sub': ['S1'],
          'level': 'standard',
          'group': '等差数列を決定する（連立）',
          'head': '第 $3$ 項が $7$、第 $8$ 項が $22$ である等差数列の一般項 $'},
 '24-3': {'skill': 'S3',
          'sub': [],
          'level': 'basic',
          'group': '等差数列の和',
          'head': '初項 $5$、公差 $4$ の等差数列の、初項から第 $15$ 項までの和を求め'},
 '24-4': {'skill': 'S3',
          'sub': ['S1'],
          'level': 'standard',
          'group': '等差数列の和',
          'head': '$2+5+8+\\cdots+92$ を求めよ。'},
 '24-5': {'skill': 'S3',
          'sub': ['S1'],
          'level': 'standard',
          'group': '等差数列の和',
          'head': '$1$ から $200$ までの整数のうち、$3$ の倍数すべての和を求めよ。'},
 '24-6': {'skill': 'S4',
          'sub': ['S3'],
          'level': 'advanced',
          'group': '等差数列の和',
          'head': '初項 $30$、公差 $-4$ の等差数列で、初項から第 $n$ 項までの和 $'},
 '24-7': {'skill': 'T3',
          'sub': [],
          'level': 'standard',
          'group': '等比数列の和',
          'head': '初項 $1$、公比 $3$ の等比数列の、初項から第 $6$ 項までの和を求めよ'},
 '24-8': {'skill': 'T3',
          'sub': [],
          'level': 'standard',
          'group': '等比数列の和',
          'head': '初項 $2$、公比 $4$ の等比数列の、初項から第 $5$ 項までの和を求めよ'},
 '24-9': {'skill': 'T3',
          'sub': ['T1'],
          'level': 'standard',
          'group': '等比数列の和',
          'head': '$3+6+12+\\cdots+192$ を求めよ。'},
 '24-10': {'skill': 'T3',
           'sub': [],
           'level': 'basic',
           'group': '等比数列の和',
           'head': '初項 $81$、公比 $\\dfrac{1}{3}$ の等比数列の、初項から第 $'},
 '25-1': {'skill': 'X3',
          'sub': ['V1'],
          'level': 'standard',
          'group': '3点が一直線上にある条件',
          'head': '3点 $\\mathrm{A}(2,\\,1),\\ \\mathrm{B}(5,\\,3'},
 '25-2': {'skill': 'X3',
          'sub': ['V3'],
          'level': 'standard',
          'group': '3点が一直線上にある条件',
          'head': '3点 $\\mathrm{A}(1,\\,1),\\ \\mathrm{B}(3,\\,4'},
 '25-3': {'skill': 'X3',
          'sub': ['V3'],
          'level': 'standard',
          'group': '3点が一直線上にある条件',
          'head': '3点 $\\mathrm{A}(1,\\,2),\\ \\mathrm{B}(4,\\,8'},
 '25-4': {'skill': 'V3',
          'sub': ['V1'],
          'level': 'basic',
          'group': '成分から分解する（連立）',
          'head': '$\\vec{a}=(1,\\,1),\\ \\vec{b}=(2,\\,-1)$ のとき'},
 '25-5': {'skill': 'V3',
          'sub': ['V1'],
          'level': 'standard',
          'group': '成分から分解する（連立）',
          'head': '$\\vec{a}=(3,\\,1),\\ \\vec{b}=(1,\\,-2)$ のとき'},
 '25-6': {'skill': 'X3',
          'sub': [],
          'level': 'basic',
          'group': '一次独立と係数比較',
          'head': '$\\vec{a},\\ \\vec{b}$ は $\\vec{0}$ でなく平行でない'},
 '25-7': {'skill': 'X3',
          'sub': [],
          'level': 'standard',
          'group': '一次独立と係数比較',
          'head': '$\\vec{a},\\ \\vec{b}$ は一次独立とする。$s\\vec{a}+t'},
 '25-8': {'skill': 'X1',
          'sub': ['V1'],
          'level': 'standard',
          'group': '一次独立と係数比較',
          'head': '三角形 OAB において $\\overrightarrow{\\mathrm{OA'},
 '26-1': {'skill': 'W1',
          'sub': [],
          'level': 'basic',
          'group': '内積となす角',
          'head': '$\\vec{a}=(3,\\,1),\\ \\vec{b}=(2,\\,-4)$ の内積'},
 '26-2': {'skill': 'W1',
          'sub': [],
          'level': 'standard',
          'group': '内積となす角',
          'head': '$|\\vec{a}|=4,\\ |\\vec{b}|=5$ で、$\\vec{a}$ '},
 '26-3': {'skill': 'W2',
          'sub': ['W1', 'V2'],
          'level': 'standard',
          'group': '内積となす角',
          'head': '$\\vec{a}=(2,\\,0),\\ \\vec{b}=(1,\\,\\sqrt{3}'},
 '26-4': {'skill': 'W3',
          'sub': [],
          'level': 'basic',
          'group': '垂直条件',
          'head': '$\\vec{a}=(3,\\,-2)$ と $\\vec{b}=(k,\\,6)$ が'},
 '26-5': {'skill': 'W3',
          'sub': ['V2'],
          'level': 'standard',
          'group': '垂直条件',
          'head': '$\\vec{a}=(1,\\,-3)$ に垂直で、大きさが $\\sqrt{10}$'},
 '26-6': {'skill': 'W3',
          'sub': ['V2'],
          'level': 'standard',
          'group': '垂直条件',
          'head': '$\\vec{a}=(1,\\,-3)$ に垂直な単位ベクトルをすべて求めよ。'},
 '26-7': {'skill': 'W4',
          'sub': ['V2'],
          'level': 'standard',
          'group': '内積と大きさ',
          'head': '$|\\vec{a}|=3,\\ |\\vec{b}|=2,\\ \\vec{a}\\cdo'},
 '26-8': {'skill': 'W4',
          'sub': ['V2'],
          'level': 'standard',
          'group': '内積と大きさ',
          'head': '$|\\vec{a}|=5,\\ |\\vec{b}|=3,\\ \\vec{a}\\cdo'},
 '26-9': {'skill': 'W4',
          'sub': ['V2'],
          'level': 'advanced',
          'group': '内積と大きさ',
          'head': '$|\\vec{a}|=3,\\ |\\vec{b}|=4,\\ \\vec{a}\\cdo'},
 '27-1': {'skill': 'Y1',
          'sub': ['V2'],
          'level': 'basic',
          'group': '空間の成分と大きさ',
          'head': '空間の2点 $\\mathrm{A}(2,\\,1,\\,3),\\ \\mathrm{B'},
 '27-2': {'skill': 'Y1',
          'sub': ['V2'],
          'level': 'basic',
          'group': '空間の成分と大きさ',
          'head': '空間の2点 $\\mathrm{A}(1,\\,1,\\,2),\\ \\mathrm{B'},
 '27-3': {'skill': 'Y1',
          'sub': ['V2'],
          'level': 'standard',
          'group': '単位ベクトルと垂直',
          'head': '$\\vec{a}=(1,\\,4,\\,8)$ と同じ向きの単位ベクトルを求めよ。'},
 '27-4': {'skill': 'Y2',
          'sub': ['W3'],
          'level': 'standard',
          'group': '単位ベクトルと垂直',
          'head': '$\\vec{a}=(3,\\,-1,\\,2)$ と $\\vec{b}=(1,\\,k'}}
